### ISSUE TITLE
Pkg/healthcheck: no timeout of Get

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1109]
The health check is doing a Get without a timeout... I suspect this is the reason why it is so bad on a remote not being there. This came about in a or a while back (ping the authors later). 

This should be fixed. And we can probably remove the okUntil, so we only have one metric for health: Fails.

**Comment by miekg** [comment]
This was done in #749 

/cc @ghostflame

**Comment by ghostflame** [comment]
Hi,

So it's worth finding out if the timeout option in the HTTP implementation includes time spend in connect().  If it doesn't, then Get timeout will not solve the problem.  Also, okUntil as a concept means that we have to refresh healthy status, the default is unhealthy (because we don't, for whatever reason, know that it is healthy).

IIRC, HTTP timeout is meant to be taken after issuing the request, and limiting the time a server may take to answer.  So unless the Go implementation is very different, it won't include time spent in tcp connect(), which is where the issue with an absent server is.

I don't know the underlying behaviour, but that is why I didn't try to prevent a fetch taking a long time - I went for a method that worked even if it did.

**Comment by miekg** [comment]
Thanks for chiming in :) 

See https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/ (I trust cloudflare on this):

> The easiest to use is the Timeout field of http.Client. It covers the entire exchange, from Dial (if a connection is not reused) to reading the body.

See  #1110 for a possible simplification.

**Comment by ghostflame** [comment]
Yeah, the way that reads suggests http.Client.Timeout does what you need.

I would be tempted to try out net.Dialer.Timeout set to a pretty aggressive value, maybe 20 msec (or a config'd higher value for very distant remotes) and fail fast - it would have the secondary effect of making a server that is struggling to respond look dead, taking pressure off it.  That's not great in all circumstances - if every server is struggling (but alive) it might declare every upstream dead - but if its made configurable (0 disables dialer timeout checks) then the user can decide.  It's certainly a much clearer indication of an unhappy server than HTTP response.  If the kernel is too busy to handle a TCP connection quickly, leave it alone :-)

**Comment by miekg** [comment]
fixed via #1110
