### ISSUE TITLE
plugin/autopath: add namespace 

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1139]
Wouldn't specifying a namespace for *autopath* fix the caching issue (diff. pods will see each other's resolved name if *caching* is used)?

We should also add a metrics that autopath has been done and make the slightly logging better.

**Comment by chrisohaver** [comment]
I don't believe  it fixes the issue, even if you enable autopath in only one namespace.

An example of the issue:

Say there is a service `my-svc` in namespace `my-ns` with IP `1.2.3.4`.  In the scenario below, pods attempt to look up the DNS record for this service.

A pod in namespace `a`, queries for `my-svc.my-ns`, and receives ...
```
  my-svc.my-ns.a.svc.cluster.local. IN CNAME my-svc.my-ns.svc.cluster.local.
  my-svc.my-ns.svc.cluster.local. IN A 1.2.3.4
```
This is because of autopath completion. The client querying `my-svc.my-ns`, actually tries `my-svc.my-ns.a.svc.cluster.local.` first.  This is the query (`my-svc.my-ns`) joined with the first search domain (`a.svc.cluster.local.`)  CoreDNS receives this query, gets an `NXDOMAIN`, then tries the next query in the search path (`svc.cluster.local.`).  This results in a search for `my-svc.my-ns.svc.cluster.local.`, which is a valid service dns name.  Coredns constructs the answer - the `CNAME` "glue" and the `A` record.

This answer becomes cached, for the original question `my-svc.my-ns.a.svc.cluster.local.`

Now, if any pod in any namespace (including `a`) queries for the fully qualified name `my-svc.my-ns.a.svc.cluster.local.`, it will get `1.2.3.4`, due to the cached entry.
The problem is that `1.2.3.4` is the IP for `my-svc.my-ns.svc.cluster.local.`. The service `my-svc.my-ns.a.svc.cluster.local.` probably does not exist.  If it did exist (i.e. if `my-scv` is an endpoint in a service named `my-ns` in the namespace `a` ... unlikely), it would have a different IP.

The only way to really fix this is to index the namespace of the remote pod in the cache (i.e. instead of just indexing on the question, indexing on question and remote namespace).  But this is impractical. (and it would not fix the issue 100%)

That said, the autopath/caching issue is a somewhat contrived and narrow case.  IMO unlikely to be encountered.  The generalization `When the *cache* plugin is enabled it is possible for pods in different namespaces to get the same answer.` sounds scary.  But the actual issue is less so.

**Comment by chrisohaver** [comment]
For the sake of discussion, I think the 100% fix would be ...
* Don't cache any results from autopath.  
* Don't use cache for autopath queries.

**Comment by chrisohaver** [comment]
Tangentially, I just noticed that `autopath` comes before `cache` in the plugins list.

I think this means that all queries processed will require a namespace lookup (i.e. an IP look up in the pod index), even for queries that are cached.  If we were indexing cache on namespace and query, then this would be required.  But I don't think we are, so it seems like extra work.  Is there another reason for this plugin ordering?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/autopa..." ]
>Tangentially, I just noticed that `autopath` comes before `cache` in the plugins list.
>
>I think this means that all queries processed will require a namespace lookup (i.e. an IP look up in the pod index), even for queries that are cached.  If we were indexing cache on namespace and query, then this would be required.  But I don't think we are, so it seems like extra work.  Is there another reason for this plugin ordering?

ghe.. No there is no reason for that; just put it a some number. Good point; 
shall we leave the ordering lke this (and drop this PR?)

**Comment by chrisohaver** [comment]
I think the metrics and better logging may be worth keeping.

I think we'd see a performance boost if `autopath` is processed after the `cache` plugin - but not sure if changing order would have other unintended consequences.

**Comment by johnbelamaric** [comment]
Since this comes before cache, doesn't the issue described above go away?

**Comment by chrisohaver** [comment]
>Since this comes before cache, doesn't the issue described above go away?

It remains.  The first query by the first pod in the `a` namespace is still cached.
Subsequent queries from pods in the same namespace still use the cache (when testing the first domain in the search path).
Subsequent queries from pods in other namespaces still use the cache (in these cases autopath isn't employed).
The order doesn't matter in this regard.
