### ISSUE TITLE
k8s: Prioritize pod in the same region over other pods

### ISSUE THREAD

**Issue by klausenbusk** [coredns/coredns#1219]
When running ex MySQL clusters across multiple region, it would be preferred if ex PHP connect to the nearest one (to reduce latency).

Ex: If it get a DNS request from a pod in region X, it respond with a pod ip in the same region if available.

**Comment by johnbelamaric** [comment]
You have a K8s cluster spanning regions?

**Comment by klausenbusk** [comment]
> You have a K8s cluster spanning regions?

I think the term locations is more correct. I use DigitalOcean and have servers in FRA1, AMS3 and LON1.

**Comment by stp-ip** [comment]
So you are running one cluster spanning these locations/regions compared to multiple clusters aka one for each location/region?

**Comment by johnbelamaric** [comment]
OK. We have a similar use case where we want to prefer a pod on the same node if possible. Of course you have to know the node of source pod for the query (which we can do with `pods verified`). Then you need a way of specifying the policy of which to pick. We have some plans/ideas around integrating with a generalized policy engine which may be able to accomplish this. Really it's a more sophisticated version of the `load_balancer`, where instead of randomizing the order we pick one based on policy.

**Comment by klausenbusk** [comment]
> So you are running one cluster spanning these locations/regions

Correct.



> compared to multiple clusters aka one for each location/region?

It add way too much overhead, as the cluster isn't that big (3 master nodes + 6 worker nodes + 2 VPN nodes (for outgoing traffic))

**Comment by miekg** [comment]
Could this potentially be done in the load balancer plugin? That would be
really nice if so.

**Comment by johnbelamaric** [comment]
Yes, it could be, and I think that would be best. It needs a way to move data for making the decision between plugins, I am thinking that the Context is the right place to do that. So, K8s could add some data in the context that the load balancer could use to make a selection. We can build policies directly into the `load_balancer` for now but longer term I want to be able to use a general policy engine.

**Comment by miekg** [comment]
won't fix

don't think any is working on this.
