### ISSUE TITLE
plugin/k8s: Support IPv6

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#1236]
Add support and tests for IPv6 in k8s plugin.

* IPv6 IP addresses for services, endpoints and pods
* IPv6 dashed-IP name for endpoints and pods
* IPv6 IP based indexes and reverse lookups
* IPv6 api endpoint

Not specific to k8s: verify IPv6 reverse CIDR

**Comment by fturib** [comment]
for information : IPv6 is an alpha feature for K8s v1.9 (GA on 12/23/2017).

**Comment by danehans** [comment]
The ipv6 working group is using kubeadm as the reference ipv6 k8s deployment tool. I see kubeadm supports coredns. Does a bullet needed to be added to this issue to update kubeadm to support the new ipv6 "knobs" in coredns?

**Comment by fturib** [comment]
@danehans : can you point us to a document that would explain what is expected here, so that CoreDNS could be used within a ipv6 k8s deployment ? What would need to be added to kubeadm ?

**Comment by chrisohaver** [comment]
> Does a bullet needed to be added to this issue to update kubeadm to support the new ipv6 "knobs" in coredns?

@danehans: I don't think coredns will will have any special knobs for IPv6. The one related configuration facing element that kubeadm touches is reverse zone cidr for services.  However, from kube-adm perspective this is just a string, and I expect coredns will accept an ipv4 or ipv6 without issue.

**Comment by danehans** [comment]
@fturib I do not know the coredns code within kubeadm well enough to provide detailed guidance. In general, whatever configuration options that must be set to run coredns in IPv6 mode need to be exposed through kubeadm.

**Comment by danehans** [comment]
@chrisohaver that's good to know. The less configuration knobs the better.

**Comment by danehans** [comment]
I see the associated PR's have merged, but this Issue remains open. What else is needed to close this issue? Since kubeadm supports IPv6 and CoreDNS, have you deployed a test cluster with IPv6 and CoreDNS enabled? @mmueen is working on the IPv6 upstream docs. In the meantime, @leblancd created a [deployment guide](https://github.com/leblancd/kube-v6) that can assist you with deploying an IPv6 cluster. You can also try [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster) for testing, which @pmichali added IPv6 support to.

**Comment by chrisohaver** [comment]
@danehans, thanks for the link.  I'll spin up an ipv6 k8s with kubeadm and verify.

**Comment by fturib** [comment]
@danehans : is there some expectation to have some e2e tests for the Ipv6 feature for this release (or next release) ?

**Comment by fturib** [comment]
@danehans : from your document "v1.9 Release: IPv6 PR Tracker", i see some work on e2e, like this issue : Add brackets around IPv6 addrs in e2e test IP:port endpoints #52748.
Does it mean we could run e2e testing of k8s in Ipv6 mode (on local cluster for example ?).

**Comment by danehans** [comment]
[Here](https://github.com/leblancd/kube-v6-test) is a doc that will help you run e2e. It looks like we will miss adding e2e until after kubecon.

**Comment by fturib** [comment]
that still need to setup manually the IPv6 cluster. By e2e setup I was thinking the automatic deployment of the Ipv6 cluster in order to run the e2e tests - I mean adding the deployment in kubernetes/test-infra. 
Will that deployment be ready after kubecon ?

Is there is  "more automated" way to have an Ipv6 cluster ? or a way to access an existing Ipv6 setup we could modify by shutting down kube-dns and starting CoreDNS .. in order to make some manual tests ?

**Comment by danehans** [comment]
Understood. We intend on using [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster) to deploy a v6 k8s cluster to gce for e2e. We are working through adding the necessary bits to [test-infra](https://github.com/kubernetes/test-infra). Unfortunately, this will be completed after kubecon.

kubeadm-dind-cluster is fairly automated. @pmichali added IPv6 support to the project and can help you with any questions you may have. We do have IPv6 clusters, but they are internal.

**Comment by danehans** [comment]
@leblancd will be providing an overview of the ipv6 alpha feature during the sig-network update presentation at kubecon. Please let us know if you have successfully tested k8s ipv6 with coredns so we can update the slide content accordingly.

**Comment by fturib** [comment]
@danehans : unfortunately no. I did not start this task yet.

**Comment by fturib** [comment]
Test is in progress. I reached to deploy DinD with Ipv6 only environment for K8s.
I modify the deployment to integrate option for "coredns" or "kube-dns".

At first sight, CoreDNS is replying correctly .. but need more thorough tests.

**Comment by miekg** [comment]
Is there anything left to be done here?

**Comment by fturib** [comment]
an update on what is done so far for Ipv6 tests (as of today - Jan 8th 2018).

I used DinD to build an Ipv6 only cluster (https://github.com/Mirantis/kubeadm-dind-cluster).
I ws able to:

- update configuration of DiND to have kubeadm with option coreDNS
- have the cluster run smoothly in Ipv6, running CoreDNS
- run manual tests checking replies of CoreDNS

So far it is good. But I am not sure to cover all use cases.

Then I tried to run the e2e tests (that you can run in that DinD-cluster.sh) against the Ipv6 cluster.
(the [conformance] tests). All but 7 are OK.

In those 97 that are failing we have the 2 main DNS tests:

```
[Fail] [sig-network] DNS [It] should provide DNS for services  [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns.go:170

[Fail] [sig-network] DNS [It] should provide DNS for the cluster  [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns.go:170
```

They are failing because 
1- the test was IPV4 (A Queries) only
2- the test case is not compatible Ipv6. The client pod setup to send queries and build files on result is not Ipv6 compatible. 

I fixed the Test Suite and queries Ipv6 mode (sending AAAA queries).
I was interrupted when I was trying to fix the second part : having a client pod compatible with Ipv6.

I have my environment still setup and expect to continue later during this week.

**Comment by miekg** [comment]
Closing this as done
