### ISSUE TITLE
epp client to upload DS/KEY

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#131]
When doing DNSSEC, we should probably also add the possibility to automatically upload a DS/DNSKEY to the parent.

Also: condering _not_ support KSK/ZSK, but just using CSK.

**Comment by pmoroney** [comment]
As much as I would love to have an EPP client written in go, it isn't likely that an EPP client would be useful to many users. Only registrars typically have access to the EPP endpoints at registries. And even then, it is likely that they don't allow individual services to connect directly to the EPP endpoints since the registries impose connection count limits.

But luckily, there is an ietf draft for an API that 3rd parties can update the DS record: https://tools.ietf.org/html/draft-ietf-regext-dnsoperator-to-rrr-protocol-03
Unfortunately, I don't know of any registrars that have implemented it yet, not even the one I work for, name.com.

**Comment by miekg** [comment]
Indeed, seems we can just reuse [this code](https://github.com/caddyserver/dnsproviders)
