### ISSUE TITLE
Why does proxy return 0 rcode when it shouldn't?

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#1428]
Here:

https://github.com/coredns/coredns/blob/master/plugin/proxy/proxy.go#L107

If there is a good reason for this, can we put a comment in the code? Because it seems to me it breaks the the whole return value for the chain.

**Comment by johnbelamaric** [comment]
@varyoo looks like this came from the DNS tap stuff

**Comment by miekg** [comment]
but backendErr == nil, and `0` == dns.RcodeSuccess? What break here?

**Comment by johnbelamaric** [comment]
backendErr is a go error, not a non-zero rcode. So, for example, the reply rcode could be NXDOMAIN and the backendErr is still nil. We should be returning the rcode from the upstream.

**Comment by miekg** [comment]
Geh, we (I?) removed that from plugin.md:
~~~
From the Caddy docs:
-
-> Oh yes, those pesky return values on ServeHTTP(). You read the documentation so you already know
-> what they mean. But what does that imply for the behavior of your plugin?
->
-> Basically, return a status code only if you did NOT write to the response body. If you DO write to
-> the response body, return a status code of 0. Return an error value if your plugin encountered
-> an error that you want logged. It is common to return an error status and an error value together,
-> so that the error handler up the chain can write the correct error page.
->
-> The returned status code is not logged directly; rather, it tells plugin higher up the chain
-> what status code to use if/when the response body is written. Again, return a 0 status if you've
-> already written a body!
-
-In the DNS status codes are called rcodes and it's slightly harder to return the correct
-answer in case of failure.
-
-So CoreDNS treats:
-
-* SERVFAIL (dns.RcodeServerFailure)
-* REFUSED (dns.RcodeRefused)
-* FORMERR (dns.RcodeFormatError)
-* NOTIMP (dns.RcodeNotImplemented)
-
-as special and will then assume nothing has written to the client. In all other cases it is assumes
-something has been written to the client (by the plugin).
-
-## Hooking It Up
~~~

**Comment by johnbelamaric** [comment]
Hmm. OK. I don't think we should call it an RCODE then. It's something else. Causes confusion. Maybe like "needsWrite" or something. Probably should put that back in the plugin.md though...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Why does prox..." ]
>Hmm. OK. I don't think we should call it an RCODE then. It's something else. Causes confusion. Maybe like "needsWrite" or something. Probably should put that back in the plugin.md though...

agreed.

think caddy calls is response code, but yeah, I see the confusion.

**Comment by miekg** [comment]
Fixes by updating the docs. This is WAI
