### ISSUE TITLE
plugin/metrics: only metrics from a single zone block are reported [BUG]

### ISSUE THREAD

**Issue by achille-roussel** [coredns/coredns#1492]
I'm observing what I believe is not the expected behavior with the metrics plugin (or at least not the documented behavior). 

Considering a configuration like this:
```
.com {
  proxy . 127.0.0.1:53
  autopath /zones.conf
  prometheus :9053
}

. {
  proxy . 127.0.0.1:53
  prometheus :9053
}
```
The `coredns_dns_` metrics which are generated by each metrics plugin are properly reported for both zones, however the metrics of the proxy and autopath plugins are not. Either metrics of the `.com` and `.` zones are reported. I haven't been able to determine which block takes priority, it seems kind of random.

The issue I believe comes from the fact that plugins in each zone will be attached to the `*metrics.Metrics` instance of their block (see this example https://github.com/coredns/coredns/blob/master/plugin/cache/setup.go#L33-L48), but only one `*metrics.Metrics` instance is configured to listen on a pair of IP and port (see https://github.com/coredns/coredns/blob/master/plugin/metrics/setup.go#L32-L39 and https://github.com/coredns/coredns/blob/master/plugin/metrics/metrics.go#L87-L104).
This results in having some plugins _wired_ to a metrics instance that is not serving requests.

A possible solution would be to share the `*prometheus.Registry` between `*metrics.Metrics` instances that are configured to be served on the same port. It means the `(*metrics.Metrics).MustRegister` method must be revisited to not panic when a metric is registered multiple times by multiple instantiations of a plugin.

I'm available to send a fix, but I wanted to get another pair of eyes on it in case I missed something.

**Comment by johnbelamaric** [comment]
See #1452. I think we need to decide on how we want it to work. Should metrics just be globally enabled, or per server block? Right now it's getting confused.

**Comment by achille-roussel** [comment]
Global plugins is something I was thinking of as well, but that seems more disruptive than fixing the current broken behavior (it seems possible to do so in this case), what do you think?

**Comment by fturib** [comment]
looking at https://github.com/coredns/coredns/blob/master/plugin/metrics/setup.go#L32-L39, I would think that the plugin is assuming that you would change the address for each of your directives.

then, you would have a series of stats on each of the listening addresses.

However, because of lines #47 o #49, there is maybe some race conditions where the last directive is read the the address may not be set soon enough in uniqAddr to be generate the m.OnStartup ...



```
.com {
  proxy . 127.0.0.1:53
  autopath /zones.conf
  prometheus **:9053**
}

. {
  proxy . 127.0.0.1:53
  prometheus **:9054**
}
```

**Comment by achille-roussel** [comment]
That’s what I thought initially, but there’s code in place to make sure that only a single listener is started when the same address is configured on multiple blocks... so the intention is unclear here (it would be useful to h e the author’s input on it).

Using a different port for every block becomes quickly unmanageable tho. If that’s the expected usage it would help to document it as well.

**Comment by miekg** [comment]
Note that *supporting* different address was the only use case I could think of, in no way that was intended as "this is how you should use it", more like "if you're crazy enough, this is supported".

A short-term fix would be appreciated, as I suspect #1452 will take more time

**Comment by achille-roussel** [comment]
Thanks for the context 👍 I'll work on something over the weekend.

**Comment by miekg** [comment]
Coming back to this.

I think some of the confusion is also the *metrics* will give your metrics for the whole process: `coredns_dns.*`.

**Comment by miekg** [comment]
OK, coming back to this; I'm disregarding *proxy* because I want to get rid of it (#1143). So I'm breaking this up smaller parts to understand where thing fail. First I'm start using this *different* Corefile:

~~~
om {
  forward . 8.8.8.8
  prometheus :9053
}

. {
  forward . 8.8.8.8
  prometheus :9053
}
~~~
Now I send two queries:
~~~
dig @localhost -p 1053 mx example.com
dig @localhost -p 1053 mx example.net
~~~
These are handled by the two different  server. Next I scrape the metrics endpoints:
~~~
# HELP coredns_forward_request_count_total Counter of requests made per upstream.
# TYPE coredns_forward_request_count_total counter
coredns_forward_request_count_total{to="8.8.8.8:53"} 2
# HELP coredns_forward_request_duration_seconds Histogram of the time each request took.
# TYPE coredns_forward_request_duration_seconds histogram
coredns_forward_request_duration_seconds_sum{to="8.8.8.8:53"} 0.013323782
coredns_forward_request_duration_seconds_count{to="8.8.8.8:53"} 2
# HELP coredns_forward_response_rcode_count_total Counter of requests made per upstream.
# TYPE coredns_forward_response_rcode_count_total counter
coredns_forward_response_rcode_count_total{rcode="NOERROR",to="8.8.8.8:53"} 2
# HELP coredns_forward_socket_count_total Gauge of open sockets per upstream.
# TYPE coredns_forward_socket_count_total gauge
coredns_forward_socket_count_total{to="8.8.8.8:53"} 1
~~~
So this works OK, **but only for the counter** which is incremented by both. The *gauge* also set by both and hence 1, not 2.

So this isn't IMO a prometheus registration problem, but a non-uniqueness of the metric

**Comment by miekg** [comment]
I.e. I don't there is a need to change much; we only need to make sure all metrics are also labeled with the zone (zones?) from the server block. For the above config it is easy, but:

~~~
.com . {
   forward . 8.8.8.8
   metrics
}
~~~
it is more interesting; I'm not sure we have a function already that allows you so retrieve why we matched this server.

**Comment by miekg** [comment]
We **can** use the Context for this; in fact this could be one of those things the context is actually made for.

**Comment by miekg** [comment]
only with the bind and port directives we may also want to include those -- not sure if we have access to those though....
I.e. every metrics would then get: `{zone="xx",port="yy",ip="zz"}` as extra labels.

**Comment by miekg** [comment]
See for initial impl: https://github.com/coredns/coredns/pull/1579

**Comment by miekg** [comment]
Ah, we have `*Server` in this code; which has all that info, port and ip

**Comment by miekg** [comment]
`Server.Addr` has this i.e. `dns://:1053` which we can just use in an `addr` label - this should guarantee enough uniqueness.

**Comment by miekg** [comment]
one issue is that you now need to have these labels to update the metric and in *forward* I don't have access to them (in some places) - would be awesome to have some kind of wrapper that did this for you though...

**Comment by miekg** [comment]
#1579 adds some code that allows us to fix this. I'll send another PR that updates all callers of metrics to add this.

**Comment by miekg** [comment]
Only the *dnssec* plugin needs to be updated; all other in tree plugins have out standing PRs

**Comment by miekg** [comment]
fixed
