### ISSUE TITLE
plugin/health plugin/prometheus graceful restart bug

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [coredns/coredns#1604]
Tested on 3e3d8cc845b8e072efc75043c9aa3df318ec3bf3 with Corefile
```
.:53 {
	health 127.0.0.1:8080
	proxy . 8.8.8.8:53
}
```
After graceful restart with "killall -USR1 coredns" we get an error:
```
[INFO] SIGUSR1: Reloading
[INFO] Reloading
[ERROR] SIGUSR1: listen tcp 127.0.0.1:8080: bind: address already in use
```

**Comment by fturib** [comment]
Hi Uladimir,do you have a change in your Corefile between first start and the reload ?
If, yes, can you add both Corefile ?

**Comment by UladzimirTrehubenka** [comment]
I didn't change Corefile between start and reload.

**Comment by fturib** [comment]
@UladzimirTrehubenka : I mismatch the use case. I though was tied to BIND. But in fact your issue is tide to HEALTH plugin.

I guess that there is a complete restart of the Health HTTP listener on port 8080. 
To know : the restart of CoreDNS,  there is a "graceful" restart, which means the former service is not shutdown before the new one is established and validated. From there this issue on listening a second time the same port.
NOTE: for the main listeners (the DNS request listeners), there is some magic in Caddy to allow a second service during the graceful restart. That magic does not happen on the listener created at setup or start by the plugins (like HEALTH, METRICS, ...). The plugin has to deal with check the address before reloading, or not allowing change of address at reload ...

**Comment by UladzimirTrehubenka** [comment]
BTW with Corefile
```
.:53 {
	proxy . 8.8.8.8:53
	prometheus 127.0.0.1:9253
}
```
We didn't get any error in logs but after graceful restart we get
```
curl 127.0.0.1:9253/metrics
curl: (7) Failed to connect to 127.0.0.1 port 9253: Connection refused
```
So this is another one bug.

**Comment by UladzimirTrehubenka** [comment]
Looks like all plugins that use Listen() should do magic with clone binding port (like CoreDNS does for dns port).

**Comment by ephur** [comment]
See this same behavior using the reload plugin when health plugin is enabled (others like prometheus are as well):

2018/03/17 05:23:03 [INFO] Reloading   
2018/03/17 05:23:03 [ERROR] Corefile changed but reload failed: listen tcp :8080: bind: address already in use

**Comment by miekg** [comment]
This patch fixes the above reload problem (lightly tested, but seems to work):
~~~
diff --git a/plugin/health/health.go b/plugin/health/health.go
index f6b82804..8aeb3950 100644
--- a/plugin/health/health.go
+++ b/plugin/health/health.go
@@ -61,6 +61,17 @@ func (h *health) OnStartup() error {
        return nil
 }
 
+func (h *health) OnRestart() error {
+       // relingish our listener as we re-listen on successfull reload
+       if h.ln != nil {
+               if err := h.ln.Close(); err != nil {
+                       return err
+               }
+               h.ln = nil
+       }
+       return nil
+}
+
 func (h *health) OnShutdown() error {
        // Stop polling plugins
        h.pollstop <- true
diff --git a/plugin/health/setup.go b/plugin/health/setup.go
index bd5b5c3f..e06b280d 100644
--- a/plugin/health/setup.go
+++ b/plugin/health/setup.go
@@ -61,6 +61,7 @@ func setup(c *caddy.Controller) error {
 
        c.OnStartup(h.OnStartup)
        c.OnShutdown(h.OnShutdown)
+       c.OnRestart(h.OnRestart)
 
        // Don't do AddPlugin, as health is not *really* a plugin just a separate webserver running.
        return nil
~~~

**Comment by rdrozhdzh** [comment]
OnRestart() handler should be used with care. It is called before new servers instance is created. If the creation is failed for some reason, the old servers instance is expected to continue working. So, seems we should not release any resources in OnRestart()
