### ISSUE TITLE
SIGUSR1: listen tcp:8080: bind: address already in use

### ISSUE THREAD

**Issue by yybear** [coredns/coredns#1618]
i have tow questions:
1. the coredns1.1.0, i enabled the plugin of reload, after sending SIGUSR1, then log shows:

[INFO] SIGUSR1: Reloading
[INFO] Reloading
[ERROR] SIGUSR1: listen tcp:8080: bind: address already in use
how to fix this?

2. other question was at first time i used coredns1.0.4, in this version the plugin of reload can't be used.
so no above problem, but after "Reloading complete", i found this was no effect, i had to recreate coredns pod(removing pod then kubernetes recreated new pod) to make corefile changes to work, may i miss some config item?
my corefile like this (when used coredns1.0.4 )
. 53 {
      error
      health
      cache 30
      kubernetes {..}
      ...
}

**Comment by fturib** [comment]
This issue is the same (I think) that #1604 

NOTE: there are now 2 ways to do a RELOAD:
- using SIGUSR1 (always been there, it is defined by the lib Caddy)
- the plugin RELOAD that aims to automatically reload if there is a change in the Corefile.

The both use the same mechanism.

Although SIGUSR1 was there since long time, it is only when testing RELOAD that we found some of the plugin are not compatible with the reload process - and we are in progress of tuning these plugins.

About your questions

1. #1621 should address your problem with SIGUSR1 and Health. (I understand here you are using the signal, not the RELOAD plugin).

2. I understand that for CoreDNS 1.0.4 used inside K8s, the reload using SIGUSR1 was not working. Where you modifing the Corefile inside the pod - or the Configmap named "coredns" using kubectl ?

**Comment by yybear** [comment]
with CoreDNS 1.0.4, i used the ConfigMap to store config of dns.
so after changed ConfigMap, i used SIGUSR1 to reload coredns

**Comment by yybear** [comment]
you said "for CoreDNS 1.0.4 used inside K8s, the reload using SIGUSR1 was not working", so how to make CoreDNS reload config?
I use the ConfigMap to store the Corefile, but the name is not "coredns", my situation is a bit special. there will be some CoreDNSs for different servers, I will change the corefile to add some ip and domain pairs  by myself, so I hope can reload Corefile to make it sense.
if  using SIGUSR1 was not working, is there other method?

**Comment by fturib** [comment]
I cannot say why SIGUSR1 was not working, for you, using the 1.0.4
I can see that HEALTH would not work properly .. I guess not reloading if you use the same port number, but also not stopping at the right time.

If you remove HEALTH, maybe that will be ok.
As long as your Configmap is udpating the local pod file "Corefile", and you trigger your SIGUSR1 signal AFTER this Corefile is updated, I guess that should work.

I am interested by your use case with k8s, can you elaborate on your use case, and what you are changing from one reload to next reload ?

**Comment by yybear** [comment]
now we want to use k8s to build our complex test system. in my case, there are some "sites", there are hundreds of servers(jboss, nginx, redis etc.) in each site.  the servers will have the same domain(server.xx.com) in different sites.
for example I have tow site: siteA, siteB. In siteA I have a jboss server and an accnount server, jboss server uses domain "account.xx.com" to call the account server. in siteB I also have a a jboss server and an accnount server, jboss server uses the same domain "account.xx.com" to call the account server.
so I need to create a CoreDns server for each site, in the site all servers call each other through the domain managed by this site's CoreDns (when the container in site starting, some script will change the file /etc/resolv.conf of container to make nameserver point to CoreDns server in the site).

when some users create a new server in site, the adminServer needs to add the domain and server ip to site's CoreDns ConfigMap and need to reload to make the server can be accessed. 

in my case, the CoreDns is not used like normal, maybe there is a better way to do this(in a same k8s cluster, servers need to access other other with same domain)

Do you have some ideas?

**Comment by johnbelamaric** [comment]
When you say "site" you do not mean different clusters, do you? You mean something else, like "website" or "project"? This is all in one cluster?

Are you using k8s service names or you want to give different names to them? Can you just use namespaces for this and short DNS names (i.e., "account")? So, you run the account server for siteA in the "site-a" namespace and for siteB in the "site-b" namespace, so the jboss server just uses "account" to reach the server in their own namespace. It relies on the search list in the /etc/resolv.conf which includes the namespace name.

**Comment by yybear** [comment]
@johnbelamaric  yes the "site" is just a logic concept, now all "sites" are in one k8s cluster.

I can't use the k8s namespace and the short DNS name, because the configs of container server(like jboss) are just copying from production environment, so if using the short DNS names we need to change all configs, that will be a big work.

**Comment by chrisohaver** [comment]
Possible long-shot at a convoluted solution...
In k8s, a pod in namespace `ns-1` querying for `account.xyz.com` will actually first try `account.xyz.com.ns-1.svc.cluster.local` 

When CoreDNS receives this, it can ...
1. Do a re-write using `rewrite` plugin, removing the domain part `xyz.com` ... rendering `account.ns-1.svc.cluster.local`
2. This query falls through to `kubernetes` plugin.
3. You can create an external service at `account.ns-1.svc.cluster.local` that points to the right ip.

**Comment by chrisohaver** [comment]
> Possible long-shot at a convoluted solution...

Perhaps needs to be slightly different - External name Services only allow for a destination name, not an IP. SO, here is the same idea, but with using manually created endpoints in kubernetes instead of externalName services...

1. Coredns receives `account.xyz.com.ns-1.svc.cluster.local`
2. Coredns `rewrite` plugin does a re-write to just remove `com`, leaving  `account.xyz.ns-1.svc.cluster.local`
3. This falls through to kubernetes plugin, it will be interpreted as  a query for the endpoint named `account`, in the `xyz` service.
4. You can create a service named `xyz` in ns-1, and create manual endpoints for the service named  `account`, with the IP address of your choosing.

**Comment by yybear** [comment]
@chrisohaver thanks, this should be a way, I will check it.

**Comment by grobie** [comment]
Should this be closed as duplicate of #1604?

**Comment by chrisohaver** [comment]
This issue morphed into a discussion of how to set up coredns to serve a specific test environments use case in k8s.  If that question is resolved, then we can close.

**Comment by yybear** [comment]
i have resolved this question by disable the health plugin.
