### ISSUE TITLE
plugin/reload: reload when DBFILE change

### ISSUE THREAD

**Issue by oilbeater** [coredns/coredns#1622]
Up to now, reload plugin only works when Corefile md5 changes.
It would be nice if plugin/reload and plugin/file can work together. When DBFILE on disk changed a reload is triggered to use the newest DBFILE.  Otherwise I have to echo a comment to the Corefile every time I changed the DBFILE, that's really boring

**Comment by johnbelamaric** [comment]
File already reloads, I thought? Just the zone, not the config. Also there is the auto plugin.

On Mar 21, 2018, at 7:22 AM, Oilbeater <notifications@github.com<mailto:notifications@github.com>> wrote:


Up to now, reload plugin only works when Corefile md5 changes.
It would be nice if plugin/reload and plugin/file can work together. When DBFILE on disk changed a reload is triggered to use the newest DBFILE. Otherwise I have to echo a comment to the Corefile every time I changed the DBFILE, that's really boring

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/reload: re..." ]
>Up to now, reload plugin only works when Corefile md5 changes.
>It would be nice if plugin/reload and plugin/file can work together. When DBFILE on disk changed a reload is triggered to use the newest DBFILE.  Otherwise I have to echo a comment to the Corefile every time I changed the DBFILE, that's really boring

Use the *auto* plugin that looks for those changes
