### ISSUE TITLE
can't reload Corefile in coredns

### ISSUE THREAD

**Issue by feresberbeche** [coredns/coredns#1706]
Hello,
I am using coredns with kubernetes and I when I use 
`kubectl -n kube-system edit configmap coredns`
and make changes to the Corefile, the changed are copied to inside the pods cause when I access them manually I find they are changed.
I use `kubectl exec -n kube-system coredns-*-* -- kill -SIGUSR1 1` with both pods of coredns
but when I use a dnstool pod to test if the new config works, well it dosen't.
Please tell me what to do. 

Here is my Corefile
  

>  Corefile: |
    .:53 {
        errors
        health
        rewrite continue {
        name regex ldap.feres.lab ldap.default.svc.cluster.local
        answer name ldap.default.svc.cluster.local ldap.feres.lab
        type ANY A
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream 8.8.8.8
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
    }

**Comment by fturib** [comment]
Hi, as of today, the plugins HEALTH and PROMETHEUS are incompatible with Restart of CoreDNS (both RELOAD abs signal SIGUSR1)
There is a fix in progress : #1688.

Right now, if you want to use RELOAD, you need to get rid of these 2 other plugins in your Corefile.

PROMETHEUS : it depends if you use it or not.
HEALTH : I am not sure how important it is for the management of this croedns Pod in Kubernetes : @chrisohaver - can you answer here ?

**Comment by feresberbeche** [comment]
@fturib Thanks for your answer, btw 
`kubeadm init --feature-gates CoreDNS=true
`
generates that Corefile by default, if those two plugins are not compatible please tell the kubeadm guys to rectify their default Corefile

**Comment by chrisohaver** [comment]
You’ll have to delete the pods to get them to reload the config, for now… the reload function has a bug relating to health and prometheus plugins that prevents it from reloading successfully.  There’s an active PR to fix the issue.

```kubectl -n kube-system delete pod coredns-xxxxxxxx-zzzz```

It's not generally feasible to deploy coredns by default without a liveness probe and metrics just to fix the reload issue, since you can still reload the config by restarting the pods.  IOW, for most people, it's better to reload configs by restarting pods for the occasional config file change, than to permanently live without liveness checks.

If config reload is more important for your deployment, you can remove the prometheus and health checking plugins, but you'll need to also remove the liveness probe from the coredns Deployment too, otherwise the coredns pods will constantly appear to be dead, and get restarted over and over again by kubernetes.

**Comment by miekg** [comment]
I think this is now fixes (in master) with #1709

**Comment by miekg** [comment]
Should be fixed or at least work a whole lot better with coredns 1.1.2
(although: #1722)

**Comment by miekg** [comment]
https://github.com/coredns/coredns/issues/1722 is fixed, but coredns needs to be compile with go 1.10 (default docker *is*)
