### ISSUE TITLE
Response Policy Zone

### ISSUE THREAD

**Issue by pawankkamboj** [coredns/coredns#1765]
Is coreDNS support for Response Policy Zone? we have external DNS for same zone and internal as well and want to run the coreDNS for k8s and replace internal DNS server with coreDNS file plugin. Tried it but it is not working for external, say not found.

**Comment by m4r10k** [comment]
Do you mean something like `Bind views` for example? If yes, I am pretty sure that this is not possible at the moment. We are using multiple CoreDNS instances configured for different etcd paths at the moment. But this would be nice anyway. Maybe that's a point for the reconsideration of the etcd plugin maybe... @miekg

**Comment by johnbelamaric** [comment]
No RPZ, not directly. For our commercial secure DNS service, which has much more flexible policies than RPZ, we built [Themis](https://github.com/infobloxopen/themis), a policy engine, and associated [CoreDNS policy plugin](https://github.com/infobloxopen/themis/tree/master/contrib/coredns/policy).

These are both open source but we don't really promote them because we haven't documented them very well and don't have the bandwidth for that.

You can implement RPZ with this, but right now policy decisions are run as a separate microservice which is more complex than you may want. We are looking to make this simpler at some point.

**Comment by m4r10k** [comment]
@johnbelamaric wow that's looking interesting though!

**Comment by pawankkamboj** [comment]
Thank you, will check both policy engine
