### ISSUE TITLE
plugin/proxy: the proxy plugin doesn't iterate upstreams according a policy

### ISSUE THREAD

**Issue by mparamonau** [coredns/coredns#1794]
The config example is as following:
.:53 {
    proxy . 9.8.8.8 8.8.8.8 {
        policy sequential
    }
    errors
    log
}

If the first upstream (9.8.8.8) is invalid, the proxy won't try next one (8.8.8.8).

**Comment by eugen-kleiner-mesh** [comment]
I am looking into it.

**Comment by ekleiner** [comment]
Looks like the issue is that health_check is not set. As result all proxies are treated as healthy. This seems like more correct config here:
.:5354 {
    proxy . 9.8.8.8 127.0.0.53 {
        policy sequential
        health_check /:80
    }
}
Is there any other way (supported by proxy plugin) to check if upstream is healthy except probing it via http? As this check seems strange because dns server is not http server.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/proxy:..." ]
>Looks like the issue is that health_check is not set. As result all proxies are treated as healthy. This seems like more correct config here:
>.:5354 {
>    proxy . 9.8.8.8 127.0.0.53 {
>        policy sequential
>        health_check /:80
>    }
>}
>Is there any other way (supported by proxy plugin) to check if upstream is healthy except probing it via http? As this check seems strange because dns server is not http server.

No, not in the proxy plugin. The forward plugin takes a diff. approach here, and 
uses dns healthchecks.

**Comment by miekg** [comment]
is anything happening here.

**Comment by miekg** [comment]
proxy will be deprecated.
