### ISSUE TITLE
Kubernetes : Remove service record when no endpoint is found

### ISSUE THREAD

**Issue by youkoulayley** [coredns/coredns#1809]
Hi, 

I have a simple question : is it possible to delete a service record when there is no endpoint behind it ?

Thanks in advance.

**Comment by chrisohaver** [comment]
No, there is no option to do this. Assuming you want CoreDNS to report `NXDOMAIN` for a service that has no endpoints.

**Comment by youkoulayley** [comment]
Any way this can become a feature in the future ?

**Comment by chrisohaver** [comment]
If its a common use case, we'd welcome a PR - but if it's a narrow use case then it might be better done as an external plugin that wraps kubernetes plugin rather than a modification to the existing kubernetes plugin.  An example external plugin that wraps the kubernetes plugin is  https://github.com/coredns/kubernetai.

Backing up a bit, what problem are you trying to solve by hiding services with no endpoints?

**Comment by youkoulayley** [comment]
With the PR #1813 merged, I think we can close this issue :)
