### ISSUE TITLE
hosts: example or RFC of /etc/hosts style file?

### ISSUE THREAD

**Issue by ahmetb** [coredns/coredns#1825]
I'm reading `hosts` plugin documentation at https://github.com/coredns/coredns/tree/master/plugin/hosts which says:

> `hosts` - enables serving zone data from a /etc/hosts style file.

Several things that are unclear to me:

- Is there a well defined standard fo `/etc/hosts`? RCF 952 looks similar but I'm unsure. Would be good to link if there's a respected spec.
- How are PTR records supported (as the plugin doc claims)? As far as I know the /etc/hosts files are just `<IP> <host>` lines. It would be good to explain this.

The doc would be much better if an example /etc/hosts-style file is provided.

**Comment by m4r10k** [comment]
As I see in in the testing code the test host file example looks like this: https://github.com/coredns/coredns/blob/b0fd575c658c22d082e1ac776a15ad8d188e76f7/plugin/hosts/hosts_test.go#L71-L74

The man page of the hosts file (`man 5 hosts`) does state that the host file is depending on RFC 952 but has moved forward.

PTR records are used for reverse lookups. Reverse lookups over PTR records are tested by the test case here for example: https://github.com/coredns/coredns/blob/b0fd575c658c22d082e1ac776a15ad8d188e76f7/plugin/hosts/hosts_test.go#L55-L58

I think the plugin is supporting PTR reverse lookups because it builds up a forward and a reverse lookup table given by the hosts file entries: https://github.com/coredns/coredns/blob/b0fd575c658c22d082e1ac776a15ad8d188e76f7/plugin/hosts/hostsfile.go#L116-L117

But yes, this should be better documented in the `hosts` plugin page. If you write a hosts file entry, you get the reverse PTR for free.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] hosts: exampl..." ]
>As I see in in the testing code the test host file example looks like this: https://github.com/coredns/coredns/blob/b0fd575c658c22d082e1ac776a15ad8d188e76f7/plugin/hosts/hosts_test.go#L71-L74
>
>The man page of the hosts file (`man 5 hosts`) does state that the host file is depending on RFC 952 but has moved forward.
>
>PTR records are used for reverse lookups. Reverse lookups over PTR records are tested by the test case here for example: https://github.com/coredns/coredns/blob/b0fd575c658c22d082e1ac776a15ad8d188e76f7/plugin/hosts/hosts_test.go#L55-L58
>
>I think the plugin is supporting PTR reverse lookups because it builds up a forward and a reverse lookup table given by the hosts file entries: https://github.com/coredns/coredns/blob/b0fd575c658c22d082e1ac776a15ad8d188e76f7/plugin/hosts/hostsfile.go#L116-L117
>
>But yes, this should be better documented in the `hosts` plugin page. If you write an hosts entry, you get the reverse PTR for free.

Can one of you create a PR with some changes to the README. The RFC is nice to 
reference as well. (I see that in a test we reference RFC 1123 - not sure how it 
applies to this plugin though)

**Comment by m4r10k** [comment]
> (I see that in a test we reference RFC 1123 - not sure how it
applies to this plugin though)

I had a quick look because I thought that I have heard about it in the past and it was about the host names. I had a discussion in a Docker issue that you can set UTF8 chars as host names (technically) but it should be prohibited as it is by the `hostname` binary. :smirk: 

```
docker run -ti  --rm  --hostname rofl🐳 alpine ash
/ # hostname
rofl🐳
/ # 
```

```
# hostname 🐳
hostname: the specified hostname is invalid
```

The section which is interesting and referring to RFC-952 is and I think it is checked by the `sethostname` function as referred by `man hostname`. 

```
   2.1  Host Names and Numbers

      The syntax of a legal Internet host name was specified in RFC-952
      [DNS:4].  One aspect of host name syntax is hereby changed: the
      restriction on the first character is relaxed to allow either a
      letter or a digit.  Host software MUST support this more liberal
      syntax.
```

**Comment by ahmetb** [comment]
rofl indeed.
