### ISSUE TITLE
CNAME record, dig and nslookup are ok, but can't ping

### ISSUE THREAD

**Issue by xluffy** [coredns/coredns#1840]
Hi, I check issue [417](https://github.com/coredns/coredns/issues/417) but still error.

My `Corefile`

```
amarincf.com:53 {
  log
  errors
  file db.amarincf.com
}

.:53 {
  proxy . 8.8.8.8
  log
  errors
  cache 10
}
```

File `db.amarincf.com`

```
$ORIGIN amarincf.com.
@  3600 IN  SOA sns.dns.icann.org. noc.dns.icann.org. (
    2017042745;
    10       ; refresh (2 hours)
    36       ; retry (1 hour)
    12       ; expire (2 weeks)
    36       ; minimum (1 hour)
    )

api 60 IN CNAME lb-coredns-prod-alb-11111111.ap-southeast-1.elb.amazonaws.com.
```

Output of `dig` and `nslookup`

```
> dig @127.0.0.1 api.amarincf.com

; <<>> DiG 9.9.7-P3 <<>> @127.0.0.1 api.amarincf.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14157
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;api.amarincf.com.              IN      A

;; ANSWER SECTION:
api.amarincf.com.       60      IN      CNAME   lb-coredns-prod-alb-11111111.ap-southeast-1.elb.amazonaws.com.

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu May 31 11:14:20 +07 2018
;; MSG SIZE  rcvd: 117
```

```
> nslookup api.amarincf.com 127.0.0.1
Server:         127.0.0.1
Address:        127.0.0.1#53

api.amarincf.com        canonical name = lb-coredns-prod-alb-11111111.ap-southeast-1.elb.amazonaws.com.
```

Output of `ping`

```
ping api.amarincf.com
ping: cannot resolve api.amarincf.com: Unknown host
```
My CoreDNS version:

```
./coredns -version
CoreDNS-1.1.3
darwin/amd64, go1.10.1, b0fd575c
```

Why `ping` can't resolve? How resolve with CNAME record?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] CNAME record, dig..." ]
>Hi, I check issue [417](https://github.com/coredns/coredns/issues/417) but still error.
>
>My `Corefile`
>
>```
>amarincf.com:53 {
>  log
>  errors
>  file db.amarincf.com
>}
>
>.:53 {
>  proxy . 8.8.8.8
>  log
>  errors
>  cache 10
>}
>```

You need to tell `file` to resolve external queries; you can do this with 
`upstream`:

~~~
amarincf.com:53 {
  log
  errors
  file db.amarincf.com {
        upstream
  }
}
~~~

/Miek

--
Miek Gieben

**Comment by xluffy** [comment]
Hi @miekg, I updated my config to

```
amarincf.com:53 {
  log
  errors
  file db.amarincf.com {
    upstream 127.0.0.1:53
  }
}

.:53 {
  proxy . 8.8.8.8
  log
  errors
  cache 10
}
```

So still can't resolve domain.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CNAME record,..." ]
>Hi @miekg, I updated my config to
>
>```
>amarincf.com:53 {
>  log
>  errors
>  file db.amarincf.com {
>    upstream 127.0.0.1:53
>  }
>}
>
>.:53 {
>  proxy . 8.8.8.8
>  log
>  errors
>  cache 10
>}
>```
>
>So still can't resolve domain.

Does it work with just:

amarincf.com:53 {
  log
  errors
  file db.amarincf.com {
    upstream
  }
}

.:53 {
  proxy . 8.8.8.8
  log
  errors
  cache 10
}

**Comment by chrisohaver** [comment]
> Why ping can't resolve? 

The reason is that there is no `A` record in the result, so there is no IP address to contact.  When you do name lookups with `dig` or `nslookup`, you are just querying the DNS server, and not depending on getting an `A` record back.

For this to work, `lb-coredns-prod-alb-11111111.ap-southeast-1.elb.amazonaws.com.` has to receive an `A` record from the upstream server (`8.8.8.8`)... but when I checked, it does not have one.

Does `lb-coredns-prod-alb-11111111.ap-southeast-1.elb.amazonaws.com.` resolve for you when you query 8.8.8.8 ?

For example...
~~~
CTOs-MacBook-Pro:~ cohaver$ dig @8.8.8.8 lb-coredns-prod-alb-11111111.ap-southeast-1.elb.amazonaws.com.

; <<>> DiG 9.10.6 <<>> @8.8.8.8 lb-coredns-prod-alb-11111111.ap-southeast-1.elb.amazonaws.com.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 58058
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;lb-coredns-prod-alb-11111111.ap-southeast-1.elb.amazonaws.com. IN A

;; AUTHORITY SECTION:
ap-southeast-1.elb.amazonaws.com. 59 IN	SOA	ns-1125.awsdns-12.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 60

;; Query time: 35 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu May 31 08:56:06 EDT 2018
;; MSG SIZE  rcvd: 172
~~~

**Comment by xluffy** [comment]
Hi @chrisohaver, Thank for your explain. `lb-coredns-prod-alb-11111111` just an example. I update my testing info.

My Corefile

```
amarincf.com:53 {
  log
  errors
  file db.amarincf.com {
    upstream
  }
}

.:53 {
  proxy . 8.8.8.8
  log
  errors
  cache 10
}
```

File `db.amarincf.com`
```
$ORIGIN amarincf.com.
@  3600 IN  SOA sns.dns.icann.org. noc.dns.icann.org. (
    2017042745;
    10       ; refresh (2 hours)
    36       ; retry (1 hour)
    12       ; expire (2 weeks)
    36       ; minimum (1 hour)
    )

api 300 IN CNAME lb-coredns-prod-alb-486157660.ap-southeast-1.elb.amazonaws.com.
```
And my real ALB

```
dig @8.8.8.8 lb-coredns-prod-alb-486157660.ap-southeast-1.elb.amazonaws.com

; <<>> DiG 9.9.7-P3 <<>> @8.8.8.8 lb-coredns-prod-alb-486157660.ap-southeast-1.elb.amazonaws.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24237
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;lb-coredns-prod-alb-486157660.ap-southeast-1.elb.amazonaws.com.        IN A

;; ANSWER SECTION:
lb-coredns-prod-alb-486157660.ap-southeast-1.elb.amazonaws.com. 59 IN A 52.77.20.226
lb-coredns-prod-alb-486157660.ap-southeast-1.elb.amazonaws.com. 59 IN A 52.76.10.82

;; Query time: 52 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu May 31 20:59:21 +07 2018
;; MSG SIZE  rcvd: 123
```
So same issue, I still can't resolve `api.amarincf.com`. Any ideas?

**Comment by chrisohaver** [comment]
I tested this locally and it works for me...

Did you restart CoreDNS after applying the changes to your Corefile?

**Comment by xluffy** [comment]
Hi @miekg, @chrisohaver, I tried to test. Now, It's work. Thank a lot for your support

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CNAME record,..." ]
>Hi @miekg, @chrisohaver, I tried to test. Now, It's work. Thank a lot for your support

Are there bits of docs that can be improved here?
