### ISSUE TITLE
Standardize Response Duration

### ISSUE THREAD

**Issue by makinje16** [coredns/coredns#1841]
Sometimes response duration comes in nano seconds and sometimes milliseconds. Are we able to pick a standard for the response duration in order to be more clear and needing to have conversions for them.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Standardize Respo..." ]
>Sometimes response duration comes in nano seconds and sometimes milliseconds. Are we able to pick a standard for the response duration in order to be more clear and needing to have conversions for them.

All in-tree metrics export seconds:

% grep -ir observe
forward/connect.go:	RequestDuration.WithLabelValues(p.addr).Observe(time.Since(start).Seconds())
metrics/vars/report.go:	RequestDuration.WithLabelValues(server, zone).Observe(time.Since(start).Seconds())
metrics/vars/report.go:	ResponseSize.WithLabelValues(server, zone, net).Observe(float64(size))
metrics/vars/report.go:	RequestSize.WithLabelValues(server, zone, net).Observe(float64(req.Len()))
proxy/proxy.go:		RequestDuration.WithLabelValues(metrics.WithServer(ctx), state.Proto(), upstream.Exchanger().Protocol(), familyToString(state.Family()), host.Name).Observe(time.Since(start).Seconds())
health/overloaded.go:	HealthDuration.Observe(timeout.Seconds())
health/overloaded.go:	HealthDuration.Observe(time.Since(start).Seconds())



/Miek

--
Miek Gieben

**Comment by makinje16** [comment]
Sorry @miekg I should be more specific. In the logs plugin, when unparsed, the response duration field can be in ms or nanoseconds. Are we able to standardize that part of the log plugin?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Standardize R..." ]
>Sorry @miekg I should be more specific. In the logs plugin, when unparsed, the response duration field can be in ms or nanoseconds. Are we able to standardize that part of the log plugin?

ah yeah. I can see that being annoying, but why aren't you using metrics for 
that?

Should probably make that seconds as well, just for overall consistency; PR 
welcome
