### ISSUE TITLE
plugin/metadata: enhancements

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1905]
Couple of things that can be fixed/improved

* OWNERS file needs to be added
* pkg/variables is a thin wrapper around request.Request, I don't really see a need for it. It also lacks pacckage level documentation so I can tell why its there. It converts everything to []byte which seems something the rewrite plugin should do.
* I think a split is in order to have StringVariables and IntVariables and maybe more. This means the `interface{}` stuff can go *and* the caller knows what to expect when iterating over the MetaDataVarNames(), which would then also be split into NamesString() NamesInt() etc.
* the variables itself need to be exported
* a whole bunch of cleanups, of which I'm already preparing a PR.

**Comment by miekg** [comment]
Seems request/request.go should add LocalAddr and LocalPort

**Comment by fturib** [comment]
We need to ensure the interface Provider of the package metadata will no change (most likely) over time. Because it would imply to rework all the Plugin that implement it and raise backward incompatibility.
So if we want to manage types, maybe we can add a qualify the variable with a type value and add a "type" parameter to the functions ? (in order to handle future added types w/o changing the interface)

**Comment by miekg** [comment]
closed via fcc32a79 and 99800a68
