### ISSUE TITLE
FOSSA license scan is failing still

### ISSUE THREAD

**Issue by ghost** [coredns/coredns#1956]
In #867 @yongtang reported a license scan was failing. The issue was closed then with an unclear resolution. Today I see the license scan is failing.

Was the licensing issue (assuming there ever was one) addressed in any prior release of this repository?

**Comment by ghost** [comment]
![screenshot_20180710_104233](https://user-images.githubusercontent.com/440298/42486704-faa59a42-83ec-11e8-851f-90414e6ffed7.jpg)

**Comment by chrisohaver** [comment]
All of the "failures" are for licenses that state that we must disclose our source code.  Per my understanding, since this is an open source project, all source code is disclosed.

I'll look to see if i can make FOSSA understand that this is an open source project, so it doesn't raise these types of license issues in the future.

**Comment by chrisohaver** [comment]
I cant change settings in FOSSA because i'm not a maintainer of that account.
Also, I marked the open issues as resolved, but the badge still shows up as failed.
Dont know if this takes time to update, or if it needs to be approved, or what.

**Comment by ghost** [comment]
thanks @chrisohaver. maybe pull the badge?
