### ISSUE TITLE
curl command to add SRV record to coredns+etcd

### ISSUE THREAD

**Issue by wiseflat** [coredns/coredns#1976]
Hi guys,

[documentation](https://github.com/coredns/coredns/tree/master/plugin/etcd)

I am using coredns+etcd and I would like to add SRV record for service discovery.
What should be the curl command to add this kind of record ?

Cheers

**Comment by jiachengxu** [comment]
It's better to use `etcdctl` instead of `curl`, and current documentation on master branch is not valid for the etcd plugin which based on etcdv3, so you can check this PR: https://github.com/coredns/coredns/pull/1974, and find examples about how to use `etcdctl` to write reconds into the etcd instance.

**Comment by wiseflat** [comment]
Hi @JiachengXu ,

I realized I am using an old version of coredns. I will upgrade to coredns 1.2.0 asap...

Is it possible to make a documentation improvement ? 
Could you add an example of how to add SRV records with etcdctl please ?

**Comment by jiachengxu** [comment]
Sure, will do that.

**Comment by miekg** [comment]
closed via #1980
