### ISSUE TITLE
Docker image appears to not include a [working] Prometheus Plugin

### ISSUE THREAD

**Issue by DazWilkin** [coredns/coredns#2051]
Apologies if I've missed the documentation that explains this:

```
example.org {
    file example.org
    prometheus
    errors
    log
}
```
And
```
./coredns -conf Corefile -dns.port 1053
```
And I can then `GET` the metrics endpoint on `localhost:9153/metrics`

But:
```
docker run \
--interactive \
--tty \
--publish=1053:1053/tcp \
--publish=1053:1053/udp \
--publish=9153:9153/tcp \
--volume=$PWD:/tmp \
coredns/coredns \
  -conf /tmp/Corefile \
  -dns.port 1053
```
reports
```
curl localhost:9153/metrics
curl: (7) Failed to connect to localhost port 9153: Connection refused
```

I tried explicitly referencing e.g. localhost:9151 in the Corefile but no deal.

**Comment by DazWilkin** [comment]
Aha!
```
example.org {
    file example.org
    prometheus        :9153
    errors
    log
}
```
Unsure whether this is a consequence of the containerized CoreDNS but...

The explicit port reference enabled metrics exporting with **both** the binary (`./coredns`) and the container. Absent the port reference, the container doesn't export metrics.

**Comment by chrisohaver** [comment]
> Unsure whether this is a consequence of the containerized CoreDNS

Yes, I believe this is because the `prometheus` plugin defaults to bind to localhost; localhost not being reachable from outside the container's network namespace.
Specifying `:9153`, binds it to _all_ interfaces available to the container on 9153.

Note: we had to do the same for the kubernetes coredns deployment [template](https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed#L57).

**Comment by DazWilkin** [comment]
Make sense. Thanks!
