### ISSUE TITLE
Configurable reload time of zone files

### ISSUE THREAD

**Issue by marqc** [coredns/coredns#2108]
Zone file reload is currently "hardcoded" to 1 minute https://github.com/coredns/coredns/blob/master/plugin/file/reload.go#L9
In some cases (like more complex provisioning) this is too long time. This can be also seen in tests when reload time is "hacked" to 15 seconds.
Alternative is sending SIGUSR1 signal, but this seems to reload all modules, drop caches and is quite heavy.

Best way of improving this would be to watch on inotify on config files and apply changes as soon as they appear i n zone file.
Easier way, that can be implemented faster, is to expose reload time in plugin setup.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Configurable relo..." ]
>Zone file reload is currently "hardcoded" to 1 minute https://github.com/coredns/coredns/blob/master/plugin/file/reload.go#L9
>In some cases (like more complex provisioning) this is too long time. This can be also seen in tests when reload time is "hacked" to 15 seconds.
>Alternative is sending SIGUSR1 signal, but this seems to reload all modules, drop caches and is quite heavy.
>
>Best way of improving this would be to watch on inotify on config files and apply changes as soon as they appear i n zone file.

What had inotify, but didnt work at the time because the file could be shared by 
a lot of zone, so we went for the simpler, just check every x seconds.

>Easier way, that can be implemented faster, is to expose reload time in plugin setup.

In retrospect `no_reload` should be named: `reload [DURATION]` where 0 would 
disable the behavior. I wouldn't mind PR that does this though (and leave 
no_reload for backwards compat for some time).

There is one thing the current code *does not do* and that is waiting for a 
reload to finish before starting a new one. I.e we just hope we're done.
 
/Miek

--
Miek Gieben
