### ISSUE TITLE
startup blocked if kubernetes API is unavailable

### ISSUE THREAD

**Issue by knisbet** [coredns/coredns#2116]
#### Version
CoreDNS-1.2.2
linux/amd64, go1.11, eb51e8b

#### Description
I'm experimenting with a bit of a weird setup, where I'm attempting to use CoreDNS to serve some local records, proxy to an upstream provider, and act as a replica for our kubernetes service discovery, running outside of kubernetes. The problem I'm experiencing, is the kubernetes API might not be available when CoreDNS starts, and if it's not available, I'm experiencing a hang in the CoreDNS startup where the process never binds and isn't able to serve non-kubernetes records.

I've isolated it to this code:
https://github.com/coredns/coredns/blob/master/plugin/kubernetes/setup.go#L71-L75

Which appears to have been introduced to prevent a race / unit tests:
PR: #1155 
Issue: #1006

#### Desired Behaiour
I'm not sure if this is intended behaviour or not. 

My expectation would be, that the kubernetes API being unavailable/unreachable would not block startup of a server under partial outage, only return serv fail on the zones the kubernetes plugin is responsible for (depending on fall-through).

I haven't investigated the tests, to see what implications this approach might have from a unit test perspective.

Alternatively, as a simpler workaround, I was considering the option to simply time limit the start-up routine would be blocked waiting for the kubernetes resources to sync. I was thinking something like 10-15 seconds would work.

#### Closing
I'm willing to contribute a fix for this issue with the desired approach.

Thank You

**Comment by yongtang** [comment]
@knisbet I think that is a legitimate scenario.

A timeout is one option. Another option is to always retry k8s api in background mode until success, and return serv fail on k8s zones before success. The second option is very useful in a distributed setup where you don't know when one component on another another machine might be ready (And you don't want to put a sequence of dependencies).

Of course we could have an option flag in configuration so that user could specify if they want a hard fail or always retry in background when k8s api is not ready.

A PR is very much appreciated!
