### ISSUE TITLE
Kubernetes - resolution per POD hostname

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#2139]
Based on this issue/requirement : https://github.com/kubernetes/dns/issues/266

> What I would expect is, that every pod hostname is available in DNS similar to the ip-based hostame under podname.namespace.pod.cluster.local so I can just simply add namespace.pod.cluster.localto the search path and will be covered.

NOTE: This out of current specs of DNS for Kubernetes.

**Comment by chrisohaver** [comment]
> NOTE: This out of current specs of DNS for Kubernetes.

Just to be clear  - This function is a not requirement of the DNS Specs.  But implementing this option would not _violate_ the specs in any way.

**Comment by chrisohaver** [comment]
> so I can just simply add `namespace.pod.cluster.local` to the search path and will be covered.

This could be challenging to do because `namespace` is dynamic.  Not sure how easy it is (of if its possible) to customize the search list with custom entries - especially dynamic ones. (side note, changes the search list like this would be incompatible with the `autopath` plugin)

I expect that the existing `cluster.local` search domain was intended to address the possible need for queries to pods ... so a query like `mypod.mynamespace.pod` would resolve.

**Comment by miekg** [comment]
Fix the spec first, then we can implement it.
