### ISSUE TITLE
Docker plugin (similar to Kubernetes plugin)

### ISSUE THREAD

**Issue by r6m** [coredns/coredns#2155]
Hi
first of all, thanks for this nice repo.
I was hoping there was a way to have docker support, I mean to be able to set a domain/sub on a docker container using just the container name. something similar to redbird dns proxy in NodeJS.

Another nice feature is a http or grpc API endpoint for actions.

there might be a plugin for API endpoint, but i couldn't find it.

**Comment by miekg** [comment]
what do you mean/want?

**Comment by hazelweakly** [comment]
@miekg, I believe they were wanting support for the docker daemon as a backend, similar to how kubernetes can function as a backend. Some usecases that would be convenient for that are:

1. (Their usecase, as best as I can interpret): Automatic resolution of container names (eg typing `web` into a browser would point you to the web container, `docker_web_1` if you were running the container in docker compose, etc).
2. (A usecase I'm investigating for work): Being able to have traffic between containers redirect to the containerized reverse proxy rather than having to go all the way out to the firewall and back in.

   This is different than most existing solutions because it would still require ssl termination by the proxy and would be entirely transparent to the containers rather than requiring usage of a `.cluster.internal` schema or some other differentiating factor.

Is this something that's appropriate for the CoreDNS project?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] support docke..." ]
>@miekg, I believe they were wanting support for the docker daemon as a backend, similar to how kubernetes can function as a backend. Some usecases that would be convenient for that are:
>
>1. (Their usecase, as best as I can interpret): Automatic resolution of container names (eg typing `web` into a browser would point you to the web container, `docker_web_1` if you were running the container in docker compose, etc).
>2. (A usecase I'm investigating for work): Being able to have traffic between containers redirect to the containerized reverse proxy rather than having to go all the way out to the firewall and back in.
>
>   This is different than most existing solutions because it would still require ssl termination by the proxy and would be entirely transparent to the containers rather than requiring usage of a `.cluster.internal` schema or some other differentiating factor.
>
>Is this something that's appropriate for the CoreDNS project?

Thanks for the explanation. Yes, this would be accepted as a plugin.
