### ISSUE TITLE
plugin/kubernetes: disable watch

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2156]
We should add a watch directive in kubernetes, saying you want to get watch updates. By default it is disabled and only the modified timestamp is increased so axfr works.

**Comment by chrisohaver** [comment]
@miekg, Why do you think this is no longer necessary?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>Why do you think this is no longer necessary?

I'm not going to work on it anymore

**Comment by chrisohaver** [comment]
> I'm not going to work on it anymore

But someone else may ... right?

**Comment by johnbelamaric** [comment]
Not sure there is any reason to - didn't you put in a small tweak to make it basically a no-op when no watches are defined?

It was the endpoints check I thought that was causing possible memory issues, but we need that for AXFR not just watch.

**Comment by chrisohaver** [comment]
> didn't you put in a small tweak to make it basically a no-op when no watches are defined?

No, because of the AXFR timestamp issue.

> Not sure there is any reason to.

I was thinking someone might want to run a grpc server, and _not_ have watch enabled.  But if thats not a problem/concern then there is no need for it.

Anyways, Thanks.  I was just looking for a reason.  Perhaps I wasn't asking the question correctly.  Not trying to be a pain in the ass, but I think its a good idea to explain why we are closing tickets, so later we understand why we closed them.
