### ISSUE TITLE
governance proposal

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2228]
We've send lots of replies on maintainership and we haven't reached a conclusion yet (and I also need to read the backlog of emails).

Now we had a chat with the CNFC (our monthly meeting) and a BDFL is not model they exclude. In fact they haven't really got an opinion on this (i.e. what a project should adapt).

In this issue I want to propose two forms of governance that can work for me. This excludes any discussion on voting etc.

Proposal:

1. "BDFL", but only for 1 year and then we revisit this model (BDF1Y). If think in its current state
   this model can work for CoreDNS. It also pushes a lot of responsibility into one person and it
   probably also takes up quite a lot of time.

2. "Senior maintainers" (Envoy employs this model). In this case a couple of people have the final say
   in technical disputes. I like this model quite a lot as we spread the load and we have some kind
   of leadership that (hopefully) will make the right decisions. Downside is that we need write down
   how one becomes senior (or steps down). Also with respect to succession this model makes sense as
   new persons can learn from the current senior maintainers.

**Comment by miekg** [comment]
/cc @caniszczyk @fturib @yongtang 
(and slew of other that I'm pretty forgetting - don't want to spam every ones inbox yet again)

**Comment by chrisohaver** [comment]
> In this case a couple of people have the final say in technical disputes...

And when they disagree ... weighted corp-gated 2/3 majority voting! 😉

FWIW, of these two, I prefer BDF1Y.

**Comment by fturib** [comment]
Personally, I prefer the option 2. with "Senior maintainers".
But if majority goes to BDF1Y I will agree with it. 
In both case, though you will need at some point a vote mechanism either between the "Senior Maintainers", either at end of the term of BDF1Y.

**Comment by yongtang** [comment]
I am in favor of `BDF1Y`, and I am also in favor of re-open the discussions about the governance in the future, before the expiration of `BDF1Y`.

Before finalize what the governance will be after `1Y`, I would like to have an open discussion for several things.

First of all, any format of voting for open source projects, is always a `privilege to vote`, not `right to vote` we commonly referring to in a well-functioning democracy.

In other words, equal voting does not equal to democracy in open source.

A `privileged voting` is a fine form, as long as we could clarify:
- Who is able to vote (what each vote represents)
- What kind of problems the voting format tries to solve
- What is the mechanism to adapt to progression of the coredns project

Just like CNCF has both Governing Board and TOC for non-technical and technical aspect of the organization, I think the technical and non-technical discussions about coredns could also be separated.

For technical side, it is quite straightforward. Decisions should be made by individuals based on technical merit (`privilege`). The scope is limited to resolve technical conflict (it is hard to believe this could not be resolved in harmony before a vote, though). Given the contributions from Miek at the moment, it makes sense to give him some extra weight. Equal voting among senior maintainers is fine as well. For senior maintainers, we may want to make sure new senior maintainers (for progression of the coredns project) could be added in the future, so scenarios like the following will not happen:

“I am the selected and privileged few. Since I am already in, I want to close the door so that no one else could get in.”

For non-technical side, we may have to answer the question of `what each vote represents`. In other words, who are the stakeholders for non-technical side of the coredns, and what are the non-technical side of the coredns after all?

In CNCF, the goal is to foster a community that benefits its members (for things like marketing, etc.), as well as other constituencies including the TOC, project maintainers, end users, developers contributing to projects, and others.

In coredns, who should be considered as stakeholders of the project and who’s voice should be listened (represented)?

Since coredns is an open source project with apache license, there is not a lot of restrictions. I don’t see much of conflicts of interest. For example, I don’t see a problem if any individual or any company use or sell the coredns software for a profit (at least I am not in the position to care).

But, as coredns project is part of CNCF, there are some marketing activity. And default plugins could help one vendor vs another. So the questions:
- Should coredns have a mechanism to make sure no vendors could use coredns exclusively to gain competitive advantage (by enabling some default plugins and preventing other default plugins)?
- Should coredns have a mechanism to make sure any vendors could join and help/contribute coredns, even if there are already some vendors helping/contributing coredns?

I believe the above question also aligns with the policy of cncf (correct me if I am wrong).

In summary, I think `BDF1Y` helps avoid many issues in the short term. In the long term, though, an open discussion about some questions is needed I believe.

**Comment by yongtang** [comment]
I do want to give @miekg credits for some of the clauses he proposed:
- Addition of new maintainers is reasonable enough. It helps in that maintainers are not locked into a small group forever.
- Addition of subproject is also reasonable enough. It helps avoid conflicts in case multiple competing subprojects exists.
- No forceful removal of maintainer helps avoid the alienation of independent contributors.

Overall, his proposal has addressed most of the potential conflicts in the future, without the need for intervention. His proposal also helps creating a friendly environment for independent contributors. This is one of the reasons I put more trust on him.

The remaining unresolved issues, as far as I could see, is mostly the CNCF related marketing activity and vendor involvement in coredns.

To make it clear, I am not against vendor associated activity in coredns. They are part of the community and their interests should be considered.

However, I only would like to see 1) A mechanism to make sure vendor involvements in coredns is non-exclusive and fair to all existing and future vendors. 2) A mechanism to make sure independent contributors are not totally forgotten.

If the above vendor-related concerns could be addressed without intervention, that would be ideal. That could help maintainers and the project lead of coredns to spend more time on the technical side of the coredns itself.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] governance pr..." ]
>However, I only would like to see 1) A mechanism to make sure vendor involvements in coredns is non-exclusive and fair to all existing and future vendors. 2) A mechanism to make sure independent contributors are not totally forgotten.
>
>If the above vendor-related concerns could be addressed without intervention, that would be ideal. That could help maintainers and the project lead of coredns to spend more time on the technical side of the coredns itself.

I don't think we should see vendors that differently. It creates a onus on the 
current maintainer to think about this. From what's currently happening inside 
the community there happen to be contributors that belong to the same company; I 
think that fine.

(From a technical standpoint I would like to avoid seeing code being merged 
where *only* contributors from the same company looked at the code, but this is 
borderline governance)

**Comment by yongtang** [comment]
@miekg Will the concept similar to third-party maintainer like https://github.com/coredns/coredns/pull/2220#issuecomment-434110271 work?

Essentially for things like adding plugin or adding subproject, we could ask the supporting maintainer not to be affiliated with the author of the proposal. I think that largely addresses many potential issues.

**Comment by miekg** [comment]
yes, that can work
