### ISSUE TITLE
plugin/rewrite: rewrite answer for regexes based on question

### ISSUE THREAD

**Issue by SethCurry** [coredns/coredns#2389]
CoreDNS Version: 1.2.6

I have a use case to rewrite *.publicdomain.com such that it returns results for fqdn.publicdomain.com.  I tried using the rewrite plugin with this configuration:

```
rewrite name regex .*\.publicdomain.com fqdn.publicdomain.com
```

However that only rewrites the question, and not the answer, so the response is A records for fqdn.publicdomain.com.  Some clients (like curl) are okay with that and will use the response, but other clients (like Python2) seem to actually check whether the returned name matches the requested name.  Python2 reports that the domain could not be resolved with this rule in effect.

I also tried to use the file plugin, but I couldn't find a way to allow only fqdn.publicdomain.com to pass through to upstream DNS servers.

I don't know what the best solution would be, but one though I had was to propogate the matches from the `name` regex to `answer` regex if both are wrapped in a single regex statement like:

```
rewrite stop {
        name regex (.*)\.publicdomain\.com fqdn\.publicdomain\.com
        answer name fqdn\.publicdomain\.com {name-1}\.publicdomain\.com
}
```

**Comment by johnbelamaric** [comment]
Yes, that's the basic idea. But you should anchor with ^ and $ too, or you'll have issues. And the syntax for the group is just {1}.  For example:

```
           name regex (.*)\.my\.domain\.$ {1}.default.svc.cluster.local.
           answer name (.*)\.default\.svc\.cluster\.local\.$ {1}.my.domain.
```

**Comment by SethCurry** [comment]
Oh thanks for the tip there, but I think my issue is slightly different than that.  I need to squash many domains (*.my.domain) to a single domain (fqdn.my.domain) for the name regex, and then on the answer regex I need to restore the portion of the name that I rewrote.

So if someone requests `nada.my.domain` I want to forward a DNS request for `fqdn.my.domain` from CoreDNS, and then have CoreDNS take the response from the upstream server and rewrite it so that it keeps the IPs from the A records for `fqdn.my.domain`, but changes the DNS name in the response to `nada.my.domain` so clients don't freak out that they requested `nada.my.domain` and CoreDNS is returning records for `fqdn.my.domain`.

**Comment by johnbelamaric** [comment]
Ah, so you want to use one of the matches from the name regex in the answer. I get it. @greenpau thoughts?

It should be possible to keep the match records around, so it's just how we go about representing them in the answer expression in a way that doesn't conflict with standard regex.

**Comment by greenpau** [comment]
@SethCurry , @johnbelamaric 's [comment](https://github.com/coredns/coredns/issues/2389#issuecomment-446410559) was on point.

> and then on the answer regex I need to restore the portion of the name that I rewrote.

I understand the use case. At the moment it is unsupported, but not impossible to accomplish! 😄 

@johnbelamaric, what is necessary here is creating a key-value map attached to the rewrite. The key-value map will get populated on the receipt of a request. Then, on the answer rewrite, [here](https://github.com/coredns/coredns/blob/master/plugin/rewrite/reverter.go#L51-L63), we use that key-value map. The key-value map could be inserted in [here](https://github.com/greenpau/coredns/blob/master/plugin/rewrite/name.go#L41-L46).

I think this use case is very interesting! 👍 @SethCurry thank you for raising the issue.

**Comment by greenpau** [comment]
@SethCurry , with the above said, please help with test cases. Please provide the input and output records, e.g.:

* `foo.bar` becomes `bar.foo` based on the following logic. logic follows ...

I think 5-10 of the patterns would be enough for a start.

Next, we will try figuring out how to create a syntax that would match the intent here. 
For example, `(.*:name)\.my\.domain\.$` in the below example would really mean `(.*)\.my\.domain\.$`, but the contents of the first match would become `name` key for the use in the rewrite:

```
name regex (.*:name)\.my\.domain\.$ {1}.default.svc.cluster.local.
```

@SethCurry , @johnbelamaric, does it make sense?

**Comment by ckcd** [comment]
Great! I have this use case too.

**Comment by ckcd** [comment]
@greenpau , thanks for your careful analyze for code !!!

I have a little bit different opinion for:

> `name regex (.*:name)\.my\.domain\.$ {1}.default.svc.cluster.local.`


1. in this case the domain of request after modification by coredns is fixed(for example, `fqdn.publicdomain.com.`) no matter what the origin request is. so maybe there should not have `{1}` in the last part.
2. we should use `answer name` to indicate that we truly need a rebuild for reply.

So in my rough opinion, the regex maybe looks like:

```
name regex (.*:name1)\.my\.domain\.$ fqdn.publicdomain.com.
answer name fqdn\.publicdomain\.com. (:name1)\.my\.domain\.
```
which means:

1. for request, trans `abc.my.domain` to fqdn.publicdomain.com,(name1 is abc), and coredns will record the key-value (maybe `abc.my.domain --> fqdn.publicdomain.com` or opposite);
2. for reply, check weather defines the `answer name`, if yes, read the key-value and rebuild the name, and if no, just pass it to next plugin.

Or maybe i have some misunderstanding of this case, please correct me!

Thanks a lot !!!

**Comment by greenpau** [comment]
> So in my rough opinion, the regex maybe looks like:

@MissEnXi , I like the example 👍 one thing to consider is that "name" and "answer" directive are being independent from each other for a reason. For example, the omission of some parts of a request, e.g. `(.*)\.my\.(.*)\.domain\.$ {1}.my.domain.com.`.

Everyone has a different use case. I like the ability to have a key-value hash attached to a request.

> Or maybe i have some misunderstanding of this case, please correct me!

Maybe, idk. It will be clear when  @SethCurry provides his test cases.

**Comment by krzysztof-bronk** [comment]
I'd love to see this implemented, we have a use case for that too :)

I assume the solution would be to have the key-value map available in the answer clause, in order to reconstruct the original question name?

Can't we just have access to the entire question name as it came?

Something like this:
`rewrite {
      name regex (.*)\.example\.com\.?$ {1}.anotherexample.com
      answer name .* {{ original_question_name }}
}`

So the behavior is like with the Exact type, the answer is auto-rewritten, although explicitly.

**Comment by greenpau** [comment]
> @SethCurry provides his test cases.

@SethCurry , did you find a workaround?

I will work on this feature. It will be interesting to get your test cases.

**Comment by weiqiang333** [comment]
Is this use case still implemented?
This problem continues to haunt me.

**Comment by greenpau** [comment]
> Is this use case still implemented?

@weiqiang333, I am waiting on test cases. Do you want to provide them?

**Comment by weiqiang333** [comment]
> > Is this use case still implemented?
> 
> @weiqiang333, I am waiting on test cases. Do you want to provide them?

@greenpau 
This is my real case. Is this the case you want?
```
    .:53 {
        errors
        health
        rewrite name regex k8s-.*-.*\.growingio\.com ci-k8s-public-1493930063.cn-north-1.elb.amazonaws.com.cn
        forward . /etc/resolv.conf
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
    }
```

**Comment by 633kh4ck** [comment]
Real use case: CoreDNS used as an internal DNS to provide remote VPN clients with ability to discover internal infrastructure services with memorable domains.

Ex. config (abstract):
```
rewrite stop {
	name regex (.*)\.staging\.domain\.com internal.lb.ra0
	answer name internal.lb.ra0 staging.domain.com
}
```

Ex. query (from console):
```
λ dig some.staging.domain.com.

; <<>> DiG <<>> some.staging.domain.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8259
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 27787d3d2e23340d (echoed)
;; QUESTION SECTION:
;some.staging.domain.com. IN  A

;; ANSWER SECTION:
staging.domain.com. 1    IN      A       XX.XX.XX.XX

;; Query time: 30 msec
;; SERVER: XX.XX.XX.XX#53(XX.XX.XX.XX)
;; MSG SIZE  rcvd: 115
```

**But**, many corporate security products don't trust DNS responses if answer section isn't consistent with question section, so it's _trouble_ for us (for our case). I agree with the proposal by @krzysztof-bronk:

> the solution would be to have the key-value map available in the answer clause, in order to reconstruct the original question name

I look forward to this feature.

**Comment by 633kh4ck** [comment]
> I am waiting on test cases. Do you want to provide them?

@greenpau, here is one sample (based on my prev message):
```
rewrite stop {
	name regex (.*:service)\.staging\.domain\.com internal.lb
	answer name internal\.lb (:service)\.staging\.domain\.com
}
```

Such part of config can produce following transformations:

- req. `any.staging.domain.com` --[map `service` to `any` in kv store]--> internal.lb
- res. internal.lb --[load `any` by key `service` from kv store]--> any.staging.domain.com

**Comment by euank** [comment]
I ran into this issue too, and had a go at my own solution for it.

It seems like all use-cases discussed here don't actually need the answer rewrite to reference the original 'name' regex, bur rather just want the answer to match the original question, and a regex referencing the original captures is just a means to that goal.

It seemed easier to implement that behavior than dealing with shuffling around regex state, so I implemented being able to just do `answer question` (rewriting the answer section to whatever the original question happened to be) in #3273.

**Comment by shilx3** [comment]
I have this use case too. My case is `rewrite name regex (.+).example.com foo.com` 
Question is  `abc.example.com `;  
Answer is ` foo.com   IN    A    1.1.1.1`; 
This case likes wildcard, and I don't want use file plugin. Because Ip in foo.com is dynamic. Some client cannot accept the resqonse with answer mismatching question. I really hope a solution that can resolve it. 
Thanks a lot!!

**Comment by romeotheriault** [comment]
I also have a need for this functionality. I need to do a rewrite a query but I lose part of the original hostname when I do the initial rewrite. Since the regex capture groups don't carry over to the answer rewrite I have no way to rewrite it back to the original hostname. It would be great if @euank 's commit would get merged.

**Comment by johnbelamaric** [comment]
I seem to recall a discussion where we planned to just *always* rewrite back to the original question name. @greenpau does that sound familiar?

**Comment by greenpau** [comment]
> I seem to recall a discussion where we planned to just always rewrite back to the original question name. @greenpau does that sound familiar?

@johnbelamaric , it does, but it does not always work that way with the more complex rewriting. Imagine that you have a response with CNAMEs from multiple subdomains.

For a request of A record and a response with a single A record it should be fine to rewrite automatically. Otherwise, it is probably better to having explicitly specify answer rewrite.

**Comment by euank** [comment]
@greenpau Can you explain a little more what cases this doesn't work in?

For a CNAME, my understanding is the desired question and answers look like so:

```
$ dig CNAME example.com
;; QUESTION SECTION:
;example.com.			IN	CNAME
;; ANSWER SECTION:
example.com		299	IN	CNAME	cname-target.example.com.
```

It seems like the right thing to do is still to rewrite the answer back to match the question.

Can you give a specific example of a dns setup and rewrite query where that strategy would give troublesome output?

**Comment by greenpau** [comment]
@euank , please follow this https://github.com/coredns/coredns/pull/3273#issuecomment-559826585 .

**Comment by euank** [comment]
@greenpau I think you misunderstood my question. Whether I want to make another attempt to contribute a fix isn't the immediate question.

My understanding of this issue was that rewriting back to the question would generally be correct. From your comment above. it sounds like you have an example where that's not the right thing.

If you have such an example, can you please explain it in a little more detail, preferably with an example corefile + query and what would be the right output for that scenario?

**Comment by greenpau** [comment]
@euank , I don’t want to answer your question because I rather that test harness sort it out. If you want your change in, please create separate PRs. Your previous PR changed functionality and testing at the same time. That is a no no. If your “functionality” PR passed through the test harness, then it is all good for a merge. If I were you, I would start with CLI parsing PR first.

**Comment by euank** [comment]
@greenpau maybe I'm misunderstanding the point of this issue then; I thought part of the point of it was to discuss the issue people were having and possible solutions.
If you know a reason that a given solution won't work, then you should explain it so that we can discuss and arrive at a more proper solution.

My current understanding of this issue is that rewriting back to the question by default will give good default behavior in every case.
If there's case that's not true in, that should be commented here so we can see if we need to take a different approach.
There's no point talking about specific PRs (mine or otherwise) of a given solution if we still have to discuss what the solution looks like at all first.

**Comment by greenpau** [comment]
@euank , I am not against any solution as long as it passed test harness and get acceptance via peer review.

**Comment by greenpau** [comment]
@euank , say the change in the behavior of a plugin passes existing test harness, then it is probably working as expected because existing test cases cover many use cases. If for some reason, a PR passes the harness but broke downstream apps or deployments, the it will be fixed by a patch and new tests covering any arising issues.

**Comment by greenpau** [comment]
@euank , as it relates to what would be the default, try doing it such that one can disable the new default if they choose to.

**Comment by polarathene** [comment]
I have a related use-case for this to leverage mDNS(supported by CoreDNS via external plugin).

```
local {
    rewrite stop {
        #name regex (.*)\.(.*)\.local {2}.local
        #answer name ?? Not possible currently to reference original question name
        # hard-coded example below:
        name regex service.hostname.local hostname.local
        answer name hostname.local service.hostname.local
    }
    mdns local
}
```

This allows for a system on the local network that publishes it's hostname via mDNS to also be aliased by additional labels. Most mDNS implementations have a two label limit (hostname.local), and would instead make a unicast query (which I'm using CoreDNS to catch, especially for Android, where mDNS is not supported out of the box). The `mdns` external plugin itself, only supports hosts that it can discover, so without aliasing to the hostname, many redundant mDNS addresses need to be published, and this is not pleasant to configure(Avahi for example only supports multiple hostnames for the same IP via `avahi-publish` or it's D-Bus API).

---

Unfortunately, I lack any experience with Golang, and have minimal experience with writing tests elsewhere.

If adding an additional directive for this or adding some support within `rewrite` is going to meet friction from maintainers, hopefully someone might consider making such functionality available via an external plugin for the time being? 

It really would be a nice feature to have access to, we're nearing two years since this issue was opened, upstreaming it into `rewrite` or a separate officially shipped plugin could be tackled afterwards since the main barrier there is someone with relevant experience to implement tests to the satisfaction of the CoreDNS maintainers, which is an understandable requirement, but may result in little progress any time soon based on the current history of this issue?

**Comment by stingshen** [comment]
@greenpau Is there any plan on this issue?

I have a similar use case too. In my K8s cluster, the user's pod can't access node IP and the ingress host (e.g. svc[1-10].example.com) points to the node IP. So we would rewrite the ingress host to ingress svc (e.g. ingress-nginx.ingress.cluster.local) for users because the user's pod can access ingress svc.

I have another possible solution to solve this issue. For the above use case, the rewrite statement would be:

rewrite { name regex (.*)\.example\.com$ ingress-nginx.ingress.cluster.local answer name **revert** }

I have written a rough prototype of this solution:

<https://github.com/stingshen/coredns/commit/99d3d48615050de0cdd8c692cabbb725aba27bf7>

**Comment by greenpau** [comment]
@stingshen , it is stale.

**Comment by stingshen** [comment]
> @stingshen , it is stale.

Do you have any comments on my above solution? The solution is basically based on https://github.com/coredns/coredns/pull/3273#issuecomment-558148275

**Comment by ntin90** [comment]
To those who need a work around:
> When using exact name rewrite rules, the answer gets rewritten automatically, and there is no need to define answer name. The rule below rewrites the name in a request from RED to BLUE, and subsequently rewrites the name in a corresponding response from BLUE to RED. The client in the request would see only RED and no BLUE.

If you have a small amount of fixed rules that you can list all out, you can use `rewrite name exact` as a work around.
```
rewrite continue name exact service-a.domain.x domain.y
rewrite continue name exact service-b.domain.x domain.y
...
```

**Comment by stingshen** [comment]
The coredns 1.8.4 fixes this issue! There is a new option to enable auto answer rewrite!

```
rewrite name regex .*\.publicdomain.com fqdn.publicdomain.com answer auto
```

**Comment by shilx3** [comment]
thanks. this fix helps me a lot.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "coredns/coredns"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月31日(星期一) 晚上8:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [coredns/coredns] plugin/rewrite: rewrite answer for regexes based on question (#2389)





 
The coredns 1.8.4 fixes this issue! There is a new option to enable auto answer rewrite!
 rewrite name regex .*\.publicdomain.com fqdn.publicdomain.com answer auto

**Comment by contrun** [comment]
I don't think 1.8.4 can
```
rewrite name regex (.*)\.(.*)\.publicdomain.com \2.publicdomain.com answer auto
```
, can it?
I basically want any in `*.abc.publicdomain.com` to be resolved to `abc.publicdomain.com`. But the prefix `abc` is dynamical.

**Comment by chrisohaver** [comment]
Closing. #4473 (released in 1.8.4) adds the `auto` option, which solves the issue.

**Comment by contrun** [comment]
@chrisohaver My specific user case above is still not solved. I want `*.abc.publicdomain.com` to be resolved to `abc.publicdomain.com`. Say I am requesting a resolution of `xyz.abc.publicdomain.com`. When upstream server return the result of `abc.publicdomain.com`, the result needs rewriting. The thing is that regex response rewrite will not work as the request context is forgotten. It does not know whether to rewrite `abc.publicdomain.com` to `xyz.abc.publicdomain.com` or `uvw.abc.publicdomain.com`. For a single domain, I can use rewrite auto (which would remember the request context). But my prefix `abc` is dynamic, I have to use regex response rewrite. And I can not recover `xyz.abc.publicdomain.com` from `abc.publicdomain.com`.

**Comment by chrisohaver** [comment]
@contrun, The following works ...

`rewrite name regex (.*)\.(.*)\.publicdomain.com {2}.publicdomain.com answer auto`

**Comment by contrun** [comment]
@chrisohaver Thanks. It actually works. I must have tried something different.

**Comment by kycfeel** [comment]
@chrisohaver Thank you so much. It's working like a charm.

By the way, is it also possible to exclude specific domains from the rewrite rule?

For example, I want to rewrite subdomains of `example.com`, except for the `test.example.com`.

**Comment by chrisohaver** [comment]
> By the way, is it also possible to exclude specific domains from the rewrite rule?

@kycfeel,

A few possible ways ...

1. With preceding rewrite rules that don't actually make any changes to the query ...

```
.:5399 {
  log
  errors
  rewrite name regex ^(test\.example\.com\.)$ {1}
  rewrite name regex (.*)(\.test\.example\.com\.)$ {1}{2}
  rewrite name regex (.*)\.(.*)\.example\.com\.$ {2}.example.com. answer auto
  forward . 8.8.8.8
}

```

2. Probably more operationally efficient with separate server blocks, e.g. ... 

```
test.example.com. {
  forward . 8.8.8.8
}

example.com. {
  rewrite name regex (.*)\.(.*)\. example\.com\.$ {2}. example.com. answer auto
  forward . 8.8.8.8
}
```

3. You might be able to craft a single regex to exclude a particular subdomain, but it would result in a long and complex regex.
