### ISSUE TITLE
Question regarding the DNS record chosen for headless services

### ISSUE THREAD

**Issue by svallala** [coredns/coredns#2415]
CoreDNS Version: 1.2.2

Namespace: test
Endpoint name: vnode10
Pod name: ip-172-21-10-20
In the kubernetes plugin configuration I have "endpoint_pod_names" enabled.

With above configuration, for a headless service, reverse lookup returns following DNS record

**ip-172-21-10-20.vnode10.test.svc.cluster.local**

There are applications which would verify the hostname by doing a reverse lookup on the IP address. This means we have to set the pod hostname to be the same as the above DNS record value, so far no issues.

Everything will work fine as long as FQDNs are used. A shortname for above POD would be "ip-172-21-10-20", which will not be resolved since the search domain strings will only have "test.svc.cluster.local svs.cluster.local cluster.local"

You can't add another search domain, because its not generic and if an application needs interaction with 10 pods, then there will be 10 unique endpoint names that need to be populated in the search string.

In the code reverse lookup has following lines, why can't the ep.Name be appended to the first value using a "-". This will make sure in the above case the shortname is "ip-172-21-10-20-vnode10" and everything will work fine.

	// If no cluster ips match, search endpoints
	for _, ep := range k.APIConn.EpIndexReverse(ip) {
		if len(k.Namespaces) > 0 && !k.namespaceExposed(ep.Namespace) {
			continue
		}
		for _, eps := range ep.Subsets {
			for _, addr := range eps.Addresses {
				if addr.IP == ip {
					**domain := strings.Join([]string{endpointHostname(addr, k.endpointNameMode), ep.Name, ep.Namespace, Svc, k.primaryZone()}, ".")**
					return []msg.Service{{Host: domain, TTL: k.ttl}}
				}
			}
		}
	}
	return nil
}

Thanks for looking at this. Please let me know if additional information is needed.

**Comment by svallala** [comment]
Please ignore the "**" in the code snippet, was trying to highlight the line.

**Comment by johnbelamaric** [comment]
That wouldn't follow the standard Kubernetes spec for endpoint names in
headless services:
https://github.com/kubernetes/dns/blob/master/docs/specification.md

So it would be non-compliant. I think it was spec'd that way to avoid name
conflicts - "." is not allowed in any name, but "-" is. So, if it were as
you say, you would have ambiguity in this case:


headless service: bar
endpoint: foo
namespace: baz

spec fqdn: foo.bar.baz.svc.cluster.local
your fqdn: foo-bar.baz.svc.cluster.local


clusterip service: foo-bar
namespace: baz

spec fqdn: foo-bar.baz.svc.cluster.local

I think you are stuck with using FQDNs or at least with using
"endpoint.service'.

John

**Comment by svallala** [comment]
Thanks John. I now understand that '-' can result in conflict. Why is the behavior different than cluster service? Why not just use the endpoint name only? Is it because with cluster service there is single cluster ip and with headless service there could be multiple ip addresses?

**Comment by johnbelamaric** [comment]
For a headless service, you can query it by service name just like a
cluster IP service. It will return an A record for each pod running the
service:

dnstools# dig helloweb.default.svc.cluster.local.

; <<>> DiG 9.11.3 <<>> helloweb.default.svc.cluster.local.
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to
DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53010
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;helloweb.default.svc.cluster.local. IN A

;; ANSWER SECTION:
helloweb.default.svc.cluster.local. 30 IN A 10.4.4.14
helloweb.default.svc.cluster.local. 30 IN A 10.4.4.11
helloweb.default.svc.cluster.local. 30 IN A 10.4.4.12
helloweb.default.svc.cluster.local. 30 IN A 10.4.4.13

;; Query time: 2 msec
;; SERVER: 10.7.240.10#53(10.7.240.10)
;; WHEN: Fri Dec 21 22:50:46 UTC 2018
;; MSG SIZE  rcvd: 116


Not sure what you mean by "just use the endpoint name" - it is the same
name as the service.

**Comment by svallala** [comment]
My question was the reverse lookup for a Pod IP which has a headless service configured be derived the same way as a cluster IP.

domain := strings.Join([]string{service.Name, service.Namespace, Svc, k.primaryZone()}, ".")
