### ISSUE TITLE
Deprecation policy for Kubernetes related configuration

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#2462]
Following comments on #2455 : 

> Small release, useful for announcing some backward incompat stuff going out in the next (1.4.0) release.

CoreDNS is delivered in Kubernetes with a "default" Corefile.
Today it includes the `kubernetes` plugin with the `upstream` directive

`upstream` will be deprecated in 1.3.1, and backward incompatible in 1.4.0

**What about the delivery in the Kuberentes releases ?**

Should we ensure the deprecated version (at least for the kubernetes plugin) is available with next release of k8s (v1.14 - end March 2019) before being backward incompatible in the following release of k8s (v1.15 - end June 2019) ?

By extension, should we have a specific deprecation policy when it comes to features delivered in the [default Corefile for Kuberentes](https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed) ? 

NOTE: change in the default Corefile require:
- Ensure the translation from kube-dns to CoreDNS is valid
- Spread-out the change to the right k8s install tools (kubeadm, kube-up, minikube, kops, ...)
- TODO: define a way for existing k8s installation with CoreDNS to handle the backward incompatibility.

**Comment by fturib** [comment]
@chrisohaver , @rajansandeep , @johnbelamaric , @miekg : please comment on this concern. Thanks!

**Comment by chrisohaver** [comment]
I think it's inevitable that introducing a backward incompatibility that affects the default configuration will cause pain for a lot of people.  IMO the fact the coredns just became default in the previous k8s release is one reason to defer the backward incompatibility.

IMO - If the next k8s release includes coredns 1.4, then from a Kubernetes release perspective, this deprecation schedule is a wee bit too fast (from valid to broken in one k8s release).  For plugins that are used in the k8s default, it would be less sudden if we were to stretch out the schedule so that it spans at least a couple of Kubernetes releases. 

We could do this by delaying the 1.4 release to be after the next k8s release.
Or, instead by deferring the backward incompatibility until after 1.4.

If those are unacceptable, then so be it.

In any scenario, I think we eventually have to write a configuration migration tool anyways. But getting the tool authored and integrated into every k8s install tool in one k8s release will be very challenging.

**Comment by chrisohaver** [comment]
Another option, If 1.4 is released with the backward incompatibility we could deploy an older version of coredns in the next k8s release.  This would, i think, be acceptable if there are no major fixes k8s related fixes in 1.4.   

This would buy us time from a k8s perspective without imposing a delay in the coredns release schedule.

**Comment by chrisohaver** [comment]
I've deleted my comments - I got the impression from this issue, that the changes would be _breaking_, but the recently merged upstream change is not breaking, `upstream` is ignored. 

The default config contains only `upstream`, with no parameter, so the behavior is not changed.

**Comment by miekg** [comment]
The multiple endpoints might need a tweak to consume remaining args to not
break configs. In 1.4.1 we kill that off properly.

**Comment by fturib** [comment]
>Should we ensure the deprecated version (at least for the kubernetes plugin) is available with next release of k8s (v1.14 - end March 2019) before being backward incompatible in the following release of k8s (v1.15 - end June 2019) ?

@miekg , what is your opinion on this ?

**Comment by miekg** [comment]
re: multiple endpoints. The right thing was done there:
~~~
				if len(args) > 1 {
					log.Warningf("Multiple endpoints have been deprecated, only the first specified endpoint '%s' is used", args[0])
				}
~~~
so we're good.

We have a (undocumented, I should fix that) that we announce, make the change - but keep the config, remove the feature.

Don't understand why this needs more discussion.

**Comment by fturib** [comment]
I tried to express my concerns about speed of deprecation/backward incompatibility in the PR #2470.
Therefore I can close this issue.
