### ISSUE TITLE
plugin/k8s_external: Support Ingress-resources

### ISSUE THREAD

**Issue by voidengineer** [coredns/coredns#2465]
Since 1.3.0 CoreDNS supports exposing k8s LB services with the k8s_external plugin.

It would be great to support also ingress-resources (with k8s_external or a new plugin).
An ingress-resources spec contains a list of rules (each with a hostname) and its status can contain the associated ip-addresses or hostnames.

**Comment by johnbelamaric** [comment]
See also https://groups.google.com/d/topic/coredns-discuss/7CBvHRgENg0/discussion

**Comment by chrisohaver** [comment]
Ingress objects wont always all sit in the same zone.  Before starting on this, we should get consensus and approval up front on how this will be handled in an acceptable way.

This could be done as an extension of _k8s_external_, but doing so would require that we treat certain zones in the plugin's zone list with special/different significance.  While this is possible to do, that kind of pattern has been rejected in prior plugin PRs.  So I think we need to do this as a separate plugin.

As a separate plugin, one could list each ingress domain name in the plugin's zone list.  This could lend itself to a long zone list. These zones are not strictly "zones"... they are FQDNs, which doesn't fit snuggly with how the zone routing works in CoreDNS. In the example below, the plugin would process queries `moo.foo.example.com` because it's in the zone `foo.example.com`.

```
k8s_ingress foo.example.com bar.example.org baz.example.net {
    fallthrough
}
```

The `fallthrough` directive is included here because like the _host_ plugin, _k8s_ingress_ would not be authoritative for the zones (e.g. we'd need to fall through to next plugin for `moo.foo.example.com`).

One could have the plugin process everything, and fall through when the query does not match an ingress host ... Cleaner configuration, perhaps a bit more overhead (but i don't think much).  

```
k8s_ingress . {
    fallthrough
}
```

From this perspective, zones are still zones, and someone could selectively expose ingress names falling within certain zones if required.

**Comment by voidengineer** [comment]
I think an additional plugin `k8s_ingress` makes sense. Most likely someone will ask for `k8s_istio_gateway` in the near future.

Maybe it should be possible to restrict the kubernetes namespaces where the ingress resources are searched and to specifiy the plugin multiple times.

```
k8s_ingress qa.example.org {
  namespace qa
  fallthrough
}

k8s_ingress production.example.org {
  namespace production
  fallthrough
}
```

**Comment by chrisohaver** [comment]
I think that would be equivalent to ... 
```
k8s_ingress qa.example.org production.example.org {
  namespace qa production
  fallthrough
}
```

... unless there are Ingress in the `qa` namespace with hostnames in the zone `production.example.org` (or vice versa).

**Comment by voidengineer** [comment]
After giving it another thought, what I wanted to accomplish (restricting domains to namespaces) would not work, so the whole namespace-thing most likely is not neccesary. `k8s_external` does not allow such a restriction either.

But other than that, I would love to see this `k8s_ingress` plugin.

**Comment by voidengineer** [comment]
Any chance this will happen in the near future?

**Comment by anton-johansson** [comment]
I really would love this support as well. Any news on this?

Really, what I would love is to be able to configure a `k8s_plugin` together with an ingress class (`kubernetes.io/ingress.class` annotation) and a target service (namespace & service name). Like this:

```
.:53 {
  errors
  health
  kubernetes cluster.local in-addr.arpa ip6.arpa {
    pods insecure
    upstream
    fallthrough in-addr.arpa ip6.arpa
  }
  k8s_ingress . {
    ingressClass external
    serviceName external-nginx
    serviceNamespace ingress
    fallthrough
  }
  k8s_ingress . {
    ingressClass internal
    serviceName internal-nginx
    serviceNamespace ingress
    fallthrough
  }
  prometheus :9153
  forward . /etc/resolv.conf
  cache 30
  loop
  reload
  loadbalance
}
```

The plugin could watch `Ingress` resources matching the ingress class and the specified services and simply resolve those hostnames to the services `clusterIP`.

Maybe this solution won't work, I don't know, I just feel it would be great to have something like this. Ideas? Thoughts?

**Comment by voidengineer** [comment]
Great idea to restrict on `ingressClass`!

> The plugin could watch Ingress resources matching the ingress class and the specified services and simply resolve those hostnames to the services clusterIP.

I think this should be the `LoadBalancerIP`, but this should not be necessary since Ingress Resources should have their public IP in the status-subresource.

**Comment by anton-johansson** [comment]
> I think this should be the `LoadBalancerIP`, but this should not be necessary since Ingress Resources should have their public IP in the status-subresource.

Hmm, if it would be the `loadBalancerIP`, this wouldn't make any difference for me. The hostnames already resolve to the `loadBalancerIP` using my DNS server outside the cluster. My issue is that the `loadBalancerIP` is assigned by MetalLB and I cannot reach that from within the cluster (due to `externalTrafficPolicy: Local`). This is why I want to force it to resolve to the `clusterIP` if possible, and therefore need to configure the service name and namespace. :(

Also, the `status`-subresource of my `Ingress`-resources look like this:
```yaml
status:
  loadBalancer:
    ingress:
    - {}
```

**Comment by chrisohaver** [comment]
@anton-johansson,

This is a different feature than proposed in #2214.

#2214 is internal facing, in that it intends to serve Service records to Pods inside the cluster. Therefore, the IPs used in the records would be internal IPs.

_This_ feature is external facing: it intends to serve Service records to clients outside of the cluster.   Therefore the IPs served would be external IPs (in this case, the external IPs of the ingress service).

Both are completely valid and useful, but they are distinct.

**Comment by anton-johansson** [comment]
@chrisohaver: Aha, allright. I see the difference now.

I did however realize that the solution I'm looking for ins't exactly what is proposed in #2214 either. I'll do some more digging.

**Comment by networkop** [comment]
If no one is working on this at the moment, I can pick this up. I already have a rough working implementation of this plugin so I would be happy to contribute it back.

**Comment by miekg** [comment]
As per https://github.com/coredns/coredns/pull/3935 will be done as external plugin

**Comment by reesericci** [comment]
@networkop how close are we to a final k8s_ingress plugin?

**Comment by networkop** [comment]
@reesericci checkout https://coredns.io/explugins/k8s_gateway/ - it absorbs the functions of both k8s_ingress and k8s_external

**Comment by reesericci** [comment]
After making this comment I found that, and now am stuck on making a docker container with every plugin and that external plugin. :(
