### ISSUE TITLE
accepting dynamic update requests

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#2517]
I have a need of being able to forward dynamic update requests.

Currently in CoreDNS, when we create a `dns.Server`, we don't pass a `MsgAcceptFunc`, so we use the default function.  IIUC, the default function discards all DNS update requests before they can be forwarded.

**Comment by chrisohaver** [comment]
We could pass a custom `MsgAcceptFunc`, that lets dynamic updates through, so for example the forward plugin can forward them.

But unless we enable this globally for everyone, we would need a way to turn it off/on. E.g. some kind of an option to turn this on.  Where should this option go?

here are some ideas none of which I am particularly fond of...

- add the option as a new no-op plugin?
- a directive in the forward plugin?
- command line flag? (eww)

in the vein of a plugin that just turns this option off/on, we could introduce a "server" plugin that would hold options like this, the first one being "accept-ddns"?

**Comment by stp-ip** [comment]
Curious: Could you give some context on why a message update would be passed through and not handled by CoreDNS itself?

**Comment by chrisohaver** [comment]
As an intermediate solution until it can be handled by CoreDNS itself.

**Comment by chrisohaver** [comment]
> Curious: Could you give some context on why a message update would be passed through and not handled by CoreDNS itself?

Better answer (i deleted my previous answer, as i was told it was incorrect)...

The forwarding Coredns does not have access to the backend system that holds the DNS records.
So, it needs to forward the requests to a DDNS capable server that does.
The client sending the requests cannot connect directly to the DDNS capable server.

**Comment by chrisohaver** [comment]
That said, the "DDNS capable server" could be a CoreDNS too (once a plugin is developed to handle DDNS and talk to the backend).  But in that case, there are two CoreDNSs, one forwarding, and the other processing the requests.

In either case, we need a way of enabling acceptance of dns update requests by the server.

**Comment by chrisohaver** [comment]
Or a new plugin called `accept`, that allows you to specify which DNS OP codes we will accept, e.g. ...

```
accept {
  query notify update
}
```

**Comment by chrisohaver** [comment]
I've been going over the RFC 2136  DDNS, and I noticed this:

```
3 - Server Behavior

   A server, upon receiving an UPDATE request, will signal NOTIMP to the
   requestor if the UPDATE opcode is not recognized or if it is
   recognized but has not been implemented. ...
```

Looking at the code, I think we reply with `FORMERR` instead of `NOTIMP`.  So, technically we dont follow the RFC to the letter.

**Comment by miekg** [comment]
Good catch. Should probably change that.

Re: dyn updates: allowing this means updating all plugins to look for this
and discard any such packets, which can be done, maybe we can add it to
Match which most of them should use anyway.

But also: forwarding dyn updates sounds like a real corner case...

**Comment by chrisohaver** [comment]
> But also: forwarding dyn updates sounds like a real corner case...

So, does that mean you don't want to support it in CoreDNS?

> dyn updates: allowing this means updating all plugins to look for this
and discard any such packets,

I'm not familiar with the miekg/dns code, but it seems like we allowed dns updates through prior to miekg/dns 1.1.0.

**Comment by miekg** [comment]
yes, I've killed that for reason outlined above. Also the possibility for a DoS attack using dynamic update packets.

**Comment by miekg** [comment]
closing, as this will not be supported.

**Comment by abrodmann** [comment]
@miekg @chrisohaver as dyn updates are a fundamental building block of modern dns infrastructures, saying no to it deeply restricts the use cases of coredns (e.g. dns for enterprises). Is there anything we can do to convince you otherwise? e.g. is your no to dyn updates temporary (no time now) or definite (it never will support them, look for alternative products)?

I personally regard the architecture of coredns as great and would find it a pity if dyn updates would be banned from its future development.

@chrisohaver how did you solve your issue / need?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] accepting dyn..." ]
>@miekg @chrisohaver as dyn updates are a fundamental building block of modern dns infrastructures, saying no to it deeply restricts the use cases of coredns (e.g. dns for enterprises). Is there anything we can do to convince you otherwise? e.g. is your no to dyn updates temporary (no time now) or definite (it never will support them, look for alternative products)?
>
>I personally regard the architecture of coredns as great and would find it a pity if dyn updates would be banned from its future development.

It's hard to do right, but I'm not against it.

Making e.g. the file plugin support them will mean fine grained locking, dealing 
with occluded data, having a journaling system and setting an auth/authz system 
(although auth/authz is a big word here, because there is very little). And this 
all needs to be done without impacting the serving speed too much...

From a personal view I don't see much benefit from it; as DNS servers will move 
to serve from datastores and you provision those completely separately from your 
DNS infrastructure.

If you need it now you need to put it together yourself and looks for 
alternatives.

**Comment by johnbelamaric** [comment]
I don't think anyone is dead-set against this. It's just a LOT of work to do properly.

https://github.com/coredns/coredns/pull/1822#issuecomment-390780769

**Comment by chrisohaver** [comment]
@abrodmann, I think it's a build time patch to core/dnsserver/server.go. It also required a fix in upstream miekg/dns https://github.com/miekg/dns/pull/920.

**Comment by yaocw2020** [comment]
Hi, everyone, after two years, is there any solution to support ddns in coredns, or any alternative to support ddns in Kubernetes？
