### ISSUE TITLE
CoreDNS returns SERVFAIL for query sent to POD ip, but NXDOMAIN for same query to localhost

### ISSUE THREAD

**Issue by FayeGibbins** [coredns/coredns#2532]
Version: 1.3.0
k8s: 1.9.8

My config file:

```
****REDACTED****:53 {
    errors
    log
    health :8082
    proxy . ****REDACTED**** ****REDACTED**** {
        protocol dns force_tcp
    }
    cache 300
}
****REDACTED****:53 {
    errors
    log
    health :8081
    proxy . ****REDACTED**** ****REDACTED**** {
        protocol dns force_tcp
    }
    cache 300
}
****REDACTED****:53 {
    errors
    log
    health :8089
    proxy . ****REDACTED**** ****REDACTED**** {
        protocol dns force_tcp
    }
    cache 300
}
****REDACTED****:53 {
    errors
    log
    health :8085
    autopath @kubernetes
    kubernetes ****REDACTED**** {
        pods verified
        upstream
    }
    cache 300
}
****REDACTED****:53 {
    errors
    health :8086
    log
    proxy . 169.254.169.253 {
        protocol dns force_tcp
    }
    cache 300
}
****REDACTED****:53 {
    errors
    health :8087
    log
    proxy . 169.254.169.253 {
        protocol dns force_tcp
    }
    cache 300
}
****REDACTED****:53 {
    errors
    log
    health :8088
    proxy . 169.254.169.253 {
        protocol dns force_tcp
    }
    cache 300
}
.:53 {
    errors
    log
    health :8080
    proxy . 169.254.169.253
    cache 300
}
```

Issue:

If I sh into the CoreDNS pod and run: `dig ****REDACTED**** @localhost` I get NXDOMAIN, as you would expect.

But if I sh into the CoreDNS pod and run: `dig ****REDACTED**** @<my pods ip>` I get SERVFAIL! :-(

Here are some logs of both occurring:

```
2019-02-07T09:29:23.121Z [INFO] ****REDACTED**** ****REDACTED****:46818 - 8711 "A IN ****REDACTED**** udp 84 false 4096" SERVFAIL qr,rd 84 0.000185858s
2019-02-07T09:29:23.121Z [ERROR] plugin/errors: 0 ****REDACTED**** A: plugin/kubernetes: no next plugin found
2019-02-07T09:29:33.656Z [INFO] [::1]:47288 - 8698 "A IN ****REDACTED**** udp 84 false 4096" NXDOMAIN qr,aa,rd,ra 166 0.00017482s
```

Here is some additional information from the CoreDNS's shell were I did the tests

```
root@coredns-faye-7685d8d896-cf7mz:~/go/src/github.com/coredns/coredns# ./coredns -version
CoreDNS-1.3.0
linux/amd64, go1.11.4,
root@coredns-faye-7685d8d896-cf7mz:/# dig ****REDACTED**** @****REDACTED**** ****REDACTED****

; <<>> DiG 9.10.3-P4-Debian <<>> ****REDACTED**** @****REDACTED**** ****REDACTED****
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 8711
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;****REDACTED**** IN A

;; Query time: 0 msec
;; SERVER: ****REDACTED****#53(****REDACTED****)
;; WHEN: Thu Feb 07 09:29:23 UTC 2019
;; MSG SIZE  rcvd: 84

root@coredns-faye-7685d8d896-cf7mz:/# dig ****REDACTED**** @localhost

; <<>> DiG 9.10.3-P4-Debian <<>> ****REDACTED**** @localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 8698
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;****REDACTED**** IN A

;; AUTHORITY SECTION:
****REDACTED****		30	IN	SOA	****REDACTED**** ****REDACTED**** 1549531732 7200 1800 86400 30

;; Query time: 0 msec
;; SERVER: ::1#53(::1)
;; WHEN: Thu Feb 07 09:29:33 UTC 2019
;; MSG SIZE  rcvd: 177

root@coredns-faye-7685d8d896-cf7mz:/# date
Thu Feb  7 09:30:34 UTC 2019
root@coredns-faye-7685d8d896-cf7mz:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if46: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8981 qdisc noqueue state UP group default
    link/ether fe:bd:71:bb:6b:dd brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet ****REDACTED****/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 ****REDACTED****/64 scope link
       valid_lft forever preferred_lft forever
root@coredns-faye-7685d8d896-cf7mz:/# dig -v
DiG 9.10.3-P4-Debian
root@coredns-faye-7685d8d896-cf7mz:/# uname -a
Linux coredns-faye-7685d8d896-cf7mz 4.14.72-73.55.amzn2.x86_64 #1 SMP Thu Sep 27 23:37:24 UTC 2018 x86_64 GNU/Linux
```

Can someone explain/suggest a fix for this odd behaviour please?

FYI We split up the zones like this so we could get separate prometheus metrics for each one.

**Comment by chrisohaver** [comment]
It seems you are using a custom docker image.  Is that correct?  I don't think it matters here, but just want to verify.

These appear to be interactions with `autopath`....

On the surface, the `SERVFAIL` response is expected because `autopath` will try to fall through to the next plugin if the `kubernetes` plugin producing no results from the `cluster.local` search domains.  There is no next plugin in that stanza, hence the SERVFAIL, and the error. 
E.g.  For a query for `slipstream.skyscanner.net.kube-system.svc.cluster.local.` ...
autopath tries:
`slipstream.skyscanner.net.kube-system.svc.cluster.local.` in the kubernetes plugin (and finds nothing)
`slipstream.skyscanner.net.svc.cluster.local.` in the kubernetes plugin (and finds nothing)
`slipstream.skyscanner.net.cluster.local.` in the kubernetes plugin (and finds nothing)
`slipstream.skyscanner.net` in the next plugin (but there isn't a next plugin, so SERVFAIL)

The `NXDOMAIN` response can also be explained by how `autopath` works.  To get the search paths right, `autopath` has to know the namespace of the Pod that sent the request. It does this by looking up the source ip of the dns request in the Pod list (this is why autopath requires `pods verified`). If it cannot find the IP, then it treats the query as a normal query, and doesnt try to do the domain search on the server side.  So, in this example, it just tries `slipstream.skyscanner.net.kube-system.svc.cluster.local.` and gets nothing, so returns NXDOMAIN.

In these cases, the Pod that sent the request is  coredns itself.

So, the difference in answer between querying localhost vs the Pod IP from coredns itself is probably caused by the source IP changing depending on which way you query ...  In the log you can see that the source IP is `10.231.55.42` in the SERVFAIL case, and `::1` in the NXDOMAIN case.

To get this to work from other pods, you can add a `proxy` to upstream in the cluster.local stanza...

```
cluster.local:53 {
    errors
    log
    health :8085
    autopath @kubernetes
    kubernetes cluster.local {
        pods verified
        upstream
    }
    proxy . 169.254.169.253
    cache 300
}
```

Although, this might disturb the separation of metrics. I'm not familiar with the mechanics of metrics in this regard.

**Comment by FayeGibbins** [comment]
Hi,

Wow! I’m impressed. 😊

I’ll give your suggestion a go and can I just say that’s one damn fine email!

Thanks
Faye

**Comment by FayeGibbins** [comment]
aha! I see.

k8s plug was returning a non nill error but adding in the proxy line caused the query to be run through route53 as well which (i see from my testing) results in a NXDOMAIN which then triggers autopath return.

Seems to me that perhaps, in this circumstance (having reviewed the RFC) it would be better if, in the lack of a lookup in k8s plugin (when queried via qutopath), it should return NXDOMAIN. After all the domain doesn't exist but there's nothing in the k8s cluster to stop it being looked up.

If the k8s plugin can't querry the k8s api or the k8s plugin timeouts then it would be appropriate to report out of the automap pluging a SERVFAIL, or at least a trigger to autopath to return SERVFAIL.

This could perhaps be achieved by examining the contents of the 'nil' returned by the k8s plugin, rather than just looking for its existence.

**Comment by miekg** [comment]
this looks be resolved/clarified.
