### ISSUE TITLE
plugin/cache: search harder for nxdomain

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2609]
In the cache plugin every nxdomain is cached. It would be more efficient to cache the top-level NXDOMAIN and not all underlying ones, which per definition, are NXDOMAIN is the name above doesn't exist.

**Comment by ckcd** [comment]
Does it means that if `bbb.com` is `NXDOMAIN`, then `aaa.bbb.com` must be `NXDOMAIN` ? so we can just cache the shortest one ?

if so, maybe we also need to change query strategy of `plugin/cache` to find the shortest cache item if query for a long domain.

**Comment by miekg** [comment]
Yes that's what it means

**Comment by ckcd** [comment]
@miekg thanks for your reply,

I am interesting in this issue, can i take it ?

**Comment by miekg** [comment]
Sure!

**Comment by ckcd** [comment]
@miekg Hi, 

I have a little question of this case:

In above talk, we thinks that if `bbb.com` is `NXDOMAIN` then `aaa.bbb.com` must be `NXDOMAIN`. However in a K8S cluster, `dig local.` will get `NXDOMAIN`, but `dig cluster.local.` will get `NOERROR` because `cluster.local.` is base domain of k8s services.

So i am confuse of this issue, please correct me.

Thanks a lot !!!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/cache:..." ]
>@miekg Hi,
>
>I have a little question of this case:
>
>in above talk, we thinks that if `bbb.com` is `NXDOMAIN` then `aaa.bbb.com` must be `NXDOMAIN`. However in a K8S cluster, `dig local.` will get `NXDOMAIN`, but `dig cluster.local.` will get `NOERROR` because `cluster.local.` is base domain of k8s services.

nice catch, that's wrong.
