### ISSUE TITLE
Support Azure DNS backend

### ISSUE THREAD

**Issue by krizhan** [coredns/coredns#2820]
From https://github.com/cncf/soc#support-azure-dns-backend, a suggested proposal was to implement a plugin to support azure dns backend (although I can't seem to find an open issue for it). However, it seems that this project was not selected. I am willing to implement this if help is still wanted for this plugin.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Support Azure DNS..." ]
>From https://github.com/cncf/soc#support-azure-dns-backend, a suggested proposal was to implement a plugin to support azure dns backend (although I can't seem to find an open issue for it). However, it seems that this project was not selected. I am willing to implement this if help is still wanted for this plugin.

yep, this would still be welcome! I think/hope you can make this somewhat like 
the route53 plugin.

/Miek

--
Miek Gieben

**Comment by yongtang** [comment]
Yes Azure dns backend could be a good addition 👍 . Would really help those with azure deployment.

**Comment by palash25** [comment]
hi @yongtang , I had submitted a  GSoC proposal for this plugin and Nikhita Raghunath had reached out to me after the GSoC results saying that CNCF might be interested in sponsoring me to work on this project under the community bridge programme ( https://communitybridge.org/ ) but it wasn't decided when the work would start because CNCF is still busy deciding how many students to sponsor under the programme.

So I am a little confused that @krizhan wants to work on this now and someone is already working on the google cloud plugin too. Did Nikhita reach out to you regarding this @yongtang ?

**Comment by yongtang** [comment]
@palash25 I was not aware of the community bridge program before, and have not been contacted. Maybe you can coordinate with @krizhan about this proposal?

**Comment by palash25** [comment]
I have DM'd Nikhita on k8s slack, I was under the impression that she might have contacted you regarding this. 

Once I get a reply from her, I will update it here, thanks for the quick response though :smile:

**Comment by krizhan** [comment]
Np. @palash25 can tackle this issue since its been hard to find free time w work anyways.

**Comment by palash25** [comment]
thanks @krizhan

**Comment by idvoretskyi** [comment]
@palash25 CNCF is happy to allocate one slot for CoreDNS at the Community Bridge. We'll follow up via email.

**Comment by yongtang** [comment]
This issue could be closed as PR #2945 has been merged.
