### ISSUE TITLE
Support Google Cloud DNS backend

### ISSUE THREAD

**Issue by yongtang** [coredns/coredns#2822]
This was one of the candidate proposals in GSoC: (https://github.com/cncf/soc#support-google-cloud-dns-backend). Think it is still very much relevant.

CoreDNS is able to serve DNS with cloud vendors (such as AWS) as the backend. The feature is very much useful in a hybrid environment where cloud-vendor specific service endpoints need to be exposed to clusters managed by Kubernetes. The goal of this feature is to support Google Cloud DNS (similar to already supported route53 plugin) as a backend for CoreDNS.

**Comment by stp-ip** [comment]
Sidenote as this came up. The route53 plugin is using stuff from the file plugin, which we might keep in mind to split out so not all new plugins such as this one rely on file going forward.

**Comment by miekg** [comment]
What's actually reused here? (Saw your other issue flagging this) #curious

**Comment by stp-ip** [comment]
As far as I could see from a rough view it was using file.zone and file.NewZone.

Also:
file.zone and the reloading code is used by auto plugin and file.NewZone by secondary.

Might have a few more usages, but they feel more like was there was used, than fully intentional.

**Comment by miekg** [comment]
Ah ok. Seems like a quick way to get up to speed and use a zone like
structure.

**Comment by stp-ip** [comment]
Yes, but that could make the case for splitting this out into a pkg. Reuse between plugins feels suboptimal. Not a huge problem, just thought it's a good to know here.

**Comment by stp-ip** [comment]
For reference: https://github.com/coredns/coredns/issues/2805

**Comment by miekg** [comment]
I'll take a deeper look, it may be the case something more light weight can
be used here.

I agree with reuse of things between plugins should be kept to a minimum.

**Comment by jiachengxu** [comment]
Hi @yongtang ,
This feature sounds interesting to me, and I am willing to work on this, can you provide me some more details, please?

**Comment by yongtang** [comment]
@jiachengxu This plugin is more or less similar to Route53 plugin which is already in CoreDNS repo:
https://github.com/coredns/coredns/tree/master/plugin/route53

In addition, you could also take a look at:
https://github.com/googleapis/google-api-go-client

I think it will give you some information about golang API for DNS.

**Comment by maguro** [comment]
@jiachengxu, how are thing going on this?  I am very keen on using this as soon as possible. If you can’t pick it up this week would you mind if I picked it up?

**Comment by stp-ip** [comment]
As discussed in person with @jiachengxu this might be a chance to think about how to split out the few reused functions/structures from file or if they are really needed.

Also happy for you to collaborate on this feature @maguro, but totally up to you both.

**Comment by sharmaansh21** [comment]
I would like to develop this as my first contribution towards coredns if it's ok with you guys :)

**Comment by miekg** [comment]
If noone else speaks up, please go ahead and submit something.

**Comment by jiachengxu** [comment]
Hi @maguro @sharmaanshul2102 ,
Sorry for the late reply, I just came back from the Kubecon 2019 Europe, and now I am working on this issue, and I will send a PR when it is ready to review, but at the same time, please free to also work on this.

**Comment by jiachengxu** [comment]
> As discussed in person with @jiachengxu this might be a chance to think about how to split out the few reused functions/structures from file or if they are really needed.

Really nice to meet you in person!!!

**Comment by maguro** [comment]
I've already started work on this since I need it.  Here's its `README.md`:

# gcpdns

## Name

*gcpdns* - enables serving zone data from Google Cloud DNS.

## Description

The gcpdns plugin is useful for serving zones from resource record sets in 
Google Cloud DNS. This plugin supports all Google Cloud DNS records
([https://cloud.google.com/dns/docs/overview](https://cloud.google.com/dns/docs/overview#supported_dns_record_types)). 
The gcpdns plugin can be used when CoreDNS is deployed on Google Cloud or
elsewhere.

## Syntax

~~~ txt
gcpdns [DNS_NAME:GCP_PROJECT/ZONE_NAME...] {
    [gcp_service_account GCP_SERVICE_ACCOUNT_ENV_VAR]
    [gcp_api_key GCP_API_KEY_ENV_VAR]
    upstream
    fallthrough [ZONES...]
}
~~~

* **DNS_NAME** the name of the domain to be accessed. When there are multiple 
  zones with overlapping domains (private vs. public hosted zone), CoreDNS does 
  the lookup in the given order here. Therefore, for a non-existing resource 
  record, SOA response will be from the rightmost zone.

* **GCP_PROJECT** the GCP project that hosts the GCP Cloud DNS zone.

* **ZONE_NAME** the ID of the hosted zone that contains the resource record 
  sets to be accessed.

* **GCP_SERVICE_ACCOUNT_ENV_VAR** the environmental variable name whose JSON
  value is the Google credential for the GCP
  [service account](https://cloud.google.com/docs/authentication/#service_accounts)
  to be used when querying the Google Cloud DNS (optional).
  
  `gcp_service_account` takes precedence over `gcp_api_key`.

  If neither GCP service account or API key are provided, then CoreDNS tries to 
  obtain GCP credentials using the strategy "Application Default Credentials"
  detailed below.

* **GCP_API_KEY_ENV_VAR** the environmental variable name whose value is the 
  [GCP API key](https://cloud.google.com/docs/authentication/api-keys) to be 
  used when querying the Google Cloud DNS (optional).

  If neither GCP service account or API key are provided, then CoreDNS tries to 
  obtain GCP credentials using the strategy "Application Default Credentials"
  detailed below.

* `upstream`is used for resolving services that point to external hosts (eg. 
  used to resolve CNAMEs). CoreDNS will resolve against itself.

* `fallthrough` If zone matches and no record can be generated, pass request to
  the next plugin.  If **[ZONES...]** is omitted, then fallthrough happens for 
  all zones for which the plugin is authoritative. If specific zones are listed 
  (for example `in-addr.arpa` and `ip6.arpa`), then only queries for 
  those zones will be subject to fallthrough.

* **ZONES** zones it should be authoritative for. If empty, the zones from the 
  configuration block.

## Examples

Enable gcpdns with GCP Application Default Credentials and an upstream:

~~~ txt
. {
    gcpdns example.org.:my-project/my-zone-name {
      upstream
    }
    forward . 10.0.0.1
}
~~~

Enable gcpdns with explicit GCP service account credentials stored in the
environmental variable `DNS_SERVICE_ACCOUNT`:

~~~ txt
. {
    gcpdns example.org.:my-project/my-zone-name {
      gcp_service_account DNS_SERVICE_ACCOUNT
    }
}
~~~

Enable gcpdns with explicit GCP API key credentials stored in the
environmental variable `DNS_API_KEY`:

~~~ txt
. {
    gcpdns example.org.:my-project/my-zone-name {
      gcp_api_key DNS_API_KEY
    }
}
~~~

Enable gcpdns with fallthrough:

~~~ txt
. {
    gcpdns example.org.:my-project/my-org-zone-name example.gov.:my-project/my-gov-zone-name {
      fallthrough example.gov.
    }
}
~~~

Enable gcpdns with multiple hosted zones with the same domain:

~~~ txt
. {
    gcpdns example.org.:my-private-project/my-private-zone-name example.org.:my-public-project/my-public-zone-name
}
~~~

## Application Default Credentials

GCP Cloud DNS client uses a strategy called "Application Default Credentials" 
to find GCP credentials.

It looks for credentials in the following places, preferring the first location
found:

1. A JSON file whose path is specified by the
   `GOOGLE_APPLICATION_CREDENTIALS` environment variable.
2. A JSON file in a location known to the `gcloud` command-line tool.
   On Windows, this is `%APPDATA%/gcloud/application_default_credentials.json`.
   On other systems, `$HOME/.config/gcloud/application_default_credentials.json`.
3. On Google App Engine standard first generation runtimes (<= Go 1.9) it uses
   the `appengine.AccessToken` function.
4. On Google Compute Engine, Google App Engine standard second generation
   runtimes (>= Go 1.11), and Google App Engine flexible environment, it 
   fetches credentials from the metadata server.

**Comment by shivani-1521** [comment]
Hello!
I had started work on this too. (https://github.com/shivani-1521/coredns/tree/shivani-1521/plugin/googleCloudDNS)
If its possible, can I continue with this. Sorry for the delayed update. 
@yongtang

**Comment by yongtang** [comment]
We welcome PR in this area!

**Comment by yongtang** [comment]
This issue is part of the Linux Community Bridge and is tracked in PR #3011.

**Comment by maguro** [comment]
Hey guys, sorry about the tardy PR; I had an unanticipated emergency surgery that had me laid up for a while.  As I mentioned earlier, I had already coded things up and I've created a, PR #3030.

It pretty much is in line with what I presented earlier.  Comments and suggestions are most welcome.
