### ISSUE TITLE
When replacing kube-dns with core-dns in kubernetes deployments, nslookup fails with "Got recursion not available" error

### ISSUE THREAD

**Issue by prabhakar-pal** [coredns/coredns#2857]
1. Intent is to  replace kube-dns with coredns in the kubernetes deployment
2. Used the core-dns provided migration script which generates the corefile and the k8s object manifests.
3. Core DNS kubernetes objects were created by applying the generated k8s manifests
4. Deleted the kube-dns deployment
5. Corefile config map extract

    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        log
    }

6. The problem we are facing is nslookup / dig fails after this change

$ nslookup kubernetes.default.svc.cluster.local
;; Got recursion not available from 10.24.0.10, trying next server
Server:		171.70.168.183
Address:	171.70.168.183#53

** server can't find kubernetes.default.svc.cluster.local: NXDOMAIN

$ nslookup -norecurse kubernetes.default.svc.cluster.local
Server:		10.24.0.10
Address:	10.24.0.10#53

Name:	kubernetes.default.svc.cluster.local
Address: 10.24.0.1

Here "10.24.0.10" is the Kubernetes service IP and 171.70.168.183 is the external DNS server

$ cat /etc/resolv.conf
nameserver 10.24.0.10
nameserver 171.70.168.183

**Comment by chrisohaver** [comment]
> nslookup kubernetes.default.svc.cluster.local

From where are you doing this command from?

**Comment by prabhakar-pal** [comment]
@chrisohaver,

- nslookup was invoked  from the kubernetes host. 
- From the logs, we could see that kubernetes plugin translated to the corresponding k8s service IP
- But since the response did not have the "ra" flag  set, nslookup seems to be offended
- But forcibly setting recursion-available flag in kubernetes plugin, the issue goes away but not sure if that is an acceptable solution

**Comment by chrisohaver** [comment]
Do lookups work as expected when making queries from Pods?

**Comment by prabhakar-pal** [comment]
Yes, it does

**Comment by chrisohaver** [comment]
> Yes, it does

OK, good.  Is this issue causing any practical problem for your cluster?

It looks like nslookup on the host is requesting recursion by default, and ignoring the answer from CoreDNS because it does not support recursion.

I assume that when you say "kubernetes host" that means "kubernetes node"  ...  If so, it is concerning that your host nodes are configured to query the cluster DNS IP.  This should be causing infinite forwarding looping problem for external queries.  Since the CoreDNS Pod inherits it's `/etc/resolv.conf` from the host node it's running on, it it will forward any external zone queries to itself ad infinitum.

Can you give more info on your k8s environment?  version, whats the provider, how was it set up, etc...

**Comment by prabhakar-pal** [comment]
@chrisohaver, thanks for your responses:

- This is an on-premise deployment where kubernetes was brought up using kubeadm
-  We are running kubernetes 1.11.5. 
-  The installation / upgrade / monitoring components use nslookup on the host which used to work fine with kube-dns
-  One hack that worked was the  kubernetes plugin setting RecursionAvailable as true because, anyways, for k8s domain (e.g. cluster.svc.local), kubernetes plugin provides the authoritative response and setting RecursionAvailable to true keeps the utilities like nslookup happy

**Comment by chrisohaver** [comment]
AFAIK, kubeadm does not add the cluster DNS to the node's `/etc/resolv.conf` ... so that must have been a manual step afterwards?  Can you do lookups of external zones from Pods in your cluster?

> The installation / upgrade / monitoring components ...

Are those monitoring components custom built?  IIUC, reachability from a host node to Cluster IPs isn't always guaranteed.  Also, FWIW, `dig` is generally preferred for debugging and monitoring over `nslookup`.  `nslookup` has a reputation for acting in strange ways.

 IMO AA != RA, hence they are separate flags.  I think that setting recursion available for an authoritative zone is meaningless, since recursion is only needed to resolve non-authoritative zones.  But i'll defer to @miekg here... @miekg, does it make sense to reply with recursion available for all authoritative zones?

**Comment by prabhakar-pal** [comment]
- Yes @chrisohaver  we manually add the cluster DNS ip to node's /etc/resolv.conf

>>Reachability from a host node to Cluster IPs isn't always guaranteed
-  So far it has been working fine for us 

>> I think that setting recursion available for an authoritative zone is meaningless

- I agree nslookup behaviour in this scenario is weird but was not sure if there is any requirement in spec that is causing this behaviour

**Comment by chrisohaver** [comment]
> we manually add the cluster DNS ip to node's /etc/resolv.conf

When you configured your cluster with kubeadm, did you specify an alternate `resolv.conf` to use, or are you going with the default setting.  If going with the default setting, then kubelet sets up all Pods with the `default` dnsPolicy (e.g. CoreDNS) with the node's `/etc/resolv.conf`, which means that the coredns service IP will be of the upstream servers.  This is obviously problematic for CoreDNS (forwarding loop).  In that configuration, external queries will fail randomly for some time until CoreDNS determines that `10.24.0.10` (itself) is unhealthy (because it will never get a response from itself), and will stop forwarding that way.  This would manifest as "delays" since clients generally retry if a query times out.  After that CoreDNS will continue to waste time monitoring the health of itself.

What problem are you solving by adding the cluster DNS ip to node's `/etc/resolv.conf`?  Perhaps there is a better/safer way to solve that problem.

How does nslookup behave when you specify the cluster DNS ip in the nslookup command... e.g. 

```
nslookup kubernetes.default.svc.cluster.local. 10.24.0.10
```

> I agree nslookup behaviour in this scenario is weird but was not sure if there is any requirement in spec that is causing this behaviour

There are very few details in RFC specs that dictate _client_ DNS behavior.  Each client behaves slightly differently. `Dig` is a great tool for debugging and monitoring DNS, because it does a simple query without any extra "helpful" magic, and it shows a detailed response.  IOW with dig, it's easier to control the precise nature of the request, and the easier to determine the exact form of response.

IMO, we should not alter CoreDNS behavior to always set the RA flag for authoritative domains because, put simply, recursion _isn't_ actually available.  It seems to me that the current behavior follows how the flags are defined in the DNS spec.

**Comment by prabhakar-pal** [comment]
Thanks for your inputs @chrisohaver, they are very valid.
 
>> nslookup kubernetes.default.svc.cluster.local. 10.24.0.10
This works fine.

All the DNS queriees would be forwarded  to coredns and coredns would forward the requests that are not handled by kubernetes plugin to the upstream DNS server. Upstream DNS server IP in host /etc/resolv,conf is useful only when core-dns itself is not up (or when the infrastructure is coming up).

Thanks for your inputs @chrisohaver, will close the issue for now
