### ISSUE TITLE
middleware/kubernetes Update dns schema to support skydns replacement

### ISSUE THREAD

**Issue by aledbf** [coredns/coredns#286]
https://github.com/kubernetes/kubernetes/blob/master/build/kube-dns/README.md

**Comment by johnbelamaric** [comment]
Yeah, we should change the default template to include the {type}. Also, I believe @mrichmon was working on A records for pods.

**Comment by miekg** [comment]
This should be fixed with #359? (That PR needs to be rebased to get rid of the conflicts)

**Comment by chrisohaver** [comment]
My understanding is that this is an over-arching issue to make coredns a drop in >= replacement for skydns.  #359 just addresses one (very simple) item.  Its not clear to me what the full list of TODOs is.
- #359 adds {type} into the default template.
- Also need to add A records for pods to resolve this issue.
- I assume other things need to be done as well.

**Comment by johnbelamaric** [comment]
See here for all the features we need to support: http://kubernetes.io/docs/admin/dns/

**Comment by johnbelamaric** [comment]
@aledbf in order to finalize this one, I put together a more explicit specification for DNS-based service discovery in Kubernetes, based on the docs and on some discussion with @thockin and @bowei

You may want to take a look at it here: https://docs.google.com/document/d/1B4ZA1HwprWMzyT7nUZLAZ93Fjwcdt9qs0aXfifKxpTs/edit#heading=h.ccweo4g1oxg

I will be moving it to a K8s PR probably next week for community feedback. Once that's nailed down then we can finish this issue.

**Comment by johnbelamaric** [comment]
Now it's here: https://github.com/kubernetes/kubernetes/pull/38408
