### ISSUE TITLE
Autopath and Cache vs upstreams

### ISSUE THREAD

**Issue by krzysztof-bronk** [coredns/coredns#2890]
Hello,

I have a question regarding the use of Autopath and Cache plugins in kubernetes.
In one of the recent presentations from Datadog, they mentioned that when they enabled Autopath, their upstreams choked as autopath bypasses or prevents caching. 

Is that statement accurate? What happens exactly?
Are there any other downsides to Autopath, or is it a no-brainer to use it in k8s?

Thanks for all the great work!

**Comment by chrisohaver** [comment]
Using _autopath_ does not prevent caching.

Using _autopath_ does require enabling `pods verified` mode in the _kubernetes_ plugin.  This maintains a watch on all Kubernetes Pods, which causes CoreDNS to use more memory, and puts more load on the Kubernetes API. This could be disruptive on a resource poor large scale cluster. This is why tools such as kubeadm does not enable autopath by default.  Neither of these issues however would have increased load on upstream servers.

_Autopath_ does make upstream queries take less time, because without _autopath_, upstream queries require several failed cluster domain queries first (the standard k8s cluster-first search domains).  With _autopath_, the question is answered in the first query, so the throughput would be increased. If a cluster's Pod lookups are being throttled by the cluster-first search domain bottleneck, then using _autopath_ could increase load on the upstream servers by removing the bottleneck.

**Comment by krzysztof-bronk** [comment]
Thanks for the response!
FYI, here is the excerpt from the (very informative) presentation
https://www.youtube.com/watch?v=QKI-JRs2RIE
Between 3:47 and 5:15
It mentions upstream being rate limited, but it specifically says _autopath prevents caching_

**Comment by chrisohaver** [comment]
Thanks for the link.  If thats true, it's a major bug. It's a recent presentation, and I don't recall an issue being raised with us.  Thanks for bringing it to our attention. I'll look into it.

The presenters don't go into detail there. They are right in that autopath itself does not do it's own caching.  It relies on the cache plugin to cache. If autopath is used without the cache plugin, then there will be no caching.

**Comment by chrisohaver** [comment]
OK - I verified that cache+autopath works in the latest build of master. For my test, I added a debug to log when retrieving from cache.  It shows that the first request for `coredns.io` is not retrieved from cache, and the second one is (response times line up too).

```
.:5398
2019-06-17T11:06:22.071-04:00 [INFO] CoreDNS-1.5.0
2019-06-17T11:06:22.071-04:00 [INFO] darwin/amd64, go1.12, c432f894-dirty
CoreDNS-1.5.0
darwin/amd64, go1.12, c432f894-dirty
2019-06-17T11:06:24.900-04:00 [INFO] [::1]:54897 - 54307 "A IN coredns.io.default.svc.cluster.local. udp 65 false 4096" NOERROR qr,rd,ra,ad 151 0.170248457s
2019-06-17T11:06:27.488-04:00 [INFO] plugin/cache: Retrieving response from cache
2019-06-17T11:06:27.488-04:00 [INFO] [::1]:60932 - 57692 "A IN coredns.io.default.svc.cluster.local. udp 65 false 4096" NOERROR qr,aa,rd,ra,ad 140 0.00012752s
```

**Comment by zendai** [comment]
@krzysztof-bronk I can also confirm autopath plugin and the cache plugin works together (cache plugin will store the result of autopath), I just had a packet dump level analysis a few weeks ago while I was troubleshooting issue [2842]( https://github.com/coredns/coredns/issues/2842).

Indeed @chrisohaver if they ran autopath without the cache plugin, that can result a huge upstream traffic increase, which eventually can hit rate limit. We just had this, we disabled cache to mitigate issue [2842](https://github.com/coredns/coredns/issues/2842) until the new CoreDNS version comes out with the patch, and we had hit the [rate limit](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#vpc-dns-limits) by AWS a few hours later.

So we re-enabled the cache, and waiting for 1.5.1 to be released. For Kubernetes, autopath is a very nice feature to have, especially if you're affected by the [conntrack](https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts) issue, which I assume most people are (if you use iptables, you are). For the conntrack issue, [nodelocaldns](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns) will provide a fairly painless fix, it's in beta now it aims to be GA with Kubernetes 1.15.

**Comment by zendai** [comment]
@krzysztof-bronk I can also confirm autopath plugin and the cache plugin works together (cache plugin will store the result of autopath), I just had a packet dump level analysis a few weeks ago while I was troubleshooting issue [2842]( https://github.com/coredns/coredns/issues/2842).

Indeed @chrisohaver if they ran autopath without the cache plugin, that can result a huge upstream traffic increase, which eventually can hit rate limit. We just had this, we disabled cache to mitigate issue [2842](https://github.com/coredns/coredns/issues/2842) until the new CoreDNS version comes out with the patch, and we had hit the [rate limit](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#vpc-dns-limits) by AWS a few hours later.

So we re-enabled the cache, and waiting for 1.5.1 to be released. For Kubernetes, autopath is a very nice feature to have, especially if you're affected by the [conntrack](https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts) issue, which I assume most people are (if you use iptables, you are). For the conntrack issue, [nodelocaldns](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns) will provide a fairly painless fix, it's in beta now it aims to be GA with Kubernetes 1.15.

**Comment by chrisohaver** [comment]
I'd like to understand what went wrong in the DataDog incident @lbernail recounted.
Perhaps there is a pitfall here that we could be steering people away from.

**Comment by lbernail** [comment]
@chrisohaver I just verified and we indeed disabled caching when we enabled autopath (I'll try to find out why), so it looks like the root cause was wrong.

This setup should be fine?
```
    cluster.local:53 {
      autopath @kubernetai

      kubernetai {% env "CLUSTER_DOMAIN" %} {% env "SERVICE_CIDR" %} {
        pods verified
      }
      proxy . /etc/resolv.conf
      cache
    }
```
In that configuration, the cache directive only applies to queries sent upstream?

I probably won't be able to test on our larger clusters because `pods verified` is too expensive so we are now changing the Kubernetes DNS behavior to use ndots=2 and a single search domain (`svc.cluster.local`). We also use a local coredns resolver (daemonset) to decrease the load on the coredns servers. More details here: https://youtu.be/MvoImel5qfc?t=1664

**Comment by chrisohaver** [comment]
Thanks for clarifying, @lbernail.

Going forward, I think the autopath plugin will be short lived in CoreDNS (at least in conjunction with Kubernetes), because it doesn't work gracefully with the architecture of nodelocaldns, which looks like it may become a standard Kubernetes deployment. There is an alternate "autopath" solution proposed that fits better into nodelocal dns https://github.com/kubernetes/enhancements/pull/967.  But it's still here for now... 

> In that configuration, the cache directive only applies to queries sent upstream?

IIUC, it would do the opposite.  The order of plugins within a serverblock does not matter in CoreDNS (generally).  The cache plugin in your example only handles the `cluster.local.` zone, because that is the zone of its server block `cluster.local:53 {...}`.  Its position being after the proxy plugin makes no difference.

The following should work ...

```
    .:53 {
      autopath cluster.local @kubernetes
      kubernetes cluster.local {
        pods verified
      }
      proxy . /etc/resolv.conf
      cache
    }
```

... this would cache both cluster.local and upstream zones.  For various reasons, there isn't a way to cache just upstream zones and not the cluster zone, AND use autopath at the same time.

**Comment by krzysztof-bronk** [comment]
Thanks everyone for clarifying this so quickly, I'll certainly try this combination out as soon as 1.5.1 rolls out (due to #2842).

**Comment by lbernail** [comment]
OK I think I have more context:
- the default records in a zone managed by the kubernetes plugin are: TTL:5s, NTTL: 300s
- the cache plugin default for NTTL is 1800s
- so enabling cache on a zone managed by the kubernetes plugin meant a NTTL of 300s which was long for new services

For this reason we had:
- no cache on the kubernetes zone
- caching for the default upstream

When we enabled autopath, we did not enable caching on the kubernetes zone which lead to the issue we mentioned in the talk (sudden increase in queries to upstream which lead to rate limiting)

Ideally, as @chrisohaver mentioned, it would be nice to be able to only cache proxied query when using autopath (but it does not seem possible)

Another option that would have probably worked for us was to configure cache with a much more aggressive NTTL (5-10s?)

**Comment by chrisohaver** [comment]
As of coredns 1.3 (iirc), the TTL of negative responses for kubernetes records was fixed to match positive responses (by default 5s, but configurable).

**Comment by lbernail** [comment]
We were indeed using `1.2.6`

**Comment by chrisohaver** [comment]
Around 1.3ish, If you set ttl to zero in kubernetes it prevents caching of kubernetes records.  Side effect of course is that the record ttls are zero, which for the common case, should not cause problems for a client, but dns clients can be finicky.
