### ISSUE TITLE
DNS cannot be resolved

### ISSUE THREAD

**Issue by system51** [coredns/coredns#2916]
When reporting bugs and requesting assistance, please include：
* the version of CoreDNS you are using
1.2.6

* your Corefile：
I think I have deleted it.

* logs, if applicable：
I have rebuilt DNS by deleting Pod and can't query logs.I think it may be the BUG left by the version. Is this possible?

**Comment by chrisohaver** [comment]
@system51, The Corefile is the CoreDNS configuration file.  
I'm assuming you are using CoreDNS in Kubernetes because you mention "Pod".
In Kubernetes, The Corefile is in the `coredns` Configmap in the `kube-system` namespace.

Questions:
* How are you attempting to get logs?  And what is the error you get?
* What is the status of the coredns Pods?
* Are you testing DNS from a node, or a Pod?
* What name are you querying?
* What tool are you using to test? (e.g. dig?)
* What result do you get?
* What result do you expect?
