### ISSUE TITLE
plugin/nsid: nsid not being set

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#2980]
Neither the default nor any other value is being set via nsid.

Tested with the following config:
```
. {
  forward . 8.8.8.8
  errors stdout
  log
  nsid test
  cache
}
```

```
. {
  forward . 8.8.8.8
  errors stdout
  log
  nsid
  cache
}
```

```
. {
  forward . 8.8.8.8
  errors stdout
  log
  nsid {$HOSTNAME}
  cache
}
```

Result:
```
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; NSID
```

**Comment by sharmaansh21** [comment]
I can look into it :bowtie:

**Comment by stp-ip** [comment]
The culprit seems to be the cache, which might seem intentional. So debugging queries should probably not be cached and separated into their own stanza. Not sure, if this needs a fix.

**Comment by stp-ip** [comment]
Another workaround is to have a separate stanza that forwards back to the main stanza (which still can have the cache).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] [nsid] nsid n..." ]
>The culprit seems to be the cache, which might seem intentional. So debugging queries should probably not be cached and separated into their own stanza. Not sure, if this needs a fix.

nsid is there to identify the server answering your query. This was never 
designed to be cached or survive being forward. If anything we fail to add
our own nsid when replying?

**Comment by stp-ip** [comment]
So from the preliminary testing it is as follows:
nsid + cache: on first request it includes the nsid
nsid + cache: on cached responses it doesn't respond with the nsid (this seems like a bug)
nsid + no chache: nsid works as expected

To workaround this issue one could do:
```
.:53 {
  bind 127.0.0.1 # gets traffic here
  bind 127.0.0.2
  forward . 8.8.8.8
  cache
}
nsid.example.com:53 {
  forward . 127.0.0.2
  nsid
}
```
That way nsid adds its response to the cached items as well.

**Comment by miekg** [comment]
Might be an indication of something deeper going on with OPT

**Comment by stp-ip** [comment]
My guess would be cache stripping any data it deems unnecessary and nsid isn't in the path, when it responds, but that's a bad hunch. Hopefully can dive into the code soon, if @sharmaanshul21 hasn't jumped in :)

**Comment by sharmaansh21** [comment]
Not yet, please go ahead.

**Comment by stp-ip** [comment]
Will let you know, once I got some time to work on it.

**Comment by miekg** [comment]
is this still a thing?

**Comment by erbesharat** [comment]
Yeah, the bug still exists. I tried to find what is causing the problem and I think NSID doesn't work with the cache plugin, because while creating the item to store it in the cache, the EDNS would get skipped but other extra sections would get added to the item.
https://github.com/coredns/coredns/blob/f81f28d97b3987b07f53847ee63097ac05d518b9/plugin/cache/item.go#L35-L37
I'm not sure if it's the actual reason so I thought it's better to ask about it before creating a PR. CC: @miekg

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/nsid: ..." ]
>Yeah, the bug still exists. I tried to find what is causing the problem and I think NSID doesn't work with the cache plugin, because while creating the item to store it in the cache, the EDNS would get skipped but other extra sections would get added to the item.
>https://github.com/coredns/coredns/blob/f81f28d97b3987b07f53847ee63097ac05d518b9/plugin/cache/item.go#L35-L37
>I'm not sure if it's the actual reason so I thought it's better to ask about it before creating a PR. CC: @miekg

I don't see how that can be the case (but I may be wrong). I.e. nsid plugin becomes before
the cache plugin, and IIRC that would just add an nsid identifier to whatever flows by. So
the question is: why is the nsid plugin not processing responses from the cache plugin?

**Comment by erbesharat** [comment]
@miekg I think that code is causing the problem because when I comment it all the responses would have the EDNS0 section. But when it's not commented, the first response would return EDNS0, but after being cached it would get removed from the response. 

Logs when it's not commented (`res.Extra` logged in NSID's WriteMsg method):
![image](https://user-images.githubusercontent.com/7544732/72421511-e29fce00-3795-11ea-9507-7537fb6d5e6f.png)

**Comment by stp-ip** [comment]
My reasoning:
The nsid plugin comes before cache so wouldn't add anything to cached responses.
On the first response nsid is still added due to the response not coming from the cache.
On subsequent responses nsid is not added and the cache item doesn't contain EDNS0 extras so won't have the nsid.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/nsid: ..." ]
>My reasoning:
>The nsid plugin comes before cache so wouldn't add anything to cached responses.
>On the first response nsid is still added due to the response not coming from the cache.
>On subsequent responses nsid is not added and the cache item doesn't contain EDNS0 extras so won't have the nsid.

but that's working as intended, i.e. don't cache edns0 (and certainly not nsid). nsid is
hop-by-hop, but it *should* be added backin if the cache is replying.  (I'm avoiding to
looking at the code, because $otherStuff, but I don't understand why nsid isn't doing this
for this particular case)

**Comment by erbesharat** [comment]
Well, when the response comes back from the cache it doesn't have the EDNS0 section and as far as I understood NSID only gets added to the response if it has the EDNS0 section:
https://github.com/coredns/coredns/blob/0930eb8beb69684dfb1e1e066e2a7a6ed3827bf4/plugin/nsid/nsid.go#L40

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/nsid: ..." ]
>Well, when the response comes back from the cache it doesn't have the EDNS0 section and as far as I understood NSID only gets added to the response if it has the EDNS0 section:
>https://github.com/coredns/coredns/blob/0930eb8beb69684dfb1e1e066e2a7a6ed3827bf4/plugin/nsid/nsid.go#L40

ah, that makes sense, then nsid is not doing the right thing because i needs to check the
query
