### ISSUE TITLE
Using CIDR notation it accepts queries outside range

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#2981]
It seems like we are accepting requests outside of the CIDR range.
Afaik we should only accept  IPs between 127.0.0.0 and 127.0.0.255 at the most.

Sidenote: This probably happens as from a pure DNS perspective, after we translated /24 it is converted into the zone `0.0.127.in-addr.arpa`, but this feels problematic.

```
127.0.0.0/24 {
  whoami
}
```

```
$ dig 999999.0.0.127.in-addr.arpa @127.0.0.1

; <<>> DiG 9.14.3 <<>> 999999.0.0.127.in-addr.arpa @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41077
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 3
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: b60a8e167172aabe (echoed)
;; QUESTION SECTION:
;999999.0.0.127.in-addr.arpa.	IN	A

;; ADDITIONAL SECTION:
999999.0.0.127.in-addr.arpa. 0	IN	A	127.0.0.1
_udp.999999.0.0.127.in-addr.arpa. 0 IN	SRV	0 0 51272 .

;; Query time: 0 msec
;; SERVER: 127.0.0.1#5354(127.0.0.1)
;; WHEN: Fri Jul 05 08:26:15 UTC 2019
;; MSG SIZE  rcvd: 153
```

**Comment by miekg** [comment]
This is attempted in #2783

**Comment by chrisohaver** [comment]
I believe @stp-ip is highlighting a related, but different issue.

IIUC, this is caused by this optimization ...
https://github.com/coredns/coredns/blob/master/core/dnsserver/register.go#L81

Which skips adding the cidr validation filterfunc if the mask length is a multiple of 8.
The optimization makes sense, since any valid ip coming in through the rounded off zone will always be in the cidr, so no need to check it (they are the same).
However without the filter, it will accept anything under that zone, including invalid IP addresses, as in the example.  

This is exactly how it works when you specify the reverse zone in the Corefile instead of a cidr.  I don't think this is in itself a problem.  `999999.0.0.127.in-addr.arpa` is in the zone `0.0.127.in-addr.arpa`, so it makes sense that it gets routed that way.

When the filter is active, invalid IPs are rejected because the requested IP address cannot be parsed. https://github.com/coredns/coredns/blob/master/core/dnsserver/register.go#L88, `IPnet.Contains` presumably would return false.

The concern that @stp-ip raises, I think, is that the behavior differs for CIDR masks of a multiple of 8 vs other lengths.
For masks on 8 bit boundaries: no IP validation is done
For masks not on 8 bit boundaries: IP validation is done (by the filterfunc)

**Comment by stp-ip** [comment]
Question is do we see it as reasonable to do IP validation or is that something out of scope due to the general reversing being correct and anything under that reversed zone being valid?

That the behavior differs shows that we haven't figured out, what should be the correct way.

**Comment by chrisohaver** [comment]
IMO, since this only affects invalid ip lookups, the severity is greatly reduced.  I think handling invalid ip lookups is a pretty obscure corner case, so I don't think it's worth the extra parsing/validation step for every incoming reverse zone query to handle them consistently for all mask lengths.
But for the sake of discussion, to be consistent we would either ...

_always validate_: which adds an additional IP string parse to each incoming reverse zone query. could be done a separate plugin.
_or never validate_: which will get tricky in the filterfunc (maybe could replace invalid octets with zeros before parsing to IP - "127.0.banana.10" becomes "127.0.0.0" before parse and mask check).

In either case, it's extra processing steps that are only there to make invalid IP queries act in a consistent way. So, IMO probably not worth doing.

**Comment by stp-ip** [comment]
At the very least we should document inconsistencies and that IPs are not validated, which as we agree is fine, just might not be intuitive.

**Comment by chrisohaver** [comment]
Something like ...

"When using standard `arpa` zone notation, IPs in a request are not validated. A side effect of using CIDR notation is that IPs in a request _will_ be validated when checking CIDRs that do not fall an 8 bit boundary (e.g. for IPV4: /8, /16, /24, /32).  For example a reverse lookup of `10.0.0.9999` would be routed to the CIDR `10.0.0.0/24` despite being an invalid IP address.  However `10.0.0.9999` would _not_ be routed to the CIDR `10.0.0.0/21` because `10.0.0.9999` fails IP validation."

**Comment by miekg** [comment]
dup of #2981
