### ISSUE TITLE
plugin/template Respond for zone match and regex mismatch?

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#3034]
```
.:5053 {
      template IN PTR in-addr.arpa {
        # 1.0.0.127.in-addr.arpa
        match "^(?P<a>[0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])[.](?P<b>[0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])[.](?P<c>[0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])[.](?P<d>[0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])[.]in-addr[.]arpa[.]$"
        answer "{{ .Name }} 86400 IN PTR {{ .Group.d }}-{{ .Group.c }}-{{ .Group.b }}-{{ .Group.a }}.net.example"
      }
}
```

It seems currently we don't respond to anything that matches the zone, but not the regex.
Shouln't we at least SERVFAIL?

Usually `fallthrough` + forward will lead to a NXDOMAIN, but this feels like an unhandled case here, but could just be my thinking.

**Comment by chrisohaver** [comment]
I think either a NODATA or NXDOMAIN response would be closer to "correct" than SERVFAIL.  But automatically determining the right kind of negative response would be hard - I think it would require parsing the regex itself to determine all valid sub domains - which is perhaps theoretically possible but impractical. 

I think in the "spirit" of _template_, we might want to introduce a new option, "default", which allows the user to control the response code when the query does not match. e.g. 

`default ( NXDOMAIN | NOERROR | SERVFAIL )`

**Comment by stp-ip** [comment]
I think we should default to SERVFAIL at least and giving the user the option with default would be an additional iteration. Currently we seem to just not respond at all.

**Comment by chrisohaver** [comment]
Ironically, IIUC SERVFAIL would never be the actual desired answer in any given single case.  NXDOMAIN would sometimes be the desired answer, as would NODATA sometimes be the desired answer. But since we cant be sure which is the correct answer, then I suppose SERVFAIL "works".

We could return NODATA for any queries that match the zone exactly but doesn't match the regex. This is technically correct if we assume that a plugin claiming to be authoritative for a zone actually is.

**Comment by johnbelamaric** [comment]
If there is a subdomain, then parent domains should not return NXDOMAIN for themselves, right? So for example, if: `a.b.c.com` exists this implies a query for explicitly `b.c.com` or `c.com` should also not return NXDOMAIN. What that means, is that with template the user can always construct a set of regex that "create" subdomains but not the parent domains. That means that `default NXDOMAIN` would be wrong in some cases with those sets of regex. 

This is annoying. The question is whether we can determine all the parent domains implied by the set of regex and ensure they return NODATA if there is no match for them. I suspect that is impossible and that the plan should be:

1) Add the default option as described
2) Add some best practice docs recommending how to construct templates that create valid data.

Maybe there is some feature we can offer to make #2 easier?

**Comment by yelhouti** [comment]
I think you guys are facing the same problem I have, could you cinfirm please?
I have an etcd entry with key: /skydns/com/example/demo/45642
when I dig for example.com it returns the the localIP (instead of moving to the next block that forwards)
should I create a new issue or is this what you guys are discussing?

**Comment by m-yosefpor** [comment]
> 1. Add the default option as described

It seems you all @stp-ip @johnbelamaric @chrisohaver 
agree with adding this option.

Shalll I create a PR for this?

**Comment by chrisohaver** [comment]
@m-yosefpor Are you still interested in implementing this?

**Comment by chrisohaver** [comment]
@m-yosefpor, I opened a PR for this, after looking into it, I think my conclusion that we should add a new option was wrong.

I now think SERVFAIL is the right thing to do here.  See #5180 for my reasoning.
