### ISSUE TITLE
plugin/kubernetes: Support serving records for nodes

### ISSUE THREAD

**Issue by erikwilson** [coredns/coredns#3077]
## Feature Request

Please support an option for serving node records through the kubernetes plugin. 

https://kubernetes.io/docs/concepts/architecture/nodes/#addresses

The kubernetes plugin should be able to serve a record for every node Hostname, preferably the InternalIP but optionally the ExternalIP.

Currently this can be achieved with an external controller to watch node changes and updating a config map linked to by the hosts plugin, but it would be helpful for this functionality to be built into the kubernetes plugin.

**Comment by chrisohaver** [comment]
If done, To avoid name collision with the existing internal fqdn schema, the internal fqdn of a node could be `<node-hostname>.node.<cluster-zone>` e.g. `foo.node.cluster.local.`.  

ExternalIPs probably would be better exposed by the _k8s_external_ plugin, producing records using the same schema, e.g. `foo.node.mydomain.com.`.

I recall this has been requested/suggested/discussed before.

**Comment by erikwilson** [comment]
Sorry if a similar issue already exists, I thought one would exist so took a quick look at issues opened & closed but couldn't find anything.

Yah I agree putting the ExteralIP off to another plugin or not dealing with it is fine, however I need DNS entries for an unmodified Hostname rather than a FQDN. The reason being that some kubernetes projects depend on the node name resolving, such as metrics-server. For example, if I don't provide a hosts entry for the nodes then metrics-server will produce the following error when scraping for metrics:
`
E0801 14:31:41.074784       1 manager.go:111] unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:k3s-1: unable to fetch metrics from Kubelet k3s-1 (k3s-1): Get https://k3s-1:10250/stats/summary/: dial tcp: lookup k3s-1 on 10.43.0.10:53: no such host, unable to fully scrape metrics from source kubelet_summary:k3s-2: unable to fetch metrics from Kubelet k3s-2 (k3s-2): Get https://k3s-2:10250/stats/summary/: dial tcp: lookup k3s-2 on 10.43.0.10:53: no such host]
`
If it was just for me I would say FQDN is fine, but I need this to support the behavior of other projects. Perhaps having fqdn/hostname behavior as an option, or resolving the node hostname as a fall through, could help support the functionality I need without causing conflicts or collisions.

**Comment by chrisohaver** [comment]
No worries, it may have been in one of the kubernetes repos.

Actually, the name scheme I suggested doesn't work well because of the search domain list given to pods in k8s, which looks like ... 
```
search namespace.svc.cluster.local  svc.cluster.local  cluster.local ...
```

If the name scheme was `<node-hostname>.<cluster-zone>`, then the node record would be found in the 3rd search domain.

So, assuming we implement node recrods that way, and assuming that the metrics server uses the `ClusterFirst` DNS policy, `https://k3s-1:10250/stats/summary/` would actually resolve `k3s-1` to `k3s-1.cluster.local.`, after trying `k3s-1.namespace.svc.cluster.local` and  `k3s-1.svc.cluster.local` ...

Thats where the name collision comes in, because `k3s-1.namespace.svc.cluster.local` could actually be the name of a service named `k3s-1` in the namespace `namespace` (In which case the metrics-server would use that service's IP).

**Comment by erikwilson** [comment]
Thanks for the context, I think using `<node-hostname>.node.<cluster-zone>` would be good, and adding `node.<cluster-zone>`, and then I am guessing one could configure coredns with something like:
```
        kubernetes node.cluster.local cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
```

**Comment by erikwilson** [comment]
Or rather, it looks like the kubernetes/autopath code would need to be updated? I think the node needs to take priority in the search path, am willing to take a stab at making the change if needed, have lots of other things to do tho and am happy to let someone else that knows the code better implement :)

**Comment by chrisohaver** [comment]
> Thanks for the context, I think using <node-hostname>.node.<cluster-zone> would be good, and adding node.<cluster-zone>

That would only work if the applications uses fqdns, which apparently, metric-server does not.
To support that schema, `node.cluster.local` would need to be in the search domain list of /etc/resolv.conf in the Pod.  That is controlled by kubelet, not CoreDNS.

You could create a local domain on the node for `node.cluster.local.`, this would cause kubelet to create a search list with that at the end of the list... e.g. 
```
search namespace.svc.cluster.local  svc.cluster.local  cluster.local node.cluster.local
```

This is still subject to the name collision issue,  because `namespace.svc.cluster.local` is searched first, and would return a service IP if a service exists with that name.  In fact, the external controller solution is also subject to the same name collision issue.

**Comment by chrisohaver** [comment]
> Or rather, it looks like the kubernetes/autopath code would need to be updated? I think the node needs to take priority in the search path, am willing to take a stab at making the change if needed, have lots of other things to do tho and am happy to let someone else that knows the code better implement :)

autopath is an optional feature... It's intended to mimic the way clients actually do queries, and do them on the client's behalf.  Making it act differently from the way clients behave is probably not a good idea.

**Comment by miekg** [comment]
to rain on your parade: this probably needs an update in the DNS specification, before we even attempt to write code: https://github.com/kubernetes/dns/blob/master/docs/specification.md

**Comment by chrisohaver** [comment]
>to rain on your parade: this probably needs an update in the DNS specification, before we even attempt to write code: https://github.com/kubernetes/dns/blob/master/docs/specification.md

Not if it's an optional feature.  We already do things that are not in the spec...

**Comment by chrisohaver** [comment]
Another way to do this, without any CoreDNS changes is to use the name collision issue to our advantage, creating headless services with endpoints that point to the node ips...

**Comment by erikwilson** [comment]
To be honest I have not been too concerned about the name collision issue as it is largely seems like an admin config problem. I think a sensible default should be provided (node first) with an option to change the search path if not already available.

**Comment by miekg** [comment]
we've grandfathered in some stuff from the past; update the spec

**Comment by chrisohaver** [comment]
I think creating records as`<node-hostname>.<cluster-zone>` is the least obtrusive. This doesn't require search path extension, which is problematic because it touches more parts out side of CoreDNS.  

However, it's probably not going to be allowed to merge here.

You could instead create an external plugin that accomplishes this that sits in the plugin chain just before kubernetes.  It would maintain an API watch on nodes, and resolve any queries that match the node ... then passing along queries to the next plugin (kubernetes) if nothing matches.

**Comment by erikwilson** [comment]
Another idea (probably a bad one, just throwing it out there) might be to leverage the pod hostname spec and create some default entries, like `k3s-1.default.default.svc.cluster.local`, and then search that first.

**Comment by miekg** [comment]
> However, it's probably not going to be allowed to merge here.

annoying when people put words in my mouth...

@erikwilson 
Have a discussion on the DNS spec to see if such a big change is desirable and I'm happy to merge any changes. (creating an entire new namespace next to svc and pod is a big change)

**Comment by erikwilson** [comment]
I agree that creating default subdomain entries is maybe not a good idea, and I would rather avoid changing the spec if possible or holding up a solution until some spec is fleshed out. 

Instead of service discovery I see this as providing basic node hostname resolution. 

If projects like metrics-server are operating outside of the spec that is a larger discussion for the kubernetes community, but I was hopeful this wouldn't need to be spec'd out as an opt-in and configurable feature.

**Comment by chrisohaver** [comment]
Wasn't trying to put words in mouths.

I agree that if this is intended to be a standard feature that would work for everyone, then it needs to be discussed in the k8s dev circles first (sig-network in particular).  

For an optional one-off deployment, it could be handled with an external plugin as described above, which would have less moving parts than the external controller solution that @erikwilson is using now.

**edit**: While thinking about this issue, I lost track of the fact that @erikwilson already has a one-off solution, and was in fact looking to add this as a standard part how kubernetes DNS works.

**Comment by stp-ip** [comment]
Generally? `<hostname>.node.<cluster-zone>`

But agreed this needs discussion with sig-network first.

**Comment by chrisohaver** [comment]
> But agreed this needs discussion with sig-network first.

I seem to recall it was discussed at some point - perhaps in the context of kube-dns.  But I cant seem to find the discussion in kubernetes repos either.  Maybe I dreamed it. Perhaps @johnbelamaric remembers.  I do remember discussing this verbally with John a long time ago.

I think whatever the solution, applications like metrics-manager should not rely on the clusterFirst search list to resolve a node short name to a fqdn, since enabling that in the search list would result in name eclipsing (it would eclipse a service of the same name, or it would be eclipsed by that service, depending on the order of search domains).

**Comment by johnbelamaric** [comment]
Yeah, it was discussed but never seriously. Anything that adds to the search list is a non-starter as far as I am concerned.

I think the community may be open to adding the `node` subdomain. We also discussed long long ago completely doing a `v2` schema, which would swap type and namespace: `<name>.svc.<namespace>.<cluster>` for example. But of course nodes are not namespaced so then you have a possible conflict if you do `<name>.node.<cluster>` if some *(#@% names a namespace `node`.

Anyway...happy to have this discussion on the spec. But for a quick fix I think @chrisohaver's suggestion of headless service with static endpoint is quickest. No code changes needed at all...but it would be namespaced.

**Comment by erikwilson** [comment]
I am not looking for quick, I am looking for right, but also flexible. Not sure how this isn't already a solved thing. I don't think that headless is the right way to go because, well, what are the default values? It is a little confusing what the headless spec encompasses, because it looks a lot like the pod hostname docs (https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods) use the same format. I am guessing the DNS spec was created for https://kubernetes.io/docs/concepts/services-networking/service/#headless-services but adopted by other stuff later.

At the risk of invoking people who don't care I am going to ping @DirectXMan12, besides metrics-server I am not sure what other projects might follow the scheme of addressing nodes by hostname. Maybe a whole new plugin & scope is needed to avoid conflicts, but it would be nice to have an intermediate solution until everyone could move to a non-conflicting solution.

**Comment by johnbelamaric** [comment]
The spec was reverse-engineered from kube-dns (so we could replace it with CoreDNS...).

Probably the right place to start is with an issue in k/k (or k/dns) and a discussion on the sig-network mailing list.

**Comment by chrisohaver** [comment]
The headless service per namespace per node idea requires that those services be created/deleted when nodes are added/removed from the cluster.  This requires some kind of controller to be automated.  A problem with that solution would be how to handle what to do if a service already exists with the same name.

The issue with all solutions discussed in this issue, is that hostname lookups would be ambiguous.  Due to the clusterFirst search path currently in Kubernetes, it is assumed hostname lookups are intended for a service in the same namespace (e.g. `hostname.default.svc.cluster.local.`). If a service doesn't exist then the client eventually tries the bare `hostname.` domain, which would probably never result in anything useful.  IOW, in Kubernetes DNS arch, hostname lookups are intended to be a short cut for service lookups in the same namespace.

If we add a `node` domain along side `svc` and `pod`,  then to enable hostname lookups of nodes, we'd need to add a `node.cluster.local` somewhere in the clusterFirst search list.  This list is already long, and is a pain point for essentially adding latency to external domain lookups for apps that don't fully qualify their name lookups (the experimental _autopath_ plugin was introduced to reduce that latency).  Adding one more element to the list would probably not be welcome (as @johnbelamaric says, a non-starter).  For the sake of discussion, if it were to be welcomed the choice would have to be made to add it before or after the `svc.cluster.local` in the clusterFirst search list.  If before, nodes would eclipse services for hostname lookups, which could break existing deployments.  If after, a service could eclipse a node hostname lookup.

If we don't add a `node` domain, and just place the nodes at the `cluster.local.` level, e.g. `master-0.cluster.local.`, then we would not need to modify the existing clusterFirst search list.  This avoids the concerns of lengthening the search list, but does not avoid the problem of services eclipsing nodes of the same name.  It also places extra domains below `cluster.local.` level, which could have implications (though I think of any concerning ones now).  e.g. If you named a node `pod` or `svc`, then we'd be placing records at these already exiting (record-less) domains.  The k8s dns spec doesn't say they need to be record-less, but there could be some other implication I'm not seeing right now.

Another way to approach this would be to create a new node-watching plugin that replicates what @erikwilson's controller is doing.   It would act like the _hosts_ plugin, but instead of reading hosts from a file, it would establish a node watch with the k8s api, and create entries for each node at the base domain (e.g. `node-1.` `node-2.`).  This still has the issue of nodes being eclipsed by services of the same name in the client's namespace, but leaves the `cluster.local.` domain unmarred.

I do agree with what I think @miekg is saying about the K8s DNS spec.  Any feature that we add to CoreDNS that would routinely be used in a Kubernetes context, should be vetted by the Kubernetes arch teams/sigs before we add them.  This could mean extending the spec to include some "MAYs". Currently it consists mostly if not entirely of "MUSTs", and adding more "MUSTs" would render kube-dns non-compliant (time to deprecate kube-dns?).  Spec changes or no, at least it would involve discussing the feature with the appropriate Kubernetes SMEs.  Definitely for anything that alters the behavior of searches in the cluster domain (e.g. `cluster.local.`), and perhaps less formally for non cluster domain things (e.g. the _k8s_external_ plugin for which members of sig-network contributed to discussions on how that plugin would work, iirc). 

**Side Note**: This ambiguity/eclipsing issue already exists for some corner cases, when you consider non-fqdn domains - e.g. `google.com` vs `google.com.`, the former is not an fqdn (no trailing dot). If there exists a service named `google` in the `com` namespace, you wont be able to look up `google.com` (due to the second domain in the cluster first search list `svc.cluster.local`).

**Comment by erikwilson** [comment]
Considering the complications of using `cluster.local` I am curious if it would be better to use something else entirely, like `node.local` for the node entries. 

With not wanting to change the search list it sounds like this should be a new plugin that can fallthrough to kubernetes.

**Comment by chrisohaver** [comment]
> I am curious if it would be better to use something else entirely, like node.local for the node entries.

Yes, it could work, but it would not enable hostname lookups for nodes (e.g. metrics-server would have to modify how it constructs the fetch urls for nodes).

**Comment by erikwilson** [comment]
The idea is that I have a k8s-node plugin running and I can configure it to resolve the hostname directly or append some arbitrary domain to it. So the plugin would be able to resolve `some-node` or `some-node.node.local`, and eventually when the community agrees on whatever standard the domain should be and all projects are updated then disable the bare hostname lookup.

**Comment by DirectXMan12** [comment]
context on metrics-server:

it tries to follow whatever's listed in the "hostname" field of the node, and assumes that's resolvable and routable (unless you override the address preferences), *attempting* to mimic the behavior of the apiserver connecting to nodes for stuff like logs forwarding.

I'm not super-involved in metrics-server anymore, but it seems like getting sig-network and/or sig-node to agree on whether or not there are guarantees around being able to use the hostname field consistently on nodes seems reasonable to me.

**Comment by johnbelamaric** [comment]
So, the assumption metrics-server is making, based on how apiserver behaves, is that it is not using the cluster DNS to lookup nodes to connect to. Running metrics server as an ordinary pod violates that assumption.

**Comment by erikwilson** [comment]
To be fair, there are a lot of assumptions made all around.

k3s makes the assumption that it is unnecessary for the admin to go through the burden of ensuring the host network is capable of resolving all node hostnames by modifying kube-apiserver to accept a reverse tunnel that contains that information on connection.

If all of this information is already available in kubernetes I don't understand why you wouldn't want to make it available in cluster.

**Comment by johnbelamaric** [comment]
I don't have any problem with doing it. The point was just that you won't get the effect you want because of the search path issue.

**Comment by erikwilson** [comment]
Sorry, I don't think I have made my point clear enough. There should be an intermediate solution capable of accepting both bare hostnames and hostname + arbitrary domains. When/if the sigs agree on the path to use then disable bare hostname.

**Comment by johnbelamaric** [comment]
Yes, that could work. I am a little wary of adding yet another option to k8s plugin, this may be better as a separate plugin. We don't currently watch nodes. Although...for managing headless services [topology-aware routing](https://github.com/kubernetes/enhancements/pull/640)we would need to.

I wonder if there is a way to decompose k8s plugin. Maybe too hard.

So, options are:

1) Separate plugin, sharing the k8s API client connection with k8s. k8s_external does this via an interface implemented by k8s. But in that case we still need an option in k8s to twiddle whether or not to watch nodes

2) Separate plugin, but replicate all the k8s connection stuff...ewww.

3) Option on k8s. I would suggest something like `nodes [ DOMAIN ]`. By default DOMAIN is `node.<cluster-domain>`, but the user could set it to whatever (including `.`). If the option is set, we watch nodes, o/w we don't.

I lean to 3).

**Comment by chrisohaver** [comment]
> By default DOMAIN is `node.<cluster-domain>`, but the user could set it to whatever (including `.`)

@johnbelamaric, To support `.`, _kubernetes_ would need to listen to `.` in addition to `cluster.local`, which would require `fallthough .`. This would spam upstream servers with cluster zone lookups, adding latency). 
I think as a separate plugin, listening to a zone (which could be `.` with a `fallthrough`) would fit more squarely.

As far as replicating k8s connection stuff, or moving said stuff to `plugin/pkg` and sharing, or sharing api connection like _k8s_external_: This is mostly an internal code structuring decision.  I lean toward "interface + node twiddling" in _kubernetes_, but I think exposing/sharing k8s connection stuff would be OK too.

I can take a stab at this if I get a green light.

**Comment by johnbelamaric** [comment]
Ok, good point. Let's go with a separate plugin then!

**Comment by Sh4d1** [comment]
Any progress on this issue?

**Comment by chrisohaver** [comment]
@Sh4d1, It's a new feature request, which afaik, has not been started.
There is not yet a voiced consensus on how to approach it.

**Comment by Sh4d1** [comment]
@chrisohaver okay, I thought somebody had started it already 😅

**Comment by chrisohaver** [comment]
For those interested,  See #3863, a proposed implementation of this as a separate plugin.

**Comment by miekg** [comment]
An external plugin doing something like this seems a likely solution, closing here.

**Comment by chrisohaver** [comment]
WIP external plugin for this: https://github.com/chrisohaver/kubenodes

**Comment by linwalth** [comment]
Hello! What is the current state of this? 
The plugin and coredns kubeapi have not seen commits in a while, so i just want to know if this has been ported upstream or if it is derelict, as I am in a situation where I would profit from such a solution :)

**Comment by linwalth** [comment]
I would be in need of a solution for this, too.

**Comment by chrisohaver** [comment]
> I would be in need of a solution for this, too.

https://github.com/chrisohaver/kubenodes
