### ISSUE TITLE
BIND like 'views'

### ISSUE THREAD

**Issue by wayneshow** [coredns/coredns#3095]
If there is intelligent resolution, such as **view** of bind, I can assign different zone files according to the DNS requests of different source addresses.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] intelligent resol..." ]
>If there is intelligent resolution, such as **view** of bind, I can assign different zone files according to the DNS requests of different source addresses.

no, we don't support views as this is never the correct thing to do. Just run 
multiple CoreDNS instances.

/label: question

**Comment by wayneshow** [comment]
@miekg I think this feature is very common ，as a DNS server,  different clients will be assigned different resolution records when request  one domain name resolution.
Also, how to implement multiple CoreDNS instances.

**Comment by miekg** [comment]
it's not very common and most newer dns servers don't implement this.

you need to start two different coredns processes and use the bind plugin to bind them to certain interfaces

**Comment by yongtang** [comment]
@wayneshow Configuration wise I think view really adds unnecessary complexity for a DNS server. 

If you want to have a response policy tied to source IP you could easily write a plugin for that, see:
https://github.com/coredns/demo

**Comment by glasgow** [comment]
I know this is closed, but for what it's worth, the usual use case for views is split DNS, and split DNS is staggeringly common.  Tons of companies from the smallest to the largest run split DNS.  To imply otherwise is misleading.  The use case is common; if the feature (views) is not, it's only because other DNS servers provide an alternative implementation to address the use case.  Also, running another instance only gets you half-way there.  You still need some kind of policy driven routing to get the requests to the right instance.

**Comment by yongtang** [comment]
@glasgow I think the use case of split DNS can be achieved through golang implementation mentioned in the link  https://github.com/coredns/demo above?

It does require some golang background but otherwise the whole plugin is about 80~100 lines of code and can be packaged as an external plugin. (And external plugins were meant to be served for use cases not wide enough to the community).

I think one of the the concern with views is the maintainability of view's configuration strategy, which was in the original discussion of the issue. 

In case of split DNS maybe you can create a separate issue for the discussion? If there are enough interest we can consider how to address the issue within the main coredns repo (than external plugin).

**Comment by chrisohaver** [comment]
@glasgow, @yongtang 

> In case of split DNS maybe you can create a separate issue for the discussion?

This has been done in the past. See https://github.com/coredns/coredns/issues/2833

I presented a couple of POC working solutions.

* One was an extension to the _forward_ plugin that allowed for conditional forwarding based on a configured expression.  I have since moved this off to a separate set of external plugins. See https://github.com/infobloxopen/fwdpolicy and https://github.com/chrisohaver/conditional

* Another which I preferred, was a more direct implementation of BIND-like views.  This was less clunky, didn't involve  extra local forwarding hops like the above forward implementation, but required some modifications to core CoreDNS server code, and thus would be painful to maintain out of tree so I abandoned it.  The branch is still in my repo... https://github.com/chrisohaver/coredns/tree/views.  It's a year behind CoreDNS master at this point.

**Comment by chrisohaver** [comment]
The related PRs:
* https://github.com/coredns/coredns/pull/4446 - The objection was that it modified the _forward_ plugin.
* https://github.com/coredns/coredns/pull/4463 - The objection was that it modified CoreDNS code.

My goal in both of those was to add "hooks" into CoreDNS that would allow one to write an external plugin to enable view-like behavior. I provided such a plugin "conditional" to serve as fairly flexible example.  However, in both cases the hooks were judged too extensive to justify adding.
