### ISSUE TITLE
forward  plugin memory usage

### ISSUE THREAD

**Issue by keepalivesrc** [coredns/coredns#3144]
the version of CoreDNS 1.6.2
i use forward  plugins,the memory usage 3.5GB

100,000 domain names {
     forward . 10.10.10.2
}
. {
     forward . tls://9.9.9.9 tls://9.9.9.10 {
    tls_servername dns.quad9.net
   }
    cache
}

when i use proxy plugin,use this Corefile,the memory usage about 30MB,but 1.6.2 removed proxy plugin

. {
  forward . 127.0.0.1:5301 {
  except 100,000 domain names
  }
  proxy . 10.10.10.2
  log
  cache
  health
}
.:5301 {
   forward . tls://9.9.9.9 tls://9.9.9.10 {
       tls_servername dns.quad9.net
   }
   cache
}

**Comment by chrisohaver** [comment]
@keepalivesrc, To clarify, does "100,000 domain names" mean you are inserting 100000 domain names at that place in the Corefile?

If so, it is probably because doing that creates 100000 instances of the *forward* plugin, in the first Corefile example.

In the second example, there are only two instances of *forward*.

**Comment by chrisohaver** [comment]
extreme case of #3026 (at least the plugin duplication part of that issue)

**Comment by keepalivesrc** [comment]
> @keepalivesrc, To clarify, does "100,000 domain names" mean you are inserting 100000 domain names at that place in the Corefile?
> 
> If so, it is probably because doing that creates 100000 instances of the _forward_ plugin, in the first Corefile example.
> 
> In the second example, there are only two instances of _forward_.

yep,inserting 100000 domain names in Corefile,the new version removed proxy plugin so i'm need Find a new way to solve this problem.thanks for your reply

**Comment by chrisohaver** [comment]
> the new version removed proxy plugin ...

Proxy was moved to an external plugin at around 1.4/1.5 timeframe - you could compile CoreDNS with the external [proxy](https://github.com/coredns/proxy) plugin.

If _forward_ allowed multiple instances per server block, you could simply use forward instead of proxy - but forward only allows one instance per server block.

**Comment by keepalivesrc** [comment]
> > the new version removed proxy plugin ...
> 
> Proxy was moved to an external plugin at around 1.4/1.5 timeframe - you could compile CoreDNS with the external [proxy](https://github.com/coredns/proxy) plugin.
> 
> If _forward_ allowed multiple instances per server block, you could simply use forward instead of proxy - but forward only allows one instance per server block.

yep, i compile external proxy plugin to CoreDNS,Thanks!
