### ISSUE TITLE
forward . /etc/resolv.conf not work sometimes when use local dns

### ISSUE THREAD

**Issue by wwgfhf** [coredns/coredns#3147]
I use coredns 1.5.0 in k8s 1.14.3 , the config of coredns is 
```
.:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream /etc/resolv.conf
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          prefer_udp
        }
        cache 30
        loop
        reload
        loadbalance
    }
```
i write my local dns in /etc/resolv.conf,  but it not work sometimes in pod.
But when i change the /etc/resolv.conf to local dns address 
```
forward . 10.110.18.115
```
it worked always

**Comment by chrisohaver** [comment]
Can you show us what is in `/etc/resolv.conf`?

Does it work more reliably if you remove `prefer_udp`? #3110

**Comment by wwgfhf** [comment]
@chrisohaver Thanks for your reply, this is my /etc/resolv.conf
```
nameserver 10.110.18.115
nameserver 114.114.114.114
```
And it seeams same as before when  remove prefer_udp.

**Comment by chrisohaver** [comment]
You have two nameservers in `/etc/resolv.conf`, which is why you see the behavior difference when you specify just one of them. "114.114.114.114" presumably not working.

By default the _forward_ plugin uses the "random" policy, see https://github.com/coredns/coredns/blob/master/plugin/forward/README.md.  You can use "sequential" instead so the "10.110.18.115" server is always tried first. e.g. 
```
        forward . /etc/resolv.conf {
          policy sequential
          prefer_udp
        }
```
