### ISSUE TITLE
middleware/loadbalance: balance more records

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#316]
We could (and should) loadbalance more record types. MX are sensible. SRV as well?

**Comment by stp-ip** [comment]
Does balancing MX records really make sense? As long as the MX records have the same weight they should usually be load balanced within the client afaik.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/load..." ]

> Does balancing MX records really make sense? As long as the MX records have the same weight they should usually be load balanced within the client.

google public dns does it:

dig MX miek.nl @8.8.8.8

But a _good_ client should look at the priority.

/Miek

## 

Miek Gieben

**Comment by miekg** [comment]
We should probably check in https://github.com/miekg/coredns/blob/master/middleware/loadbalance/loadbalance.go#L16 if a reply has a question section asking for A, AAAA (and potentially) MX. Now we always loadbalance a reply.

**Comment by stp-ip** [comment]
Ok so they even loadbalance between priorities. So balancing A, AAAA, MX and SRV might be useful.

**Comment by jcdickinson** [comment]
How would the SRV load balancing work? From the readme:

> loadbalance acts as a round-robin DNS loadbalancer by randomizing the order of A and AAAA records in the answer.

However, SRV already supports this, and _more_, when `priority` and `weight` are used in conjunction. IMO:

## SRV Loadbalance Strategy

The configuration includes a `priority` and `weight` for each record (as-per SRV specification). The shuffle would then:
1. Place all records into buckets based on their priority.
2. Perform a weighted shuffle on each bucket.
3. Emit the buckets (sorted by priority ascending).

Additionally the middleware could automatically generate the SRV record for you (which is completely static given the same configuration). The default strategy can then be deprecated/retired because the current strategy is simply SRV with all records having `weight=1` and `priority=1`.

## Remarks

In the above case it would make sense to add MX, because MX records are not as versatile as SRV records.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/load..." ]

> How would the SRV load balancing work? From the readme:
> 
> > loadbalance acts as a round-robin DNS loadbalancer by randomizing the order of A and AAAA records in the answer.
> 
> However, SRV already supports this, and _more_, when `priority` and `weight` are used in conjunction. IMO:
> 
> ## SRV Loadbalance Strategy
> 
> The configuration includes a `priority` and `weight` for each record (as-per SRV specification). The shuffle would then:
> 1. Place all records into buckets based on their priority.
> 2. Perform a weighted shuffle on each bucket.
> 3. Emit the buckets (sorted by priority ascending).
> 
> Additionally the middleware could automatically generate the SRV record for you (which is completely static given the same configuration). The default strategy can then be deprecated/retired because the current strategy is simply SRV with all records having `weight=1` and `priority=1`.

I'm not in favor of generating records from this middleware. Also I'm hoping a
SRV aware client this does shuffling.

> ## Remarks
> 
> In the above case it would make sense to add MX, because MX records are not as versatile as SRV records.

Agreed, this would be a nice addition (and relatively easy to add)

/Miek

## 

Miek Gieben

**Comment by jcdickinson** [comment]
> Also I'm hoping a SRV aware client this does shuffling.

Good point. So what you're saying is that you make sure that even bad client implementations should still behave correctly? I.e. The SRV record should come back pre-shuffled (according [to spec](https://www.ietf.org/rfc/rfc2782.txt))?

> I'm not in favor of generating records from this middleware.

Fair enough. Any opposition to using SRV records as the configuration for `weight` and `priority`? I'm not convinced that it's a good idea, but it's worth mentioning. The problem is that IANA don't have registrations for every type of DNS record (e.g. MX/smtp is absent). The only workaround I can think of is clearly a hack:

| Entry | Priority | Weight | Port | Target |
| --- | --- | --- | --- | --- |
| _mx._coredns.example.com. | 1 | 60 | 443 | mx1.example.com. |
| _mx._coredns.example.com. | 1 | 40 | 443 | mx2.example.com. |
| _mx._coredns.example.com. | 2 | 0 | 443 | mx3.example.com. |

Another route would be to configure your priorities and weights within loadbalance, but that would result in compliant clients and non-compliant clients behaving differently (as compliant clients would ultimately ignore the coredns shuffle).

Maybe loadbalance shouldn't care about SRV at all and merely replicate the behavior of it for other record types?

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/load..." ]

> | Entry | Priority | Weight | Port | Target |
> | --- | --- | --- | --- | --- |
> | _mx._coredns.example.com. | 1 | 60 | 443 | mx1.example.com. |
> | _mx._coredns.example.com. | 1 | 40 | 443 | mx2.example.com. |
> | _mx._coredns.example.com. | 2 | 0 | 443 | mx3.example.com. |
> 
> Another route would be to configure your priorities and weights within loadbalance, but that would result in compliant clients and non-compliant clients behaving differently (as compliant clients would ultimately ignore the coredns shuffle).
> 
> Maybe loadbalance doesn't care about SRV at all and merely replicate the behavior of it for other record types?

Yes, _loadbalance_ should not touch SRV records, only A/AAAA and (maybe) MX.

**Comment by jcdickinson** [comment]
I'm still learning Go, but would love to approach this problem this weekend. So in terms of the PR I'd create:
- Reflect SRV records (with the funky _coredns proto)?
- Some configuration file with weights/priorities?

**Comment by miekg** [comment]
Please only focus on adding loadbalancing for MX records. This should no be too hard and gives you a good learning experience (both for Go and CoreDNS internals)

Thanks for working on this.

**Comment by miekg** [comment]
Is this coming along?

**Comment by jcdickinson** [comment]
Sorry, got side-tracked this weekend. I'm looking into it tonight.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/load..." ]

> Sorry, got side-tracked this weekend. I'm looking into it tonight.

no problem (and no rush), just wondering.

Thanks!
