### ISSUE TITLE
Stance/future with Caddy v2

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#3261]
Caddy is working on a revamped v2 and we might wanna think about our future stance on this.

Do we want CoreDNS to migrate to v2?
Would this mean CoreDNS v2 as well?
What are the main pain points within Caddy v1?

Starting this discussion now as Caddy v2 is still inflight to make it possible to remove some pain points in the process, if we decide that v2 might be the way to go.

Would love your thoughts ideas etc.

For context:
https://github.com/caddyserver/caddy/wiki/v2:-Writing-a-Module
https://github.com/caddyserver/caddy/blob/v2/modules/caddyhttp/caddyhttp.go

**Comment by stp-ip** [comment]
Looping in @mholt as well :)

**Comment by mholt** [comment]
I think this would be a good idea, and I'd rather get feedback sooner than later especially if changes need to be made to the design (it's too late already for some things, but depends how critical it is).

However, I'm pretty confident we can meet most, if not all, of CoreDNS' needs already.

v2 _should_ be able to simplify quite a bit in general. The biggest improvement for plugins is that all config loading is done for you, yay! All you need to do is declare a type:

```go
package coredns 

type App struct {
   // config fields here
}

// since CoreDNS would be an "app" module, you'll need
// to implement the caddy.App interface with Start() and
// Stop() methods
```

Then implement the `caddy.Module` interface:

```go
func (App) CaddyModule() caddy.ModuleInfo {
	return caddy.ModuleInfo{
		Name: "dns",
		New:  func() caddy.Module { return new(App) },
	}
}
```

Then register it:

```go
package coredns

func init() {
    caddy.RegisterModule(App{})
}
```

Once you import your module's package, that's it! You can then run Caddy with a config like this:

```
{
    "apps": {
        "dns": {
             // coredns config goes here!
         }
     }
}
```

Most modules also have a `Provision()` method to set themselves up, especially if they need to load guest modules (plugins of their own). Loading modules out of a json.RawMessage field is pretty easy, but probably the "most complicated" single thing a host module will do:

```go
val, err := ctx.LoadModule("dns.whatever."+modName, app.WhateverRaw)
if err != nil {
	return fmt.Errorf("loading guest module '%s': %s", modName, err)
}
app.Whatever = val.(MyWhatever)
app.WhateverRaw = nil // allow GC to deallocate
```

That's about all there is to the basics. Hope that helps.

Edit: In v2, the Caddyfile is totally separate. It's a config generator, basically, rather than the primary way to configure your plugin. The "Caddyfile adapter" is one of several "config adapters" that take some input and output Caddy's native JSON config. The Caddyfile adapter is basically finished and working on the v2 branch, and it is special in that it is baked into Caddy by default, and is modular, so you can specify your own directives and stuff. It works a little differently than the v1 Caddyfile at a high-level, but the syntax and structure is basically the same, as is low-level token parsing. So your parsing code can remain mostly the same, it's just how everything plugs in that's a little different. We can go over that later.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Stance/future..." ]
>I think this would be a good idea, and I'd rather get feedback sooner than later especially if changes need to be made to the design (it's too late already for some things, but depends how critical it is).
>
>However, I'm pretty confident we can meet most, if not all, of CoreDNS' needs already.
>
>v2 _should_ be able to simplify quite a bit in general. The biggest improvement for plugins is that all config loading is done for you, yay! All you need to do is declare a type:

That's quite nice!

>That's about all there is to the basics. Hope that helps.

Thanks for the details.

This is all backwards incompatible, although we can change in-tree plugins 
easily enough. I don' want to inflict such changes for the reason that caddy 
moved to a v2, but rather some incremental path to using the new bits.

The dropping of config parsing in plugins sound an interesting first step.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
We should most likely start hiding the caddy deps from plugins, i.e.
~~~
func init() {
	caddy.RegisterPlugin("whoami", caddy.Plugin{
		ServerType: "dns",
		Action:     setup,
	})
}
~~~
can be wrapped by ourselves into something like
~~~
plugin.Register("whoami", setup)
~~~
`*caddy.Controller` is harder to hide, but if we move to using caddy2's auto-setup stuff those things might be moot

**Comment by miekg** [comment]
I want to very much look into automatically parsing a plugin struct and getting rid of all setup.go and setup_test.go code - of course in a backward compatible way

**Comment by mholt** [comment]
Hmm, thst could get a little dicey in the long run -- any reason you want to hide the Caddy dependencies?

Note that logic from setup functions that parse Caddyfile (or Corefile) tokens need to remain if you wish to support configuring those modules/plugins from the Corefile. (Otherwise, you're right, the native JSON config format unmarshals for you.) EDIT: After seeing the linked issue, I think I see what you mean: you're hoping to infer Corefile syntax from the native structure, using reflection or the like. That's fine I guess, however you want to do it!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Stance/future..." ]
>Hmm, thst could get a little dicey in the long run -- any reason you want to hide the Caddy dependencies?

mostly for backwards compatibilty in the future. I don't see a good reason to 
make backwards incompatible changes in CoreDNS right now.

>Note that logic from setup functions that parse Caddyfile (or Corefile) tokens need to remain if you wish to support configuring those modules/plugins from the Corefile. (Otherwise, you're right, the native JSON config format unmarshals for you.)

Yep, agreed, this is also not really a problem, but some level of indirection 
might be beneficial to us as a project. Especially now that caddy has moved on 
to version 2.

**Comment by miekg** [comment]
We should piecemeal port and use the best bits of caddy v2. We should def. *not* make any API changes because of it though.

Closing this. Please open an new issue if there is some piece of v2 we should start using.

**Comment by mholt** [comment]
As an update... It turns out that Caddy 2 plugins ("modules") will be eligible to be documented automatically from its source code. There's a brief demo of a prototype at the end of the video here: https://m.youtube.com/watch?v=EhJO8giOqQs. CoreDNS would also benefit from Caddy 2's API that enables graceful, online, dynamic config changes. You don't even need to write any API endpoints yourself,  the API comes for free. These features might be really appealing for some of your users, and it could relieve some burden for you as maintainers.

**Comment by mholt** [comment]
As far as compatibility, I doubt much if anything would have to break externally. You're in control of the corefile format/syntax and you can probably just plop your existing code into the v2 design and the main changes would probably just be how plugins are registered... At least that's what comes to mind right now.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Stance/future..." ]
>As far as compatibility, I doubt much if anything would have to break externally. You're in control of the corefile format/syntax and you can probably just plop your existing code into the v2 design and the main changes would probably just be how plugins are registered... At least that's what comes to mind right now.

I don't like making this particular change, unless it can be made backwards
compatible.

As for the dynamic config updates - that works now, but is quite crude (i.e. a
config reload). I'm more a fan of having this "config" live in some backend
(e.g. the kubernetes api) and just serve that. This keeps the core config very
static negating the need for such an API.

But, that being said, this is interesting stuff. I also looks at Envoy and what
they do.

**Comment by mholt** [comment]
> I don't like making this particular change, unless it can be made backwards
compatible.

What do you define as backwards compatible in this case? (There's a lot of layers here.) Plugin registration is an implementation detail and is not exposed to users, so that wouldn't break anyone.

> As for the dynamic config updates - that works now, but is quite crude (i.e. a
config reload). I'm more a fan of having this "config" live in some backend
(e.g. the kubernetes api) and just serve that. This keeps the core config very
static negating the need for such an API.

Fair enough; v2 has a mechanism (still developing it, in fact) that will allow you to load a config from some arbitrary storage location. This way, the config you feed the server stays static, and it loads its actual config on its own.

But, how do you do online config changes then, without, er, reloading it?

> But, that being said, this is interesting stuff. I also looks at Envoy and what
they do.

Anything catch your eye in particular? Let me know, and I'll see what we can do!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Stance/future..." ]
>> I don't like making this particular change, unless it can be made backwards
>compatible.
>
>What do you define as backwards compatible in this case? (There's a lot of layers here.) Plugin registration is an implementation detail and is not exposed to users, so that wouldn't break anyone.

source API backwards compatible, so no source level changes are needed in any of
the plugins.

>Fair enough; v2 has a mechanism (still developing it, in fact) that will allow you to load a config from some arbitrary storage location. This way, the config you feed the server stays static, and it loads its actual config on its own.

ah, that's cool; I've been pushing forward the use of disk (or something to
'write to') for ages, right now I'm just using the 'os' package. I'm aware Caddy
has been using http.FileSystem for some things, but I think CoreDNS needs more,
at least 'Remove', 'Symlink', 'Inofity' and maybe 'Append'. Something that
unifies all access behind an interface and it extensible with a *plugin* would
be really cool.

>But, how do you do online config changes then, without, er, reloading it?
>
>> But, that being said, this is interesting stuff. I also looks at Envoy and what
>they do.
>
>Anything catch your eye in particular? Let me know, and I'll see what we can do!

The whole xds, lds, lfs shenanigans, I need something similar for https://github.com/coredns/coredns/blob/traffic/plugin/traffic/README.md
