### ISSUE TITLE
forward: allow use edns0

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3386]
Related to #3305 

When forwarding we use the client's buffer size; but we also (must of the time) cache these answers; they way we cache means we can cache an answer that's too small or we cache it in the tcp cache.

As we truncate answer for specfic clients's anyway we probably can do 2 things
1. always set edns0 buffer size to 2k (or something that doesn't fragment, see 2020 flagday (#2979))
2. remove the distinction in cache between tcp/udp and have one, and just truncate to the right size.

/cc @rdrozhdzh

**Comment by miekg** [comment]
edit: we do *not* distinguish between udp/tcp in the cache, but between 'DNSSEC OK' and not. This is more tricky, because other plugins may also return a different response depending on DO; i.e this would force them to always return/ask with DO bit set.

Still I think this is a sensible change; we can filter them out in *cache*

**Comment by rdrozhdzh** [comment]
Seems too many things mixed in this and related issues. See below my opinion
1. DNS 2020 flagday just requires that **authoritative** DNS servers set appropriate buf size in DNS **response**. Frankly speaking, different plugins can be considered as different DNS devices with different roles, e.g. `forward` plugin is a DNS forwarder, `rewrite` plugin - intelligent forwarder, `file` plugin - authoritative server. So, the coredns behavior may be different depending on which plugin created the response. If response comes from `file` plugin we can consider it as authoritative server, and therefore it should set appropriate buf size in OPT record, if present.
2. Based on above, forward plugin should not change OPT record in both directions
3. Normally, no plugins should change buf size in query OPT.
4. I'm not familiar enough with `cache` plugin code. Do we cache OPT record from DNS response? This is prohibited, see https://tools.ietf.org/html/rfc6891#section-6.2.1

> remove the distinction in cache between tcp/udp and have one, and just truncate to the right size.

Not sure about this. Perhaps if cached response doesn't fit the requested buffer we should treat this as cache miss and forward the query to the next plugin and get new response from authoritative server. Because auth name server can vary response depending on client buffer size.
Perhaps we would also cache different responses for the queries with different buf size.

btw, seems #3391 is related issue

**Comment by ykhr53** [comment]
Hi,

I think DNS Flag Day is not only for authoritative DNS server but also resolver and related software.

https://dnsflagday.net/2020/
> Action: DNS Resolver Operators
> Requrirements on the resolver side are more or less the same as for authoritative: ensure that your servers can answer DNS queries over TCP (port 53), and configure an EDNS buffer size of 1232 bytes to avoid fragmentation. Remember to check your firewall(s) for problems with DNS over TCP!

We have to consider about fragment attack anyway, *bufsize* can limit requester's UDP payload size.  
This Draft may also be useful.  

https://tools.ietf.org/html/draft-fujiwara-dnsop-fragment-attack-01#section-4.3
> 4.3.  Limit requestor's UDP payload size to 512
>    Limiting EDNS0 requestor's UDP payload size [RFC6891] to 512 may be a
>    measure of path MTU attacks.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] forward: allo..." ]
>Hi,
>
>I think DNS Flag Day is not only for authoritative DNS server but also resolver and related software.
>
>https://dnsflagday.net/2020/
>> Action: DNS Resolver Operators
>> Requrirements on the resolver side are more or less the same as for authoritative: ensure that your servers can answer DNS queries over TCP (port 53), and configure an EDNS buffer size of 1232 bytes to avoid fragmentation. Remember to check your firewall(s) for problems with DNS over TCP!
>
>We have to consider about fragment attack anyway, *bufsize* can limit requester's UDP payload size.
>This Draft may also be useful.
>
>https://tools.ietf.org/html/draft-fujiwara-dnsop-fragment-attack-01#section-4.3
>> 4.3.  Limit requestor's UDP payload size to 512
>>    Limiting EDNS0 requestor's UDP payload size [RFC6891] to 512 may be a
>>    measure of path MTU attacks.

doing edns sizing in a different plugin seems like a very sensible path forward. 
We don't have do antyhing here.

Thanks both for your input.

**Comment by miekg** [comment]
bufsize plugin will solve this.
