### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3393]
I'm eyeballing some RSS graph (can't include them here - sorry). But we're looking memory. This is in a kubernetes setting with a non-default config (don't think that matters thought). It's kubernetes + forward +cache etc.

On startup we consume 40MB-ish, this grows to 140MB in the 30days I'm looking at.

Will be somewhat trouble some to pprof this; esp, since pprofing requires a reload which resets the stats.

**Comment by miekg** [comment]
this is 1.6.4; think just the coredns from docker hub

**Comment by chrisohaver** [comment]
@miekg, We have not observed any long term memory growth in the long run tests of CoreDNS 1.6.4 we have been running (using the default kubeadm deployed corefile).

Can you share more details about the environment? e.g.
The Corefile?
Kubernetes version?
Number of nodes, services and pods in kubernetes.
QPS served by CoreDNS.
Ratio of internal vs external queries.

**Comment by miekg** [comment]
* corefile: default from deployment cluster
* kubernetes 1.13.x
* qps hovers around 1K, forwarding is minimal. 

Services and nodes might be harder to put here. I think this is normal churn and growth.

Planning to pprof it here.

**Comment by chrisohaver** [comment]
OK, nothing out of the ordinary.  Just for reference, specs on the long run test:
CoreDNS version: 1.6.4
K8s: 1.15.0
K8s nodes: 4
K8s services: 110
K8s pods: 242
CoreDNS QPS: 1100
CoreDNS up: 85 days
CoreDNS RSS: 11 MiB
Cache entries: ~1800

**Comment by miekg** [comment]
Ok. Thanks. Here is way more than that and a lot of churn as well. Do we
test that also?

**Comment by chrisohaver** [comment]
Yeah, we churn by killing all test pods (about 200), and letting the deployments spin them back up repeatedly.  This results in a pretty much constant stream of endpoint changes.

Edit - Actually the churn process has only been running for the past 24 hours - So we don't have long term data on that yet.  Churning endpoints showed an immediate bump in RSS of about 1M, but has been otherwise flat.  I do see a steady increase in i/o cache with the churn - which is unexpected, looking into it...

**Comment by miekg** [comment]
Ok.. awesome. I wasn't aware we're doing this!

Now I def. need to figure out where the memory goes here.

**Comment by chrisohaver** [comment]
> Ok.. awesome. I wasn't aware we're doing this!

Just wanted to make sure you didnt miss my edit to my comment above (since you are interacting via email) - The churn process has only been running for 1 day - not 86 days., so no long term data with churn yet.

**Comment by miekg** [comment]
Ok. Thanks. Yes indeed that doesn't show. Let's wait and see. This should
be visible after a day or two.

**Comment by chrisohaver** [comment]
@miekg, I am seeing a ~steady~ increase in the coredns pod's io cache in the long run test.  It has gone from from 0 to 1MB in the 24 hours that the churn has been running.  But IIUC, io cache fills otherwise unused memory - IOW, if applications need memory, they get it, and io cache is reduced. 
~I think the total "memory used" stat includes both RSS and cache (and swap)~ (correction, the pod "memory used" stat from prometheus is just RSS iiuc)

Why suddenly io cache is needed in the coredns pod when churning endpoints, I'm not sure.

**Comment by chrisohaver** [comment]
In the Long Run tests, RSS for the coredns pod has continued to remain level.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] memory leak? ..." ]
>In the Long Run tests, RSS has continued to remain level.

ok, looking again at the data; it seems it stablized here as well.

Hmm, odd. Let's close this for now.

/close
