### ISSUE TITLE
The coredns_cache_size metric jumps around

### ISSUE THREAD

**Issue by jaygorrell** [coredns/coredns#3434]
I'm not using prometheus so just pinging the /metrics endpoint at the moment, but I'm seeing the `coredns_cache_size` value jump around between a few different values. One hit might have 4 denial and 12 success, then it'll have 49 denial and 7 success, then it will go back to 4 denial and 12 success.

I'm using the NodeLocalDNS kubernetes daemonset so I'm hitting a single local hostnetwork address (169.254.20.10) for all requests.

Apologies if this isn't an issue and I'm just misunderstanding something.

**Comment by miekg** [comment]
is there anything to do here?

**Comment by jaygorrell** [comment]
I don't see any resolution or answer, so I'd say _yes_ :)

**Comment by chrisohaver** [comment]
@zouyee, have you investigated this?

**Comment by chrisohaver** [comment]
@jaygorrell, I do not see this behavior in a k8s system I had up on hand, which is running a default  dns config with 2 instances of coredns 1.6.4.  The cache size does not jump around when scraping one of the pods with curl.

I don't know what version of NodeLocalDNS you are using. We could probably correlate that back to a base version of CoreDNS (NodeLocalDNS is built from a separate repo, I think forked or copied in some manner from this repo).  I don't think cache metrics behavior has changed at all - but its possible there was a bug fixed in the past, and NodeLocalDNS is still using and older version.  FYI, the maintainers here don't maintain the NodeLocalDNS code. 

It's possible this behavior is the result of special networking magic that NodeLocalDNS does (of which would correctly infer by my use of the word "magic", I am not technically familiar).  Perhaps it is redirecting the http metrics scrapes to the cluster dns service, which in turn distributes them to the replicas (by default 2), hence the 2 state flapping.
