### ISSUE TITLE
https dns-query return no 'dns' query parameter found

### ISSUE THREAD

**Issue by zzxap** [coredns/coredns#3465]
I hava start a https server
https://www.mydomain.com  {
tls cert/fullchain.pem cert/privkey.pem cert/cert.pem
 hosts {
    10.6.6.2 sms.service
}
}
And i send a request like this 
curl -H 'accept: application/dns-json' 'https://www.mydomain.com/dns-query?name=sms.service&type=A'

it return no 'dns' query parameter found

how to get the A record return     10.6.6.2

**Comment by chrisohaver** [comment]
duplicate

**Comment by cookiengineer** [comment]
If you've landed here because Google thinks this is the answer to the problem:

- /dns-query is RFC8484, which means it only supports `?dns=<base64url encoded data>` as per [RFC4648](https://datatracker.ietf.org/doc/html/rfc4648) (it's actually base62, but whatever)

- /resolve is the JSON API, which supports `?name=<domain>&type=<DNS Q/A type>`, which this project does not support. See [this file](https://github.com/coredns/coredns/blob/master/plugin/pkg/doh/doh.go) that only supports the `?dns=...` parameter syntax.

(though many servers on the web implement this in a wrong manner, and support the `name` and `type` parameters on `/dns-query` paths)
