### ISSUE TITLE
How to response different records by client ip with plugin/file

### ISSUE THREAD

**Issue by sharego** [coredns/coredns#3518]
**EDNS** support thansfer request ip address to dns server,  is there a way to configure using this to response flexible records, like CDN case.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] How to response d..." ]
>**EDNS** support thansfer request ip address to dns server,  is there a way to configure using this to response flexible records, like CDN case.

this is not possible with the file plugin

**Comment by learn0208** [comment]
@miekg
Is there any other way to do this? like bind views acl  [https://kb.isc.org/docs/aa-00851](url)

**Comment by yongtang** [comment]
@learn0208 @sharego It is fairly straightforward to write a plugin to achieve that. In fact in KubeCon Europe I walked through a demo with code, to show you could have different response based on client IP (responds 1.1.1.1 if client in CIDR 172.0.0.0/8 and 8.8.8.8 otherwise).

There are less than *80 lines* of code total:
https://github.com/coredns/demo

You can certainly expand to more complex logic but overall it is quite straightforward.
