### ISSUE TITLE
[Security] CVE-2019-19794

### ISSUE THREAD

**Issue by yongtang** [coredns/coredns#3547]
This is a public announcement of a security vulnerability discovered in earlier versions of CoreDNS before v1.6.6:

https://nvd.nist.gov/vuln/detail/CVE-2019-19794

As was mentioned in CVE-2019-19794, one of the upstream library miekg/dns used Golang's  `math/rand`. This causes predictable TXID and may allow cache poisoning (See https://github.com/miekg/dns/issues/1043 for details).

CoreDNS was impacted by this upstream vulnerability.

The latest release of CoreDNS v1.6.6 fixes this issue. We encourage all CoreDNS users to update to v1.6.6+ as soon as possible.

The issue was discovered by @FiloSottile, we very much appreciate his contributions! 👍 

This issue will keep open for a  couple of weeks or so, so that it is visible to public.

**Comment by miekg** [comment]
should we make some more noise on this? Release is ready.

**Comment by yongtang** [comment]
I think we can post a blog on coredns.io?

**Comment by miekg** [comment]
I'll do that later today

**Comment by rtheis** [comment]
Does CVE-2019-19794 impact Kubernetes usage of CoreDNS assuming configurations such as https://github.com/kubernetes/kubernetes/blob/v1.17.0/cluster/addons/dns/coredns/coredns.yaml.base or https://raw.githubusercontent.com/coredns/deployment/5a861f8a6fa192ac9dbda1856bff95b9d6721389/kubernetes/coredns.yaml.sed?

**Comment by chrisohaver** [comment]
IIUC, it could be exploited by someone with access to read and spoof packets into the Pod network (the network traffic between pods and coredns).

**Comment by stp-ip** [comment]
This is planned to be fixed in Kubernetes in the next patch release.
Afaiks: Hard to exploit and the result would be a poisoned cache. It needs cluster access and partial control of the network to be an attack vector. So severity should be low.

You can update to the latest CoreDNS (v1.6.6) manually, if you control the Cluster or wait for the Kubernetes patch release to hit.

**Comment by miekg** [comment]
release it out; closing

**Comment by rtheis** [comment]
@stp-ip Is it possible then to mitigate this security vulnerability by disabling the cache via removing the `cache` plugin from the CoreDNS configuration?

**Comment by stp-ip** [comment]
The cache poisoning isn't within the CoreDNS cache in the usual Kubernetes setup afaik.
In general the issue is that response forgeries can be created, that can lead to a poisoned cache within applications and/or caching resolvers.

To answer the specific question. Disabling the cache plugin shouldn't prevent this issue from happening afaik.

If you control the deployment upgrade to 1.6.6 manually or wait for the next K8s patch release.
