### ISSUE TITLE
希望template插件支持rcode NODATA 应答！谢谢！

### ISSUE THREAD

**Issue by snakwu** [coredns/coredns#3559]
如果设置插件为：
template ANY AAAA {
    rcode NXDOMAIN
}

windows会发现两个dns请求，一个是请求AAAA记录。第二个是A记录。
因为很多域名是没有ipv6地址的，于是dns先返回一个NXDOMAIN AAAA，再返回一个正常的A记录。于是浏览器误以为没有这个域名了引起无法访问。

**Comment by chrisohaver** [comment]
google translated:

If the plugin is set to:
template ANY AAAA {
rcode NXDOMAIN
}

Windows will find two DNS requests, one is to request AAAA records. The second is the A record.
Because many domain names do not have ipv6 addresses, dns first returns an NXDOMAIN AAAA, and then returns a normal A record. So the browser mistakenly thought that the absence of this domain name caused inaccessibility.

**Comment by chrisohaver** [comment]
That config works as expected, and it seems that windows acts in a reasonable way as you explain it.

What is your use case?

**Comment by snakwu** [comment]
我是用来做dns分流，就是本国的ip就正常返回ipv4和ipv6，国外的ip只需要返回ipv4。
我查阅过资料，要windows不误认为是不存在的域名，就需要返回的rcode 为 NODATA。

**Comment by chrisohaver** [comment]
> I use it to do dns shunting, that is, the local IP will return ipv4 and ipv6 normally, and the foreign IP only needs to return ipv4.
> I have checked the information. In order for Windows not to mistakenly believe that the domain name does not exist, the rcode returned is NODATA.

Template can provide a NODATA response as of ...
https://github.com/coredns/coredns/pull/2855

**Comment by snakwu** [comment]
template IN AAAA？？
