### ISSUE TITLE
middleware/proxy: DNS over TLS

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#356]
We should support this - its an RFC (IIRC). It basically boils down to stuff the dns binary data over a TLS connection. Go DNS has support for this (although it could be improved).

This should be an option `tls` in the proxy configuration.

Note that this is different from DNS over HTTPS (to google) that needs json marshalling and other stuff. I believe the former belong the _proxy_ middleware, while this (dns-over-https-google) might need a new middleware.

**Comment by stp-ip** [comment]
Just to clarify what this means.

The proxy might get records via HTTPS from google for example. This would be enabled in the proxy configuration via a `tls` keyword?

The other maybe new middleware would be serving DNS over TLS to the client? So basically:
client -> https -> https-proxy -> coredns -> https-proxy -> happy client

**Comment by miekg** [comment]
> The proxy might get records via HTTPS from google for example. This would be enabled in the proxy configuration via a tls keyword?

Google does not support DNS-over-TLS, what we want to do there is #155 

I think the intent here is to allow upstream to be fetched over TLS and respond to client via normal DNS

**Comment by stp-ip** [comment]
Thanks for the clarification.

For anyone interested the current RFC for DNS over TLS is https://datatracker.ietf.org/doc/rfc7858.

Basically #155 is a special implementation/workaround for the current method (https + json) google uses to provide privacy for DNS requests, which could be used for upstream queries.

This issue is for plain DNS over TLS, which should be integrated in the proxy to enable privacy provided upstream queries. (Later this could be used for google too, if they switch to RFC7858).

_Sidenote: There are already issues for DNS over TLS for user facing queries: #16 and #234_

**Comment by stp-ip** [comment]
Seems this is available with TLS on the user facing side and TLS via google on the proxy side. Can be closed.
