### ISSUE TITLE
non-amd64 images claim to be amd64

### ISSUE THREAD

**Issue by bfallik** [coredns/coredns#3669]
**What happened**:

I tried to run the arm coredns image but podman refused:

```
# podman pull coredns/coredns:latest
Trying to pull docker.io/coredns/coredns:latest...
Getting image source signatures
Copying blob 89d2da39cc12 [--------------------------------------] 0.0b / 0.0b
Copying config b52ee75a77 done  
Writing manifest to image destination
Storing signatures
b52ee75a7749dc470ec4dacf990c26733c1477371f190e2748d653b8834c3f48
# podman run coredns/coredns
Error: incompatible image architecture "amd64" on "arm" host
# podman image inspect b52ee75a7749d | jq '.[0].Architecture'
"amd64"
```

**What you expected to happen**:

The image would have the 'arm' architecture and run successfully.

**How to reproduce it (as minimally and precisely as possible)**:

see above

**Anything else we need to know?**:

I originally asked about this on a [podman mailing list thread](https://lists.podman.io/archives/list/podman@lists.podman.io/thread/PIISF4ZSDQFZCGR3ANMASO4I7BXBLC6K/). I was pointed at https://github.com/kubernetes/kubernetes/issues/87325 for a similar issue in k8s.

**Environment**:

RaspberryPi 3

**Comment by chrisohaver** [comment]
All coredns tagged releases are manifest _lists_, which contain images for each arch .  Just to test, does using the arm image only manifest `coredns/coredns:coredns-arm` work?

**Comment by miekg** [comment]
The whole arch stuff in docker felt very "bolted on", no supprise other tools can't
understand it.

**Comment by bfallik** [comment]
@chrisohaver 

> All coredns tagged releases are manifest _lists_, which contain images for each arch . Just to test, does using the arm image only manifest `coredns/coredns:coredns-arm` work?

Surprisingly, no that doesn't seem to work either.

```
# podman pull coredns/coredns:coredns-arm
Trying to pull docker.io/coredns/coredns:coredns-arm...
Getting image source signatures
Copying blob c6568d217a00 skipped: already exists  
Copying config b52ee75a77 done  
Writing manifest to image destination
Storing signatures
b52ee75a7749dc470ec4dacf990c26733c1477371f190e2748d653b8834c3f48
# podman run coredns/coredns:coredns-arm
Error: incompatible image architecture "amd64" on "arm" host
```

**Comment by chrisohaver** [comment]
Looks like every arch we build is annotated as amd64 architecture.  However, the sizes of images differ between archs of the same version, so it's likely that just the annotation is wrong.  Podman may be validating the annotation, whereas docker pulls may be ignoring it. 

We could try adding `--platform=os/arch` to the `docker build` command in `Makefile.release`.  The option is experimental however... which suggests to me that podman _probably_ shouldn't be validating the field quite yet.  Is there an option in podman to skip this validation?

```
cohaver$ docker manifest inspect -v coredns/coredns:coredns-arm
{
	"Ref": "docker.io/coredns/coredns:coredns-arm",
	"Descriptor": {
		"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
		"digest": "sha256:a8be13d1f9fbd24d75dbc2013bb37f810cd1aa217d135173dab6cdbef652485e",
		"size": 739,
		"platform": {
			"architecture": "amd64",
			"os": "linux"
		}
	},
	"SchemaV2Manifest": {
		"schemaVersion": 2,
		"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
		"config": {
			"mediaType": "application/vnd.docker.container.image.v1+json",
			"size": 1945,
			"digest": "sha256:b52ee75a7749dc470ec4dacf990c26733c1477371f190e2748d653b8834c3f48"
		},
		"layers": [
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 122224,
				"digest": "sha256:c6568d217a0023041ef9f729e8836b19f863bcdb612bb3a329ebc165539f5a80"
			},
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 12543683,
				"digest": "sha256:89d2da39cc12ed98983b4f9042171916126863686c6e5c5682859712e9bcf248"
			}
		]
	}
}

```

**Comment by bfallik** [comment]
hi @chrisohaver ,

Yes, podman-run exposes an option that allows me to skip the validation, --override-arch=arm, so I'm not immediately blocked by this bug. I wanted to log it so that this project was aware of the discrepancy between the metadata and the underlying bits.

**Comment by chrisohaver** [comment]
FWIW, I tried building with the `--platform` option, and it made no difference.   I may have done something wrong - or perhaps the option doesn't do what I expect - or perhaps it's not fully functional ("experimental") docker engine 19.03.5.

I expect that building each image on a docker server actually running in the target architecture would work.  I saw a comment in a discussion that the os/arch used in an image manifest is dubiously determined by the os/arch of the docker server that builds it.  However, this would be challenging to pull off for all archs.

That said, since this is the default behavior of docker, it would seem that the discrepancy would be common.

**Comment by stp-ip** [comment]
Can you check with `gcr.io/k8s-staging-coredns/coredns:1.6.6`
This was pushed using manifest-tool and seems to have the correct manifest afaik.

**Comment by chrisohaver** [comment]
`gcr.io/k8s-staging-coredns/coredns:1.6.6` is a manifest list... which are fine.

The issue lies in the image manifests they reference.

**Comment by chrisohaver** [comment]
I figured I'd try to see if `docker manifest` currently does a better job at this than `manifest-tool` does (`docker manifest` also experimental, which is why we still use `manifest-tool`).  It doesn't.

FWIW, I found that `docker manifest create` appears to default to using the arch indicated in each arch image manifest (all set amd64 in this case). So, you need to follow up with `docker manifest annotate` for each image in the manifest list to fix the os/archs in the manifest list before pushing the list.  This fixes the manifest list archs, but still leave the underlying image manifests set at amd64 (just as in manifest tool).

Also, `docker manifest annotate` does not allow you to annotate an image manifest - it only allows annotation of manifest _lists_. So we cant use it to "fix" the arch on each of the image manifests before building the manifest list.

**Comment by chrisohaver** [comment]
Also tested using the beta `docker buildx` multi-arch builder.  Same result.

**Comment by miekg** [comment]
I don't see what we can do here. Seems to be a bug in podman and or docker.
