### ISSUE TITLE
Rate Limiting  Plugin

### ISSUE THREAD

**Issue by bonedaddy** [coredns/coredns#3802]
**What would you like to be added**:

In certain situations you may want to rate limit all clients, or maybe just some clients. Additionally rate limiting could be used to help protect against attacks.

**Why is this needed**:

If you're running a low-powered DNS server without rate limiting it would be easy to overwhelm the DNS server. Also it could be used in part to help mitigate against things like DNS amplification attacks.

**Comment by zouyee** [comment]
https://kb.isc.org/article/AA-00897/11/What-is-a-DNS-Amplification-Attack.html

https://kb.isc.org/article/AA-00994/189/Using-the-Response-Rate-Limiting-Feature-in-BIND-9.9-Subscription-Version.html

**Comment by zouyee** [comment]
https://github.com/coredns/coredns/issues/2311

external plugin
https://github.com/coredns/rrl

**Comment by bonedaddy** [comment]
oh cool didnt see that. thanks

**Comment by chrisohaver** [comment]
rrl (response rate limiting)  != _request_ rate limiting.

Response Rate Limiting (by design) does not protect the DNS server itself from being overwhelmed.  It specifically mitigates [DNS amplification attacks](https://www.us-cert.gov/ncas/alerts/TA13-088A) against arbitrary victims.

I suspect that @bonedaddy is looking for something that limits the number of incoming queries to CoreDNS to be processed (presumably dropping any excess).

The `max_concurrent` option in the _forward_ plugin may be closer to what you want.
