### ISSUE TITLE
plugin/etcd: lookup_test fails

### ISSUE THREAD

**Issue by takuhiro** [coredns/coredns#3810]
**What happened**:

I run tests for plugin/etcd, but lookup_test.go always fails.

**What you expected to happen**:

all tests pass.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run etcd locally. I used [v3.4.5](https://github.com/etcd-io/etcd/releases/tag/v3.4.5) for darwin.
```
$ ./etcd &
```
2. Run tests with `-tags=etcd`
```
$ go test -tags=etcd ./plugin/etcd                                                                                                                                                         
--- FAIL: TestLookup (0.38s)
    lookup_test.go:331: rcode is "NXDOMAIN", expected "NOERROR"
{"level":"warn","ts":"2020-04-03T15:42:50.922+0900","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-2ede7eb0-fbb2-4ef1-ba6d-469070a3ad33/localhost:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
FAIL
FAIL    github.com/coredns/coredns/plugin/etcd  0.903s
FAIL

```

**Anything else we need to know?**:

The following test case fails.
https://github.com/coredns/coredns/blob/53f3f0b666821588e721ceeea4766b76333b668b/plugin/etcd/lookup_test.go#L132-L138

The test seems to have passed before e3266d24

**Environment**:

- the version of CoreDNS: v1.6.7 or later
- Corefile: 
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): macOS
- Others:

**Comment by msedzins** [comment]
Hi, I've looked into that and actually there are two separate issues with those tests. You can spot it when you run:
```
$go test -tags=etcd ./plugin/etcd   -v 
=== RUN   TestLookup
    TestLookup: lookup_test.go:331: rcode is "NXDOMAIN", expected "NOERROR"
--- FAIL: TestLookup (0.29s)

=== RUN   TestSetupEtcd
{"level":"warn","ts":"2020-04-19T21:27:25.072+0200","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-d8e37ae4-1704-4ffd-ae5a-789a21f57ce3/localhost:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
--- PASS: TestSetupEtcd (0.01s)
```

**First problem  (TestLookup)**

The error was introduced in https://github.com/coredns/coredns/commit/e3266d24f7a3a120739875ff421d2d47d044ad69 with the change in the line number 330, to be more specific:
value of "exact" parameter was changed from "false" to "true".

To fix that error we need to update the test in lookup_test.go, lines 134 and 136:
 "server1.prod.region1.skydns.test." -> "txt.server1.prod.region1.skydns.test."

I will create pull request for that.

**Second problem  (TestSetupEtcd)**

The problem is in setup_test.go file, test in line 45 ("// with valid credentials"). We try to test connection to etcd with credentials but authentication in etcd is not enabled by default.
Test is not failing (there is a warning) but I don't think it tests anything meaningfull.

However, when we enable authentication in etcd - anonymous access is blocked (no guest account in etcd v3 as opposed to etcd v2). As a result - many other tests stop working.

I'm not sure if there is an easy fix to that problem. Any suggestions are welcomed.
