### ISSUE TITLE
How to configure multiple ip for one domain

### ISSUE THREAD

**Issue by zhyinjun** [coredns/coredns#3821]
Hi, I have two K8S clusters in a private network, cluster A and cluster B.  

Cluster A has defined following ingress: 
clusterA.example.com: 10.10.10.10
clusterA.example.com: 10.10.10.11
clusterA.example.com: 10.10.10.12

How can I configure the CoreDns in Cluster B, then the service in the Cluster B can access the clusterA.example.com(IP address is resolved randomly)?

Thanks,

**Comment by johnbelamaric** [comment]
Not sure I really understand the question. These are IP addresses for the API server? Or for the L7 load balancer (i.e., ingress)? Do you have another DNS server or is it just the in-cluster service?

For simple use cases the [k8s_external](https://coredns.io/plugins/k8s_external/) plugin + zone transfers between clusters might work.

Otherwise you probably need to run a separate CoreDNS and use the [external DNS controller](https://github.com/kubernetes-sigs/external-dns).

You can also look at the example for doing [multicluster-dns](https://github.com/coredns/multicluster-dns) but that also has limited use cases.

/question
/plugin kubernetes
/plugin k8s_external
/plugin kubernetai

**Comment by zhyinjun** [comment]
Yes, these are IP addresses for backend API services in Cluster A.  The cluster B wants to connect those services by using hostname(via private network)

eg. Pod in cluster B wants to access pods(exposed in private network via ingress) in cluster A.

Pod in B ->  Pod in A(https://clusterA.example.com/api1)
Pod in B ->  Pod in A(https://clusterA.example.com/api2)
Pod in B ->  Pod in A(https://clusterA.example.com/api3)

Both Cluster A and Cluster B have the access to the public network.
I have a DNS server on the public network.
I will look at the k8s_external plugin.

**Comment by zhyinjun** [comment]
I resolved this issue by adding three A records in my DNS server on the public network.
```
clusterA A 10.10.10.10
clusterA A 10.10.10.11
clusterA A 10.10.10.12
```
Nothing changes are required in coredns.
