### ISSUE TITLE
Data is not synced when CoreDNS reconnects to kubernetes api server after protracted disconnection

### ISSUE THREAD

**Issue by GsssC** [coredns/coredns#3879]
**What happened**:
For some reason, our project needs to deploy coreDNS away from k8s apiserver , at the same time the network is not reliable. Therefore, we tested whether the event of k8s SVC when the network was disconnected would be detected by CoreDNS after reconnetcion. The result showed that when SVC was deleted during a long period of disconnection from k8s API server, and CoreDNS still had the parsing record of the SVC after reconnection.
**What you expected to happen**:
When CoreDNS is disconnected from API server, SVC is deleted. After reconnection, CoreDNS should not have the parsing record of this SVC
**How to reproduce it (as minimally and precisely as possible)**:
Virtural Machine a : run kubernetes api server
Virtural Machine b : run CoreDNS by binary+systemed
- Short time network failure
1. In a, use kubectl to create a svc relating existing pod
2. In b, use dig  to resolve svc `dig svc.namespace.service.cluster.local @debianIP -p 1053`, successfully return svc vip
3. In b, **shut down** the network of b
4. In a, use kubectl delete svc
5. In a, use kubectl create svc2
6. In b, **resume** the network of b after 1 min
7. In b, use dig to resolve svc , successfully return none
8. Inb, use dig to resolve svc2, successfully return svc2 vip
- Long time network failure
1. In a, use kubectl to create a svc
2. In b, use dig to resolve svc, successfully return svc vip
3. In b, **shut down** the network of b
4. In a, use kubectl delete svc
5. In a, use kubectl create svc2
6. In b, **resume** the network of b after 30 min
7. In b, use dig to resolve svc , **still return svc vip**
8. In b, use dig to resolve svc2, successfully return svc2 vip
**Anything else we need to know?**:
Could this be due to a design flaw in the ListWatch itself?

**Environment**:
- the version of CoreDNS:
- Corefile:
```
.:1053 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           endpoint http://10.10.103.98:8080
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 0
        }
        forward . /etc/resolv.conf
        loop
        reload
        loadbalance
    }
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Data is not synce..." ]
>    Could this be due to a design flaw in the ListWatch itself?

it may well be. We're not doing something strange with this API and there are no hooks for
us to use to know we're not up to date.

**Comment by GsssC** [comment]
@miekg Thanks for reply. Dose coreDNS knows when it is disconnected from the apiserver？ and has a mechanism for reconciling?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Data is not s..." ]
>@miekg Thanks for reply. Dose coreDNS knows when it is disconnected from the
>apiserver？ and has a mechanism for reconciling?

I think the reconnection logic is all handled in the k8s libs, so we don't get to see it.

We had a resync period thing in the kubernetes plugin, but that was removed because it was
causing other issues (can remember exactly).

**Comment by zouyee** [comment]
The problem should be that the watch feature of the client-go missed some events, so some dirty data has left, and the general processing method is periodic traversal processing

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Data is not s..." ]
>The problem should be that the watch feature of the client-go missed some
>events, so some dirty data has left, and the general processing method is
>periodic traversal processing

yeah, it looks like we need to implement something like that; problem is that we don't
know when to trigger a 'full traverse' (or whatever we want to call it).

**Comment by chrisohaver** [comment]
@GsssC, thanks for the reproducible steps.  I have been tracking similar issues down but have been unable to re-create them. These reproducible steps will help.

> yeah, it looks like we need to implement something like that; problem is that we don't
know when to trigger a 'full traverse' (or whatever we want to call it).

client-go is supposed to be handling this automatically for us.  In the past, client-go provided no way of hooking into errors - it does print the errors to standard out, so they show up in our log. However I recently saw some code in master that suggests they may be adding a facility for adding a custom watch error handler.

> We had a resync period thing in the kubernetes plugin

The (perhaps ill-named) `resyncperiod` option in client-go, according to various accounts and code inspection, does not actually retrieve any lost events from the API.  It schedules a periodic client-side reprocessing of all items the client already knows about through the event handlers.  AFAIK, it was removed because it was creating unnecessary processing overhead while providing no apparent benefit in our application.

With a reproducible scenario, I can finally test a few things:
1. I should be able to see what the errors are, if any, upon reconnection in the CoreDNS logs.
2. AFAICT, resyncperiod doesn't retrieve lost items from the API, but the client-go code is very twisty, and perhaps there is something going on there that I'm not seeing.  So, i'll test adding back a resyncperiod to see if that changes things.
3. We use a custom IndexerInformer instead of the default one included in client-go.  This has drifted a bit from the client-go code, and since it was copied from client-go, one of the functions used has since been deprecated.  Looking through the code, I think this is innocuous, but I'll update it and see if it changes anything. Should be updated anyways.

**Comment by chrisohaver** [comment]
@GsssC, I ran through the test above, and was unable to reproduce the described results. 
In short, I did the following with an instance of CoreDNS running locally on my machine connecting to a K8s cluster in a virtual machine:

1. Create service "service1". Validate the service can be queried by name via dns. 
2. Break CoreDNS's connection to the API. Errors immediately begin repeating in CoreDNS log.
3. delete "service1"
4. wait 30 minutes
5. Restore CoreDNS's connection to the API. Errors immediately cease in CoreDNS log.
6. Query for "service1", got NXDOMAIN as expected

I did this twice, with the same result.  Is your failure scenario consistently reproducible in your environment?  What version of CoreDNS are you using? And what version of Kubernetes?

**Comment by GsssC** [comment]
@chrisohaver Thanks. 
CoreDNS-1.6.9，kubernetes  v1.17.1，how about yours? 
At the same time, we will do more tests in different envrionment.

**Comment by Poor12** [comment]
Hello，I do the same thing but return the same result. When long time network failure, still return deleted svc vip. environment: CoreDns-1.6.9, kubernetes v1.17.4. This is strange.@chrisohaver @GsssC

**Comment by chrisohaver** [comment]
Thanks. I tried CoreDNS at master, which I think has a slightly newer version of client-go (k8s api client lib) than 1.6.9.  I'll try on 1.6.9 today.  The cluster I used was at 1.15.  If I can't reproduce the results with CoreDNS 1.6.9, I'll try on 1.17 Kubernetes.

**Comment by chrisohaver** [comment]
I was unable to reproduce the issue for CoreDNS 1.6.9 for ClusterIP services (i'm assuming you are testing with normal services, since you have not mentioned "headless").  But there was a difference...

Curiously, I saw the client-go stack-trace log reported in #3860 upon reconnection.  After seeing that error logged, I created a _headless_ service with a static endpoint and was able to replicate the behavior described in https://github.com/coredns/coredns/issues/3860#issuecomment-620870161 - that CoreDNS ceases receiving updates for endpoints after this error appears in the log (affecting headless services, but not ClusterIP services). I confirmed that another instance of CoreDNS that did not have its connection interrupted replied correctly for the new headless service.

**Comment by chrisohaver** [comment]
Unfortunately,  I'm unable to reproduce the stack-trace/endpoint issue above consistently (only saw it in one test).  So may not be related to CoreDNS version at all.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Data is not s..." ]
>I was unable to reproduce the issue for CoreDNS 1.6.9 for ClusterIP services
>(i'm assuming you are testing with normal services, since you have not
>mentioned "headless"). But there was a difference...
>
>Curiously, I saw the client-go stack-trace log reported in #3860 upon
>reconnection. After seeing that error logged, I created a headless service with
>a static endpoint and was able to replicate the behavior described in #3860
>(comment) - that CoreDNS ceases receiving updates for endpoints after this
>error appears in the log (affecting headless services, but not ClusterIP
>services). I confirmed that another instance of CoreDNS that did not have its
>connection interrupted replied correctly for the new headless service.

hopefully asking the question: were you able to capture the strace?

**Comment by chrisohaver** [comment]
yes, I saved it.  It's the same as the one in the edit history of #3860. i'll reopen #3860 and record it there, since it does not cause the behavior described in this issue.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Data is not s..." ]
>yes, I saved it. It's the same as the one in the edit history of #3860. i'll
>reopen #3860 and record it there, since it does not cause the behavior
>described in this issue.

hmm :-( are we hitting a race somewhere?

**Comment by chrisohaver** [comment]
@GsssC, do you still see your issue with CoreDNS built at master (now that #3887 and #3890 are merged)?

**Comment by GsssC** [comment]
Thx，I will test tomorrow 。

**Comment by nickasam** [comment]
> @GsssC, do you still see your issue with CoreDNS built at master (now that #3887 and #3890 are merged)?


Hello @chrisohaver @GsssC （My colleagues）  , I am using coredns master branch in the environment of kubernetes1.17.3. The service that has been deleted when the network is still disconnected for a long time can still be resolved by coredns after the network is restored.

1. Create service
2. Unplug the network cable
3. Change service：delete svc1，create svc2
4. Restore the network after 30mins
5. nslookup svc1 success,nslookup svc2 success
ps:  coredns tolerate node notready

**Comment by chrisohaver** [comment]
@zheng199512, Do the CoreDNS logs show any errors?

**Comment by nickasam** [comment]
sorry，i forgot. @chrisohaver 
![coredns-error](https://user-images.githubusercontent.com/29241175/82921992-a3875200-9fab-11ea-8df5-a309bc096e5c.png)

**Comment by chrisohaver** [comment]
@zheng199512, Can you share the info at the beginning of the CoreDNS log, to verify what commit you are using?  e.g. 

```
.:53
CoreDNS-1.6.9
linux/amd64, go1.13.6, bc2ba2886
```

**Comment by zheng199512** [comment]
I will use the latest branch to test again, because it was used last time but there is no screenshot.  I will confirm tomorrow which release version has the picture error.

**Comment by chrisohaver** [comment]
>  it was used last time but there is no screenshot.

Though it is somewhat blurry and difficult to read, the line numbers in the stack trace suggests a commit prior to the fixes was running.

**Comment by nickasam** [comment]
@chrisohaver 
the master branch (i built a image six days ago)
![image](https://user-images.githubusercontent.com/29241175/82971769-10c7d100-a006-11ea-9443-4e48c205565f.png)

![image](https://user-images.githubusercontent.com/29241175/82971621-aca50d00-a005-11ea-956d-38659aec4c07.png)

![image](https://user-images.githubusercontent.com/29241175/82971605-a44cd200-a005-11ea-873c-9ea7cd06d497.png)

the relase 1.6.9
![image](https://user-images.githubusercontent.com/29241175/82972298-4b7e3900-a007-11ea-8cb3-fed449510329.png)

**Comment by chrisohaver** [comment]
@zheng199512, Thanks, I assume that the series of screen shots is intended to show that you don't see a stack trace upon api reconnect with a version compiled at c9c21270, but you do see a stack trace at the 1.6.9 release, which confirms  #3860.

Was the svc1 deletion properly handled by coredns with the c9c21270 build?

**Comment by nickasam** [comment]
![image](https://user-images.githubusercontent.com/29241175/83031828-a9db0400-a067-11ea-8815-e1f12978b65b.png)

no, svc1 (nginx-test-helm-hello-helm) is deleted,but nslookup svc1(nginx-test-helm-hello-helm) get a result.

**Comment by johnbelamaric** [comment]
How long after the reconnect did you do the queries? The sync will not be
instantaneous.

**Comment by chrisohaver** [comment]
Ah ha! I just noticed a difference in the error messages - In my scenario the way I am interrupting the API connection causes a "connection refused" response, and in @zheng199512's case, the error is "no route to host".  That would seem innocuous, but digging into the k8s client-go code, I see it actually handles these types of disconnects differently. 

When the error is anything other than "connection refused", the Informer returns an error and starts over with an exponential backoff,  whereas for "connection refused" errors, it just tries to re-establish the watch every second (no backoff).  So, it's possible that after 30 minutes the exponential backoff has reached a high enough interval such that it takes considerable time after the connection is restored before the api client attempts to reconnect.

~I'm looking into implementing a kind of "give up and die" behavior for when the kubernetes plugin cannot connect to the API for an extended period of time.~

**Comment by chrisohaver** [comment]
> So, it's possible that after 30 minutes the exponential backoff has reached a high enough interval such that it takes considerable time after the connection is restored before the api client attempts to reconnect.

FYI, Looks like the max backoff duration is 30 seconds, and it resets every 2 minutes... So try waiting 30 seconds after restoring API connection to see if that changes things.

**Comment by nickasam** [comment]
The computer resumed the network at about 11 am（02:30 +8:00）, and it is now 1 am. It still has this error.
![image](https://user-images.githubusercontent.com/29241175/83050267-e23a0c80-a07e-11ea-87e8-d52d63c769d2.png)

**Comment by chrisohaver** [comment]
When I modify client-go to treat "connection refused" just like any other network error (re-list and rewatch, instead of just re-watch), services deleted during the 30 minute outage are _not_ deleted from the client-go cache.  I tested up to 10 minutes after connection restoration.

So this seems to be some interaction in client-go with re-listing onto an existing cache, which I plan to dive into more this week.

**Comment by chrisohaver** [comment]
I see whats going on. The object imbedded in a tombstone is a different type than normal delete event objects.  This is due to the fact that we store trimmed down objects to cache. The objects imbedded in the tombstones are copies from the local cache, not from the api server.  

Verifying the fix now ...

**Comment by miekg** [comment]
think this is fixed and debugged.
