### ISSUE TITLE
plugin/cache: serve_stale enhancements

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4199]
A recent discussion let me look into serve_stale in cache and it you must specify a duration which you need to figure out manually. Btw the discussion was how fast a k8s cluster breaks when the control plane goes down, coredns was fingered as one of the things the makes it go down more quickly. 

Another approach is when serve_stale is active to check the response from whatever the upstream is and if it's not an answer (like the thing we cached before, or potentially a new reply all together), we reply with the old one. This mimics "last-known-good-behavior" which is a good strategy for surviving outages. It's also more dynamic, doesn't require a duration option and may be actually be "on" by default.

**Comment by bharath-123** [comment]
k8s 1.18 has made node local dns stable.[nodelocaldns](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/)  it seems like its coredns on every node now. If the coredns deployment goes down for some reason, every node will have a node local dns cache which can serve them.

I feel that ideally, the node local coredns should not share configmaps with the cluster wide coredns deployment. So hopefully it does not go down due to a bad config in the main coredns. 

But with this i think that, if a node with the main coredns pods goes down things should still be fine because the node local dns cache can serve requests __if__ they are still in the cache.

What do you think?

**Comment by chrisohaver** [comment]
> I feel that ideally, the node local coredns should not share configmaps with the cluster wide coredns deployment.

They don't.  They have their own config map, different than the cluster dns deployment.

> What do you think?

I think the current serve stale implementation does what you are hinting at.  To continue to serve stale cache entries beyond their original TTL when the upstream (cluster DNS deployment), is down.

**Comment by chrisohaver** [comment]
#5131 implements what I think is described in this issue.

i.e. it checks upstream first, if no answer then reply with old (stale) cached entry.
