### ISSUE TITLE
Config.Handlers is not ordered

### ISSUE THREAD

**Issue by davy-tw** [coredns/coredns#4210]
**What happened**: According to the comment of Config.Handlers (https://github.com/coredns/coredns/blob/279194f2e4/core/dnsserver/register.go#L185):
> // Note that this is order dependent and the order is defined in directives.go

But in golang, map does not maintain the insertion order, so the result of Config.Handlers is un-ordered.

**What you expected to happen**:

The result of Config.Handlers should be ordered with directives.go (plugin.cfg)

**How to reproduce it (as minimally and precisely as possible)**:

Just apply two transfer-supported plugins into same server block and enable transfer, than you can see the order of pluginChain is different from transfer.Transferer list.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: master (1f07f7d)
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by davy-tw** [comment]
And the possible solution can be:

```diff
diff --git a/core/dnsserver/register.go b/core/dnsserver/register.go
index b4e9f4fd..4506bf49 100644
--- a/core/dnsserver/register.go
+++ b/core/dnsserver/register.go
@@ -189,8 +189,10 @@ func (c *Config) Handlers() []plugin.Handler {
                return nil
        }
        hs := make([]plugin.Handler, 0, len(c.registry))
-       for k := range c.registry {
-               hs = append(hs, c.registry[k])
+       for _, k := range Directives {
+               if h, ok := c.registry[k]; ok {
+                       hs = append(hs, h)
+               }
        }
        return hs
 }
```

**Comment by yzwdroid** [comment]
Is it already solved? If not, can I give it a try?

**Comment by miekg** [comment]
I fail to see what needs to be solved here. If there is a specific bug please create one.

/close

**Comment by davy-tw** [comment]
@miekg according to the comment of `Config.Handlers`, the return list should follow the order in directives.go (plugin.cfg), but the result is not ordered.

If you think this is not a bug, maybe we should fix the comment of that function?

**Comment by davy-tw** [comment]
@miekg the reproduce commit is here:
https://github.com/david50407/coredns/commit/0892630fc1767db627b371d3e799d8d5bf04a6a7

Just `make` and run `./coredns --conf Corefile --dns.port 1053` and you will get:

```
[WARNING] plugin/auto: Directory does not exist: ./empty
[INFO] plugin/thebug: Listing Handlers, this should match the order in plugin.cfg:
[INFO] plugin/thebug: > Handler: auto
[INFO] plugin/thebug: > Handler: thebug
.:1053
CoreDNS-1.7.1
linux/amd64, go1.15, 1f07f7dd-dirty
```

Notice that `auto` is before `thebug`, but in `plugin.cfg`, the order of `thebug` is right above `auto`.
So the result of `Config.Handlers()` is not ordered with `plugin.cfg`.

**Comment by chrisohaver** [comment]
I understand that the data structure is not ordered. What actual user facing problem does this cause? Can you give an example of a configuration, and show that a wrong DNS answer to a client is produced by that configuration?

**Comment by chrisohaver** [comment]
I thought of one...  I think an issue could occur with the transfer plugin, and transfer-capable plugins that allow `fallthrough`.  In that situation, two plugins can serve the same domain.  Transfer, IIRC, would call transfer functions on the "first" plugin matching the domain in the Handlers list, but since Handlers is not ordered, "first" plugin is not necessarily based on the order of plugins in `plugin.cfg`.  i.e. A client might get a transfer response from the second plugin instead of the first.

FWIW, the proposed [k8s_api plugin](#4157) has the same problem for handling watch overrides.

**Comment by davy-tw** [comment]
@chrisohaver you're right! That is the problem I'm facing, so I found the problem is from the order of Handlers is not as same as pluginChain

**Comment by chrisohaver** [comment]
Given the default plugins - I can only see a very corner case where this causes an outward issue:  Where _transfer_ is used on a zone "shared" by two plugins via `fallthrough`.  IMO, that kind of set up is ill-advised anyways, because even if _transfer_ always transferred the first plugin based on plugin execution order, the transfer would be incomplete because it would not include the fallthrough records.  This limitation is known.  `fallthrough` complicates things.  Perhaps ideally _transfer_ should get the records of each plugin matching the zone, and merge them together into a single zone transfer response, so all records are represented.  ~Although if it did that, the order of `Handlers` would not matter.~ (edit: actually - yes it would still matter if there is record name overlap)

The only way this can happen currently with _transfer_ is with _kubernetes_ falling through to _file/auto/secondary_.  Is there a legitimate use case there?

The docs are perhaps unclear, especially when taken out of context as done above. They state that the result of Handlers is "order dependent", "not ordered".  The full text is:

> // Note that this is order dependent and the order is defined in directives.go, i.e. if your plugin
> // comes before the plugin you are checking; it will not be there (yet).

The second sentence provides important clarification. This is why most plugins that look at Handlers do so in an `OnStartup` hook which is called _after_ all plugins have registered - otherwise the list would only contain the plugins that registered _before_ the current plugin.

**Nevertheless, the proposed fix seems like a harmless change, and would protect against future plugins that make the incorrect assumption that plugin list returned by Handlers list itself is ordered.**

**Comment by davy-tw** [comment]
@chrisohaver thanks for the explanation.

In my case, I'm writing a plugin which will inject and rewrite the answer (including XFR) from next plugin for internal usage.

My plugin implements `plugin.Handler` and `transfer.Transferer`, handles requests and pass requests to next plugin then modify the answers. This causes the issue: my plugin gets higher order of execution, but transfer picks another plugin :( and causes my plugin cannot correctly inject and rewrite the response for transfer.

If this change can be applied, please let me know, thanks.

**Comment by chrisohaver** [comment]
Thank you for describing your case.  Interesting approach!  It's like a "transferer proxy".

A possible alternate approach instead of your solution above: You might be able to wrap a ResponseWriter that instead of writing to the client in WriteMsg, saves the message to a slice of messages (something like this exists in test cases named ResponseRecorder or something like that IIRC). In ServerDNS, your plugin would wrap the incoming ResponseWriter with the new wrapper and call next plugin.  When the answer is returned, your plugin could examine/modify the messages and write them to the client using the original ResponseWriter.

>If this change can be applied, please let me know, thanks.

IMO, the change seems reasonable.  I don't think it would impact performance.  Typically plugin.Handlers is only called at startup or during setup. @miekg WDYT?

**Comment by miekg** [comment]
This doesn't need code changes in this area. There is always 1 plugin responsible for a
zone and this is why fallthrough is a hack (a sometimes handy one, but still a hack).

Plugin are, and should be oblivious to any ordering.

What may be needed here is that a plugin can possible tell *transfer* it is not
responsible for zone, by always returning `transfer.ErrNotAuthoritative`, but this
requires an option in all plugins that support tranfers, and this to support a very thin
usecase...
