### ISSUE TITLE
coredns startup and throw error 'read  node dns adress i/o timeout'

### ISSUE THREAD

**Issue by Jiangting1** [coredns/coredns#4211]
version 1.6.7
error
[ERROR] plugin/errors: 2 3797952284163317497.7063757873447144811. HINFO: read udp 192.168.209.17:36807->20.128.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 3797952284163317497.7063757873447144811. HINFO: read udp 192.168.209.17:35090->20.128.8.8:53: i/o timeout
coredns ip 192.168.209.17
node dns:20.128.8.8
other features: pod in cluster can normal know addresses in both cluster or outside cluster
and coredns pod can reach dns server
question：how to solve the the error of coredns

**Comment by chrisohaver** [comment]
The loop plugin sends HINFO type requests with a random number domain to the upstream DNS to determine if there is a forwarding loop.  The error indicates that the upatream does not respond to that request.  You could test manually by sending the queries directly to same upstream that CoreDNS uses.  e.g. 
```
dig @20.128.8.8 -t HINFO 3797952284163317497.7063757873447144811.
```

If this is expected behavior of your upstream, and you are confident you don't have a forwarding loop, then you may remove the loop plugin from your Corefile.

**Comment by Jiangting1** [comment]
> The loop plugin sends HINFO type requests with a random number domain to the upstream DNS to determine if there is a forwarding loop. The error indicates that the upatream does not respond to that request. You could test manually by sending the queries directly to same upstream that CoreDNS uses. e.g.
> 
> ```
> dig @20.128.8.8 -t HINFO 3797952284163317497.7063757873447144811.
> ```
> 
> If this is expected behavior of your upstream, and you are confident you don't have a forwarding loop, then you may remove the loop plugin from your Corefile.

if I can ignore these error? Will any  bad effects occure?

**Comment by chrisohaver** [comment]
> if I can ignore these error? Will any bad effects occure?

If you can make queries to CoreDNS for domains that CoreDNS will forward upstream, and you get an answer, then I'd guess that either your upstream either doesn't respond to HINFO requests or it doesn't respond to queries for randomly formed domains. If so, you can probably ignore the error.
