### ISSUE TITLE
Feature request: DNS64

### ISSUE THREAD

**Issue by RichiH** [coredns/coredns#429]
It would be nice if CoreDNS supported https://en.wikipedia.org/wiki/IPv6_transition_mechanism#DNS64 / https://tools.ietf.org/html/rfc6147 .

**Comment by miekg** [comment]
That should be a small contained middleware. Little bit concerned about "when asked for a domain's AAAA records, but only finds A records", which means doubling the amount of queries.

**Comment by RichiH** [comment]
Why is this a concern? It's part of how the designed system works.

This is only used with NAT64, i.e. in well-contained networks; usually eyeball ones.

**Comment by miekg** [comment]
Do you have time to work on this feature?

**Comment by miekg** [comment]
#432 should provide a nice starting point - but I might finish it over the weekend :)

**Comment by RichiH** [comment]
@miekg JFTR, no, I won't. But great that you do :)

**Comment by miekg** [comment]
nobody is working on this

**Comment by fturib** [comment]
When you work on Ipv6 only env, you need a NAT64 and a DNS64. Right now in Docker-in-Docker, this DNS64 function is provided by bind9. Is there a place for CoreDNS here ?

Does it make sense to reopened this issue ?. 
NOTE: Looking at the code of PR #432 , it is not really implemented. We need to have the Ipv6 prefix in order to translate IP of the A Record into an IP of AAAA Record.

**Comment by serverwentdown** [comment]
should the plugin modify the request being sent out or should it behave entirely like proxy?

**Comment by serverwentdown** [comment]
i'm working on an initial version of the plugin (based on #432) that modifies the request being sent out, but to perform the second lookup of A records, i have to maintain my own `proxy.Proxy` and second `upstream`. 

https://github.com/serverwentdown/dns64
have not read the spec yet, and still need to write tests for dns64.go

**Comment by fturib** [comment]
@serverwentdown : I see the plugin is all done already ... !! Great !

I am not sure how much options we want to support. Here is a doc of DNS64 support by BIND described here :
https://www.safaribooksonline.com/library/view/dns-and-bind/9781449308025/ch04.html

Then I have the following questions (I have not the reply myself)

1- do we want to support the reverse mapping ? - I guess that make sense.
2- options clients / mapped / excluded ? - I am not sure here.

For my usage (I am testing  a K8's server in a cluster Ipv6 only), we could use CoreDNS with this plugin DNS64 instead of bind9 - I am not wrong-. 

I guess the current version, should work ... I am not sure I would need the reverse mapping.

**Comment by serverwentdown** [comment]
that would require inserting a custom response when the reverse plugin is used. i may look into that sometime. https://tools.ietf.org/html/rfc6147#section-5.3.1

**Comment by miekg** [comment]
https://coredns.io/explugins/dns64/

**Comment by RichiH** [comment]
Thanks!
