### ISSUE TITLE
 Enables server-side domain search path completion for pods running in the host network 

### ISSUE THREAD

**Issue by htgeis** [coredns/coredns#4299]
**What would you like to be added**:
Currently, we could use autopath plugin together with kubernetes plugin to enable the server-side domain search path completion in Kubernetes clusters. However, it doesn't support the pods running in the host network due to no private ip.
Is there any ideas to support it? Is it reasonable to get search path from the dns request directly? The reason we need the private ip is to find the namespace a pod running in. However, we may get it from the dns request(e.g. XX.namespaces.svc.cluster.local) and we could check whether it existed or not in kubernetes cluster also.

**Why is this needed**:
 It would reduce the latency of the external domain name resolution for the pods running in the host network and in many scenarios, it needs to run the container in host mode.

**Comment by johnbelamaric** [comment]
Presumably this is for Pods with explicit DNS policy `ClusterFirstWithHostNet`? One option would be to watch Nodes; if we see a source IP of a node IP address, just use the non-namespace specific part of the search path, rather than just aborting which is what we do now, IIRC. I have not thought through the other implications of that though.

You can't reliably infer the namespace of the Pod from the DNS request - any pod could request a DNS name in any namespace.

My preferred solution would need a new RFC for autopath. We could implement adding the search path in an EDNS option, and what would be really cool would be to update resolv.conf to be able to set that option. This would be universal across all DNS resolvers rather than just for Kubernetes.

@miekg want to write a new RFC with me?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns]  Enables serv..." ]
>Presumably this is for Pods with explicit DNS policy ClusterFirstWithHostNet?
>One option would be to watch Nodes; if we see a source IP of a node IP address,
>just use the non-namespace specific part of the search path, rather than just
>aborting which is what we do now, IIRC. I have not thought through the other
>implications of that though.
>
>You can't reliably infer the namespace of the Pod from the DNS request - any
>pod could request a DNS name in any namespace.
>
>My preferred solution would need a new RFC for autopath. We could implement
>adding the search path in an EDNS option, and what would be really cool would
>be to update resolv.conf to be able to set that option. This would be universal
>across all DNS resolvers rather than just for Kubernetes.
>
>@miekg want to write a new RFC with me?

that sounds like fun! :)

Note there is a private range (IIRC) where we can just do this, but reserving a codepoint
seems like a nice exercise.

/Miek

--
Miek Gieben

**Comment by johnbelamaric** [comment]
If we ever want it in resolv.conf it needs to be reserved and accepted as an RFC, I assume.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns]  Enables serv..." ]
>If we ever want it in resolv.conf it needs to be reserved and accepted as an
>RFC, I assume.

the IETF doesn't deal with /etc/resolv.conf, but with nodelocaldns we don't really care,
we can just inject the option.

Assuming it's nothing more then an EDNS0 code point and a list of domain names attached to
it (with some maxium)

/Miek

--
Miek Gieben
