### ISSUE TITLE
coredns error

### ISSUE THREAD

**Issue by misteruly** [coredns/coredns#4311]
###  image :coredns/coredns:1.6.9

error:
loading Caddyfile via flag: open /etc/coredns/Corefile: no such file or directory

What's the solution?

**Comment by zouyee** [comment]
When you use the configuration command line, please make sure the configuration file exists.

**Comment by misteruly** [comment]
This is the official mirror package, it must exist

**Comment by anandpartha** [comment]
I suppose this is due to an error during coredns upgrade. During upgrade, the CoreFile mount path is not correct and hence its not able to find the file when coredns starts.

Editing the coredns deployment so that we are have volumes section list "Corefile" instead of the "Corefile-Backup" key fixes this.

Hope that helps.

**Comment by chrisohaver** [comment]
> I suppose this is due to an error during coredns upgrade. During upgrade, the CoreFile mount path is not correct and hence its not able to find the file when coredns starts.
> Editing the coredns deployment so that we are have volumes section list "Corefile" instead of the "Corefile-Backup" key fixes this.

That would be in the context of using _kubeadm_ upgrade.

Although the image path here is `coredns/coredns:1.6.9`, and presumably this is what the coredns deployment is using.  Kubeadm uses the k8s.gcr.io repo instead of dockerhub, which kind of hints that coredns was deployed in some other way.

There really is minimal information in this issue, so it's hard to guess.
