### ISSUE TITLE
How to efficiently monitor CoreDNS reload failure?

### ISSUE THREAD

**Issue by Kenshir0** [coredns/coredns#4342]
Hi,

I am trying to write Prometheus alerting rules based on **coredns_reload_failed_total** metric introduced by https://github.com/coredns/coredns/issues/2920. 

I'm probably missing something here, but my understanding is that **coredns_reload_failed_total** metric is not sufficient on its own:  it allows one to detect reload failures, but not to detect when the config has been fixed and the last reload succeeded.

As an administrator I just want to answer the question: "Was the last reload successfull or not?", and trigger/recover alerts based on the answer. Maybe a **coredns_last_reload_successful** metric would make sense.

Best,

**Comment by chrisohaver** [comment]
Three states can be inferred from the existing metrics, `coredns_reload_version_info` and `coredns_reload_failed_total`:
* reload succeeded: if `coredns_reload_version_info` reflects the new config
* reload failed: if `coredns_reload_failed_total ` increments
* reload hasn't happened yet: if neither metric changes

**Comment by Kenshir0** [comment]
Thanks for your answer.

While I get your point, it's still unclear to me how to achieve this. 

@chrisohaver Could you please provide an example of alerting rule or a PromQL query? Thank you.

**Comment by chrisohaver** [comment]
I'm not a PromQL aficionado, but I think the following could work: 
1. create recording rules similar to the `last_update` example suggested in https://stackoverflow.com/questions/54148451/get-time-that-passed-since-the-last-increase-of-prometheus-counter. One called `last_successful_reload` that uses`coredns_reload_version_info` and another called `last_failed_reload` that uses `coredns_reload_failed_total`
2. create an alert that compares the two dates. i.e. alert if `last_failed_reload` >  `last_successful_reload`

**Comment by pacoxu** [comment]
Current metrics: we cannot tell if the current configuration is correct directly.
```
coredns_reload_failed_total 2
coredns_reload_version_info{hash="md5",value="384de8452dd2354951fd9a976bbd8f80"} 1
```

Does something like the below make sense? Add status for the current version info.
```
coredns_reload_failed_total 2
coredns_reload_version_info{hash="md5",value="384de8452dd2354951fd9a976bbd8f80",status='fail'} 1
```

Another way is setting the value to 1 for `ok` and 0 for `fail`
```
coredns_reload_failed_total 2
coredns_reload_version_info{hash="md5",value="e1a4295f517851803bf32360813e848d"} 0
```
