### ISSUE TITLE
CNAME need not be followed after a synthesized CNAME for a CNAME query

### ISSUE THREAD

**Issue by SivaKesava1** [coredns/coredns#4398]
Hi again,

A synthesized `CNAME` record is a perfect answer for a `CNAME` query and need not be followed. 

Consider these cases, 
|                    |           |                                                          |
|--------------------|-----------|----------------------------------------------------------|
|uni.net.        | 500  SOA  | ns1.uni.net. root.campus.edu. 3 86400 7200 604800 300 |
| *.uni.net.        | 500  CNAME   | ww.uni.net.                                         |
| ww.uni.net.    | 500 CNAME | ww.campus.edu.                                          |
| test.uni.net.    | 500 CNAME | ww.uni.net.                                          |

For the query, `< test.uni.net., CNAME>` CoreDNS returns the last `CNAME` records and **stops**. But for the query `<foo.uni.net, CNAME>` CoreDNS synthesizes a `CNAME` record from the wildcard record and then again **follows** it. The response was as follows:
```
          ";QUESTION",
          "foo.uni.net. IN CNAME",
          ";ANSWER",
          "foo.uni.net. 500 IN CNAME ww.uni.net.",
          "ww.uni.net. 500 IN CNAME ww.campus.edu.",
```

The processing should have been the same for both cases.

**Comment by bkrugerp99** [comment]
Real world example?  (inside a container)

```
# nslookup dl-cdn.alpinelinux.org
Server:		10.100.0.10
Address:	10.100.0.10#53
Non-authoritative answer:
dl-cdn.alpinelinux.org.default.svc.cluster.local	canonical name = dl-cdn.alpinelinux.org.
dl-cdn.alpinelinux.org	canonical name = dualstack.d.sni.global.fastly.net.
Name:	dualstack.d.sni.global.fastly.net
Address: 151.101.54.133
** server can't find dualstack.d.sni.global.fastly.net: NXDOMAIN
```

**Comment by ykhr53** [comment]
I can reproduce the behaviour.
Root cause is in the `externalLookup` function, CNAME RR (in this case, "ww.uni.net. 500 IN CNAME ww.campus.edu.") will be added to `rrs` which will be returned to a client.
https://github.com/coredns/coredns/blob/master/plugin/file/lookup.go#L333

The reason why we don't get this additional answer on `test.uni.net` is, we don't call `externalLookup` for non-wildcard RRs. Please check the differences.

The case we found entire name:
https://github.com/coredns/coredns/blob/9026a4a295efa216f79e80dd7c544fcf0001ed27/plugin/file/lookup.go#L169

The case we found wildcard:
https://github.com/coredns/coredns/blob/9026a4a295efa216f79e80dd7c544fcf0001ed27/plugin/file/lookup.go#L206

I think we can safe to add `&& qtype != dns.TypeCNAME` condition as it was added in order to support CNAME chain in this commit.
https://github.com/coredns/coredns/commit/4ef53081c536a66acf77c7b1e3df15c2fc0ca52b

**Comment by SivaKesava1** [comment]
Thanks, @ykhr53, for sending the PR. 

There is one more corner case involving DNAMEs - If the query is for a CNAME type and a DNAME is used, then a CNAME record will be synthesized, and the processing should stop there. Can you also check that with your fix that case is also handled?

More details - https://github.com/PowerDNS/pdns/issues/9886 https://github.com/NLnetLabs/nsd/issues/148

**Comment by ykhr53** [comment]
Thanks for the quick reply @SivaKesava1.
I'll read issues you provided and dig some related RFCs.
Before I check or implement the cases, could you provide some sample cases (RRs, expected answer) specifically you have concern with?
Thanks!

**Comment by SivaKesava1** [comment]
Consider the following sample zone file:
|                    |           |                                                          |
|--------------------|-----------|----------------------------------------------------------|
| campus.edu.        | 500  SOA  | ns1.campus.edu. root.campus.edu. 3 86400 7200 604800 300 |
| campus.edu.        | 500  NS   | ns1.outside.edu.                                         |
| c.d.campus.edu.    | 500 DNAME | f.d.campus.edu.                                          |
| foo.f.d.campus.edu.    | 500 CNAME | done.campus.edu.                                          |
| done.campus.edu.    | 500 A|1.1.1.1                                         |

For the query `<foo.c.d.campus.edu., CNAME>` the answer should be :
```
       "opcode QUERY",
          "rcode NOERROR",
          "flags QR AA",
          ";QUESTION",
          "foo.c.d.campus.edu. IN CNAME",
          ";ANSWER",
          "c.d.campus.edu. 500 IN DNAME f.d.campus.edu.",
          "foo.c.d.campus.edu. 500 IN CNAME foo.f.d.campus.edu.",
          ";AUTHORITY",
          ";ADDITIONAL"
```

The processing should stop with the synthesized CNAME and not add the `foo.f.d.campus.edu.  500 CNAME done.campus.edu.` record to the response.

**Comment by ykhr53** [comment]
Thanks. Seems like I have to modify the PR. I'm working on it.

**Comment by ykhr53** [comment]
That is also caused by `externalLookup` under the `synthesizeCNAME`
https://github.com/coredns/coredns/blob/9026a4a295efa216f79e80dd7c544fcf0001ed27/plugin/file/lookup.go#L119

Updated the PR by simply adding a condition to check a query type.
Also I refered RFC 6672 for the synthesized CNAME requirement.
https://datatracker.ietf.org/doc/html/rfc6672#section-3.2

**Comment by ykhr53** [comment]
Resolving it per https://github.com/coredns/coredns/pull/4828
