### ISSUE TITLE
Add support for json logging

### ISSUE THREAD

**Issue by uthark** [coredns/coredns#4460]
**What would you like to be added**:

* Ability to configure logging to JSON.

**Why is this needed**:
* would simplify integration with third party logging systems.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Add support for j..." ]
>What would you like to be added:
>
>  • Ability to configure logging to JSON.
>
>Why is this needed:
>
>  • would simplify integration with third party logging systems.

you can wrap the output in some json yourself before giving it to your logging system.

there is no need to do this in the log plugin

/close

**Comment by dajudge** [comment]
@miekg A lot of modern log-shipping systems rely on JSON formatted log output to avoid the hassles of parsing arbitrarily formatted plaintext logging. Introducing the option to output JSON formatted log entries directly from applications on the other hand usually does not require unreasonable amounts of work on their side.

Not offering that option in a cloud native application like CoreDNS seems like an odd decision to me.

Would you be open for a contribution to CoreDNS in that regard?

**Comment by yongtang** [comment]
@dajudge formats such as JSON in logging essentially is just a layer of serialization/deserialization to the log messages. The conversion can be easily done with dedicated log processors (which may already exist in your infrastructure). Have you looked into tools such as Fluentd/Fluent-bit?

**Comment by dajudge** [comment]
@yongtang thank you for your response.

we are already parsing plaintext logs from some other archaic tools that are not supporting JSON formatted logging output. but it's always a hassle, especially when things like stack traces, multiline log entries etc. come into play: plaintext formatted output usually is prone to this kind of parsing problems.

JSON is a format that allows easy and generic parsing of log entries w/o the mentioned difficulties, which I guess is why a lot of modern cloud native tools offer easy options to switch to JSON formatted logging output.

for some open source runtime components that did not support JSON formatted logging we were able to successfully contribute the required enhancements. hence the question in my first post if the CoreDNS project would be open for a contribution (probably the log plugin?) in that regard.

**Comment by yongtang** [comment]
@dajudge I think multi-line support could a fair point. But I am not so sure about structured logging.

I had quite some experience with logrus when working on another project. The `log.WithFields` in logrus looks pretty initially. However, it quickly becomes a source of confusion among contributors: without a strictly predefined RFC/Standard and a way to automatically generate the code itself, different contributors puts different `log.WithFields` in different ways and the whole point of structured logging became unclear.

To coredns's logging, I think coredns only want to maintain one logging system, and we probably don't want to rewrite every log.Warn/Error etc instances within the current codebase. The default way (the way delivered by default binary build of coredns) may very well remain the same.

However, if there is a way to make some changes in `coredns/plugin/pkg/log/log.go` so that users can rebuild coredns binary on their own with a different logging backend, that might be something we could consider.

/cc @miekg for insight.

**Comment by miekg** [comment]
https://github.com/coredns/coredns/issues/4460#issuecomment-777236785
