### ISSUE TITLE
Forwarding does not pass original client ip hence acl checks fail

### ISSUE THREAD

**Issue by jatinn** [coredns/coredns#4495]
Hi so what I want to accomplish is to serve different ip for the same record based on which subnet the request comes from. My attempt was to use forward, acl & alternate to test this out.

Minimal example Corefile
```
.:8053 {
	forward . 127.0.0.1:5301
	alternate original REFUSED . 127.0.0.1:5302
	log
}

.:5301 {
	acl example.org {
		allow net 192.168.20.0/24
		block
	}
	hosts {
		192.168.20.1 test.example.org
	}
	log
}

.:5302 {
	acl example.org {
		allow net 172.16.30.0/24
		block
	}
	hosts {
		172.16.30.1 test.example.org
	}
	log
}
```

When I make a request like
```
dig @[coredns-ip] -p 8053 test.example.org
```
In the coredns logs I see
```
[INFO] 127.0.0.1:49551 - 25937 "A IN test.example.org. udp 45 false 4096" REFUSED qr,rd 34 0.000068764s
[INFO] 127.0.0.1:54253 - 25937 "A IN test.example.org. udp 45 false 4096" REFUSED qr,rd 34 0.000064456s
[INFO] 192.168.20.3:12345 - 25937 "A IN test.example.org. udp 45 false 4096" REFUSED qr,rd 45 0.000599758s
```

However same `dig` call to port `5301` works as expected.

So what I believe is happening is that the forwarded requests see localhost as the client instead of the original client ip, hence getting refused by the acl.

Not sure if this is the expected behaviour or a bug? If expected, is there a way to accomplish this?

**Comment by chrisohaver** [comment]
This is essentially called split DNS - or split horizon DNS.  Using _alternate_ and _acl_ like that is a clever approach. But due to the way forward works, it doesn't work in the end. 

By design, _forward_ acts as a DNS proxy. It makes DNS calls and receives responses on behalf of the client.  So it's expected that the source ip is of CoreDNS - otherwise CoreDNS would not receive the response.

There is no in-tree solution for split horizon DNS.  There have been a few [ideas/proposals](https://github.com/coredns/coredns/issues/2833) on how to implement it, though none have thus far have been adopted.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Forwarding does n..." ]
>Hi so what I want to accomplish is to serve different ip for the same record
>based on which subnet the request comes from. My attempt was to use forward,
>acl & alternate to test this out.

it's super trivial to just run 2 instances and have it point to different configs.

**Comment by jatinn** [comment]
🆒 Thanks for taking a look.
