### ISSUE TITLE
Allow fallthrough for file and secondary

### ISSUE THREAD

**Issue by vlcty** [coredns/coredns#4773]
**What would you like to be added**:

Fallthrough support for file and secondary plugin. This has already been partly discussed in issue #4444.

**Why is this needed**:

Assume you have a /64 IPv6 network you want to generate PTR records on the fly except for some known hosts. Example:

- Network: 2001:db8::/64
- Known host: 201:db8::5 -> whatever.hostname.tld
- For every other host a generic PTR should be generated

A sample Corefile:

```
8.b.d.1.0.0.2.ip6.arpa {
    log
    file 8.b.d.1.0.0.2.ip6.arpa.zone
    autoipv6ptr {
        suffix hostname.tld
    }
}
```

Coredns would traverse from top to bottom checking if a known PTR entry is stored in the zone file. If not it should fallthrough to the custom plugin generating a PTR record on the fly based on the requested IP address.   
Currently the file plugin is a backend and returns a NXDOMAIN if not found. Same applies for the secondary plugin.

Apparently after reading some blog posts and issues the usage of `fallthrough` is not desired. Is this a good enough case to alter the behaviour of file? For me of course but for you probably not. I'd love to hear your feedback abouth this.

**Comment by chrisohaver** [comment]
Since you are already writing a custom plugin, you could make that custom plugin do what you want without modifying the _file_/_secondary_ plugins.  E.g. By using the "non-writer" pattern as follows ...

* position the _autoipv6ptr_ plugin above _file_/_secondary_ in `plugin.cfg`
* have _autoipv6ptr_ first call the next plugin in the chain using a non-writer response writer.  This will allow you to see what the response is from the next plugin is before writing it to the client.
* if the answer was _not_ NXDOMAIN, write the answer as is to the client.
* if the answer _was_ NXDOMAIN, auto generate the response , and write that response to the client instead.

**Comment by chrisohaver** [comment]
A good example plugin for the "nonwriter"  approach is from the O'Reilly "Learning CoreDNS" book ... https://github.com/coredns/learning-coredns/tree/master/plugins/onlyone

**Comment by chrisohaver** [comment]
If a custom plugin was not an option here, then the _hosts_ plugin, instead of the _file_ plugin, would probably work.  It allows `fallthrough`, and supports PTR record synthesis IIRC.

**Comment by chrisohaver** [comment]
> Apparently after reading some blog posts and issues the usage of fallthrough is not desired. Is this a good enough case to alter the behaviour of file? For me of course but for you probably not.

Closing this, since there are a couple workarounds for the specific case in this issue which do not require adding fallthrough to plugins.
