### ISSUE TITLE
CoreDNS crashes when handling a surge in DNS requests

### ISSUE THREAD

**Issue by ghost** [coredns/coredns#4823]
**What happened**:

We run CoreDNS 1.8.3 on Amazon EKS 1.20. The deployment has the default memory configuration: request 70 Mi and limit 170 Mi. When our K8s cluster encountered a surge in DNS requests, CoreDNS pods crashed due to OOMKilled. Restarting the pods didn't help. The pods were only brought back up after the Deployment memory limit was increased to 1 Gi. 

**What you expected to happen**:

CoreDNS pods should handle increased workloads more gracefully. Instead of crashing and requiring manual intervention, some automated mechanism such as load shedding should have been in place to avoid total breakdown of the pods.

**How to reproduce it (as minimally and precisely as possible)**:

Not fully known yet. We are investigating the reason that we saw increased DNS requests.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.8.3
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
A plugin for CoreDNS technically could be written to drop requests to reduce load when some condition is met (e.g. QPS exceeds some rate, or number of inflight packets exceed a limit).  Configuring it would require careful tuning per deployment (probably by trial and error).  Such a plugin has been proposed before to mitigate this kind of issue, but it was not approved.

In theory, I think you could use the existing `max_concurrent`  option in the _forward_ plugin.  In the official K8s release, the _forward_ plugin configuration limits concurrent queries upstream to 1000.  However, this doesn't protect against a spike of queries for in-cluster names.  So (here's the theory part, because I have never tried this), you could configure CoreDNS with a forward server block in front.  e.g.

```
. {
  forward . 127.0.0.1:9953 {
    max_concurrent 1000
  }
}

.:9953 {
  [... normal K8s config ...]
}
```

This would be less efficient and use more memory, requiring an extra "self" forward request for every incoming request.  But it would limit the number of concurrent requests (as best it can).

Any solution in CoreDNS that processes requests to drop or actively reject (e.g. with a REFUSED response) still requires the requests to enter CoreDNS user space, and thus it could still be overwhelmed.  The best place to shed load would be _before_ it gets to CoreDNS.
