### ISSUE TITLE
middleware/proxy: unhealthy backend per query type/name?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#486]
While working on #484 I setup a proxy to 8.8.8.8:53 and then queried `isc.org.` ANY. Someone blocks these queries. This mean the proxy will flag 8.8.8.8 as unhealthy for some amount of time, but other domains and even types for `isc.org.` keep working. Clearly this needs to get more sophisticated, but not completely clear what is the solution.

Do we need to treat domain/8.8.8.8:53 as a tuple and make backend health tick on that? This would mean that `Select()` needs an argument which is the current domain begin looked up. (Or something like this).

**Comment by miekg** [comment]
Another thing here is that we mark our upstream as bad even though it's the upstream's upstream doing the wrong thing.

**Comment by johnbelamaric** [comment]
I believe that upstream's upstream issue is captured in https://github.com/coredns/coredns/issues/1035

**Comment by johnbelamaric** [comment]
Our goal here and in #1035 is to determine whether or not the upstream is alive. After discussing with @cricketliu he suggested we send a *non-recursive* query for something like the list of roots ("."/IN/NS).

We should generally get a reply to that, and it would mean the server is alive at least.

If we think we need to identify whether it can successfully recurse or otherwise resolve upstream domains, then something like what is suggested in #1035 makes sense.

**Comment by miekg** [comment]
Good point. That would mean we remove the whole setting-upstream-unhealthy from the proxy's ServeDNS and move it to a separate go routine. I think that makes sense.

**Comment by miekg** [comment]
https://github.com/coredns/coredns/pull/1093

**Comment by miekg** [comment]
the *forward* plugin should do the right thing here.
