### ISSUE TITLE
[Question] Why is forward's default policy for selecting upstream servers random?

### ISSUE THREAD

**Issue by SachinDatabricks** [coredns/coredns#4930]
Why is forward's default policy for selecting upstream servers random when other DNS resolvers (including default implementations in Linux/Unix/Windows) sequentially query nameservers with the first one listed having the highest precedence? Is this something that has been overlooked or is it an intentional design choice? 

Context: Nameservers within AWS and other cloud vendors are typically not the same targets load balanced for redundancy. Instead, it is typically a combination of private and public nameservers with the private NS having the highest precedence. This NS can handle the lookup of private endpoints/hostnames while the other nameservers will return an error or incorrect answer. The random policy leads to an unexpected and different behavior than the underlying OS. 

```
policy specifies the policy to use for selecting upstream servers. 
The default is random.

* random is a policy that implements random upstream selection.
* round_robin is a policy that selects hosts based on round robin ordering.
* sequential is a policy that selects hosts based on sequential ordering.
```

Source: https://coredns.io/plugins/forward/

**Comment by johnbelamaric** [comment]
If what you are saying is true of AWS, they are doing something completely wrong. That is not in any way the purpose of the nameserver list. In fact, some resolvers like musl (used in Alpine last I checked) use all nameservers in parallel: https://wiki.musl-libc.org/functional-differences-from-glibc.html#Name-Resolver/DNS

File a bug with AWS if that's their configuration....because it's completely broken.

**Comment by chrisohaver** [comment]
Intentional choice.  It's just a default, and can be changed if you want to behave otherwise.

The correct way to integrate a private DNS is via separate server block for the private zone.  e.g.

```
. {
  forward . /etc/resolv.conf
}

my.zone.org. {
  forward . 10.0.0.1
}
```

FWIW, if by the "behavior of the underlying OS", you are referring to `resolv.conf`: the intent of `nameserver` in `resolv.conf` is to provide multiple servers for resiliency.

**Comment by SachinDatabricks** [comment]
@johnbelamaric Agree 100% as this leads to unexpected behavior (and a "silent failure" if a NAT/internet gateway is present), created https://forums.aws.amazon.com/thread.jspa?threadID=347393 - "[Question] VPC Endpoint Services (PrivateLink) DNS configuration" for the observed behavior with the default PrivateLink/VPC configuration.
