### ISSUE TITLE
grpc:// or protocol

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#579]
This is an discussion proceeding from #574 

The gist is:
shoud a new listener be started by specifying it as a host, e.g.
~~~
grpc://.:443 { ... }
~~~
Or should we allow:
~~~
.:443 {
   protocol grpc [ssl stuff]
}
~~~

**Comment by miekg** [comment]
@johnbelamaric 

My stance is that the `grpc://` is better, because we can then treat it as "just another server". With the `protocol` thing, you're launching servers within a server - which can work, but is against the implicit CoreDNS model IMHO.

Against it: any `ssl` config you put in the server will be shared between server and what may look like an unnatural way. (My point here is that the `root` "middleware" already suffers from this)

**Comment by johnbelamaric** [comment]
Ok. So, right now you can't put do "zone:IP:port", right? I tried it and it doesn't work. You use the `bind` middleware to set the IP instead.

I think I am convinced on this. It seems a little weird to have the "host" part of the URI be the zone we are serving rather than the address we are listening on. But it does fit with what we have already.

**Comment by miekg** [comment]
Thanks for your input. This is also inline with caddy - which I still consider a plus.
