### ISSUE TITLE
outdated document?

### ISSUE THREAD

**Issue by huang195** [coredns/coredns#642]
Trying to deploy coredns in a k8s federation. I found some instructions here: https://kubernetes.io/docs/tutorials/federation/set-up-coredns-provider-federation/, in which it was mentioned that an etcd instance needs to be pre-installed, as if it's being used by coredns backend. I thought just like skydns, coredns takes information from etcd and various others, but doesn't need a persistent storage. Is the documentation outdated or I misunderstood something?

**Comment by johnbelamaric** [comment]
If you are deploying CoreDNS as the in-cluster DNS service discovery, it does not need any persistent storage because it uses the K8s API directly.

Setting up CoreDNS as a federation provider means it is serving the domains where you plan to publish your DNS records for federation. This would be a separate instance from any in-cluster service discovery. The federation controller will write records to etcd, and CoreDNS will read them from etcd. So, you'll need to have etcd running in that case. The same would be true of SkyDNS or any other DNS server used for federation - it needs somewhere to store the records provided by the federation controller.

**Comment by huang195** [comment]
@johnbelamaric thanks for that quick response. That makes sense. I realized that some of my questions might not be appropriate as github issues, but I didn't find information about a Slack channel. If there's one, can you please point me to it? Thanks!

**Comment by johnbelamaric** [comment]
#coredns on https://slack.cncf.io

Twitter works too. Or Caddy forum.
