### ISSUE TITLE
middleware/kubernetes: investigate what happens when Kube API goes down

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#720]
This came up in the Twitterverse recently: https://twitter.com/rothgar/status/872486629952241664

Basically, if the K8s API server dies for an extended period, the actual production services continue to run (as one would expect). The question is what happens to the service discovery. We should make sure we can maintain our API object cache indefinitely, if the API server is down.

**Comment by yongtang** [comment]
It should be possible to specify multiple Kubernetes api servers so that in case one server is down, it is still possible to access another server (assuming etcd is ok).

**Comment by yongtang** [comment]
The redundancy of Kubernetes api servers will be similar to `--api-servers` flag for which you could specify multiple API end points. Not sure Kubernetes truly support high-availability in this case. I will take a closer look at Kubernetes and see how it is being done.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/ku..." ]
>The redundancy of Kubernetes api servers will be similar to `--api-servers` flag for which you could specify multiple API end points. Not sure Kubernetes truly support high-availability in this case. I will take a closer look at Kubernetes and see how it is being done.

isn't *caching* *caching* *caching* the name of the game here? (At least for DNS
naming). We could teach the caching middleware to do something special for
soon-to-expire names while the backend is down (meaning: don't expunge)

Might be leading to some kludges in the caching middleware though - not sure if
this is the best thing to do.

**Comment by chrisohaver** [comment]
There are two "caches" at play.  There is the coredns cache of dns responses.  But in kubernetes middleware, there is the API object cache.  Per my understanding it's a complete list of all services and endpoints (and also pods if 'pods verified' is enabled).

The kubernetes "cache" is updated by watchers.  Not updated by requests/access. I doubt there is any time based expiration on the API cache.  I suspect if the watchers cannot reach the API, then they would leave the API cache as is.  But its worth testing.  Also, there is a periodic refresh associated with the watch cache.  I'd assume cache is left in place if that fails too, but we should make sure.

**Comment by johnbelamaric** [comment]
@yongtang that's not really an issue. In general CoreDNS will be using the ClusterIP and so the redundancy built into Kubernetes will handle that. My question was more along the lines of what @chrisohaver is saying - how long will we retain items in the K8s object cache.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/ku..." ]
>There are two "caches" at play.  There is the coredns cache of dns responses.  But in kubernetes middleware, there is the API object cache.  Per my understanding it's a complete list of all services and endpoints (and also pods if 'pods verified' is enabled).
>
>The kubernetes "cache" is updated by watchers.  Not updated by requests/access. I doubt there is any time based expiration on the API cache.  I suspect if the watchers cannot reach the API, then they would leave the API cache as is.  But its worth testing.  Also, there is a periodic refresh associated with the watch cache.  I'd assume cache is left in place if that fails too, but we should make sure.

Ah thanks. That sounds like a should just work (TM).

/Miek

--
Miek Gieben

**Comment by yongtang** [comment]
Yes the ClusterIP will get the endpoint once connected but the `APIEndpoints` *(clusterinfo.Server)* at the middleware startup time still may not be available initially:
https://github.com/coredns/coredns/blob/5c10eba31c17dcc5d95431e655280fff19979a34/middleware/kubernetes/kubernetes.go#L199-L201

In a distributed scenario where k8s api server, k8s cluster, and coredns servers are distributed across different nodes:
```
    [k8s api server 1]   [k8s api server 2]  [k8s api server 3]

                    [coredns 1]       [coredns 2]
```
, the availability of k8s api server 1, 2, 3 may not be guaranteed. Eventually **at least** one is working. And you only need one of the 1, 2, 3 to be working (instead of waiting for the availability of a particular one specified in the config file (`endpoint https://k8s-endpoint:8080`)

The `endpoint` in the Corefile could be converted into a list:
```
kubernetes coredns.local {
	# endpoint <url>
	#
	# Use url for a remote k8s API endpoint.  If omitted, it will connect to
	# k8s in-cluster using the cluster service account.
	#
	endpoint https://k8s-endpoint1:8080,https://k8s-endpoint2:8080,https://k8s-endpoint3:8080
```

**Comment by johnbelamaric** [comment]
Sure, but in general we don't use the `endpoint` directive, because we are running in-cluster. That's used for tests but I wouldn't expect it to be used in production, where it uses a service account and endpoint given to it by K8s.

**Comment by yongtang** [comment]
There will be cases where in production you want to run coredns outside of k8s managed containers. In fact I am in favor of this way in production as it helps the stability of the overall cluster.

When we were investigating Mesos/Marathon some time ago, we used Mesos to *self-manage* Mesos itself and Zookeeper. It ends up in multiple cases the non-availability of one component trickle-down a lot more components. k8s might be better in this scenario but it is still not necessarily a better architecture.

I think we could add the minimal support of specifying multiple endpoints.

**Comment by johnbelamaric** [comment]
Sure, it's easy to add. We can do it when we fix #690

**Comment by miekg** [comment]
#690 is fixed, anything left here?

**Comment by chrisohaver** [comment]
#690 isn't really related to the original raised issue.

Determining what happens when the Kube API goes down still warrants investigation.
I suspect the records will remain indefinitely, in the state they were when the API went down, and that errors would get logged on the refresh interval. But this should be confirmed.

**Comment by yongtang** [comment]
From a HA point of view, the kubernetes by default does not really handle High-Availability. For example, even though it is possible to specify multiple api servers with `--api-servers`, kubelet will always pick the first one:
https://github.com/kubernetes/kubernetes/blob/45b47c7faa78d8d4f66f3de4218baad4a32397ca/cmd/kubelet/app/server.go#L761-L764

For that from an operational point of view, it might be good to always place one CoreDNS server in front of one k8s API server.

When the specific API server behind a particular CoreDNS server is down, we could refuse k8s related DNS queries so that end user could find the next available CoreDNS server (in front of another API server).

Another option is to round robin the back-end k8s api server but that seems to be quite complicated given k8s is not truly High-Availability.

**Comment by yongtang** [comment]
We could also have a reverse proxy setup so that one CoreDNS server could be pointed to one Proxy with multiple k8s api servers as the backend. This will handle the cases where one API server might be  down.

**Comment by yongtang** [comment]
I setup a Kubernetes cluster with CoreDNS on AWS with CloudFormation. The CoreDNS is deployed through out-of-cluster deployments and points to a nginx with multiple k8s api servers as the upstream backend. That should resolve the issues with one api server down for CoreDNS:

https://github.com/yongtang/kubernetes-cfn/blob/master/cfn/vpc.yaml

This is more like a PoC. We may want to consider adding a simple proxy in place (in k8s middleware) to address the issue.

The in-cluster-deployment of CoreDNS in k8s may need to be investigated further.

**Comment by johnbelamaric** [comment]
In-cluster will use ClusterIP, so something like a reverse proxy isn't needed. But what we do want to check is how long the K8s client will hold onto the cached objects when it can't connect to the API.
