### ISSUE TITLE
middleware/rewrite: Support for variables in EDNS0 local options

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#802]
Right now, the rewrite allows you to append static data (from the Corefile) in EDNS0 local options. This works for some use cases, but for others there is a need to populate these options with various data about the original request (which will then be proxied so the receiving proxy wouldn't have this data otherwise). For example, the ability to grab:

* `qname`
* `qtype`
* `client_ip`
* `client_port`
* `protocol`
* `server_ip`
* `server_port`

Right now I have a specific use case for client_source_ip and not the others. But it seems like we should add the basic data we have in there.

I imagine something like:

```
rewrite edns0 local set 0xffee $client_ip
```

**Comment by huynhmb359** [comment]
John,  I'll start with the list you provided.   The macro name will be exactly as in the list.

**Comment by huynhmb359** [comment]
For qname and qtype,  the question section may have more than 1 question.   Which one should we select or are we going to report them all?

**Comment by johnbelamaric** [comment]
@miekg I have noticed we only process the first question (https://github.com/coredns/coredns/blob/master/core/dnsserver/server.go#L188) is that normal?

**Comment by miekg** [comment]
What? Multiple questions in the section section. No that will never work. Although DNS was designed to support this, a reply could only have rcode making the notion useless

**Comment by huynhmb359** [comment]
Thanks for the response.  It's confirmed that we are expecting only one question in the "question section". 

I need to fetch the LocalAddr in the query (i.e. server IP/port).  The  Request object provides APIs to access to the RemoteAddr (i.e. client IP/port) like  IP()/Family()/Port().  Can we add the similar APIs to access the LocalAddr in the Request object?

**Comment by miekg** [comment]
LocalAddr? Yes, this is available in the dns.ResponseWriter.

**Comment by huynhmb359** [comment]
Yes LocalAddr is available in dns.ResponseWriter.  However,  the Request has a set of APIs that conveniently read the information in the RemoteAddr.   These include parsing IP/ IP version check ...etc.
Reading the raw LocalAddr is identical to the reading of raw RemoteAddr.   In stead of duplicating the code,  I wonder if we can add these into the Request so that the common code can be extracted and reused.

**Comment by miekg** [comment]
Sorry, with Request you mean `request.Request`. If so you can just access the `responseWriter` with:
```
r = request.Request{...}
r.W.LocalAddr()
```

**Comment by huynhmb359** [comment]
That is not exactly my question.  For example,  in the request.Request,  there is a function called  Family(),   
`
func (r *Request) Family() int {
	var a net.IP
	ip := r.W.RemoteAddr()
	if i, ok := ip.(*net.UDPAddr); ok {
		a = i.IP
	}
	if i, ok := ip.(*net.TCPAddr); ok {
		a = i.IP
	}
	if a.To4() != nil {
		return 1
	}
	return 2
}
`
This function operates on the r.W.RemoteAddr().   I would like to add a function that does the same but operates on r.W.LocalAddr(),  called like request.LocalFamily() .    Since the implementation would be almost identical,  it may be a good idea to extract a common utility function that take the net.Addr and return a family.  Both  request.Family() and request.LocalFamily() will call the utility function with the corresponding net.Addr. 
Similar approach from  request.IP() and request.Port(). 

Alternatively,  I can simply add these functions into the middleware.rewrite and use it locally.

**Comment by miekg** [comment]
I don't understand, when is the family from the client different to what
the server sees?

Having a local impl. in a middleware before extracting anything out seems
like a good idea to me.
