### ISSUE TITLE
k8s axfer inventory

### ISSUE THREAD

**Issue by kfox1111** [coredns/coredns#806]
Say I have the following setup:

1. external dns server which is the primary for my domain (and a stand alone system)
2. a k8s system with a VIP for exporting services on.

I would like to:
1. Run coredns as a k8s deployment so it can scale up/down as needed.
2. use the slave middleware so that it can be bound to the primary and take load off of it.
3. expose all the coredns instances via the VIP to the outside world.

This has one issue I can see currently. Refreshing the records. I would have to expose each coredns instance to the extermal dns server, as well as put in the slaves manually into its config file before ixfr transfers would happen properly.

Instead, what about the following:
Support a new setting in the slave for getting TransferTo settings from k8s via label selector. Whenever an ixfr comes in, it refreshes (and removes itself from the list) Then forwards the request on.

That way, only the VIP needs to be registered with the external dns entry. only one instance of coredns would recieve the ixfr, and it would forward it to all the others in the deployment.

**Comment by johnbelamaric** [comment]
Interesting idea. Not sure I want to mix the slave so directly with K8s. We do need something like this for the [multi-cluster/federated service discovery proposal](https://docs.google.com/document/d/1tvDE7oTAOKEPQr2HQDgCZQFDoVCoiy_ICQmvUIy6h5Y/edit#heading=h.yw4waelx1f33) as well.

Essentially what we want is a way for the group of CoreDNS instances running under the same deployment to make themselves part of a "group". Your suggestion is to use K8s as the state storage for that. I am wondering if there is some more general-purpose way to do that. Either generic key-value store. Or raft internally (no...).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] k8s ixfer inv..." ]
>Interesting idea. Not sure I want to mix the slave so directly with K8s. We do need something like this for the [multi-cluster/federated service discovery proposal](https://docs.google.com/document/d/1tvDE7oTAOKEPQr2HQDgCZQFDoVCoiy_ICQmvUIy6h5Y/edit#heading=h.yw4waelx1f33) as well.
>
>Essentially what we want is a way for the group of CoreDNS instances running under the same deployment to make themselves part of a "group". Your suggestion is to use K8s as the state storage for that. I am wondering if there is some more general-purpose way to do that. Either generic key-value store. Or raft internally (no...).

Indeed. If you were to provision the DNS servers in k8s from etcd, instead of an 
external DNS server you almost have what you want. You *can* do this with the 
etcd backend, but this doesn't support all record types (only the most common 
once and no DNSSEC). (Enough room for improvement there).

Any specific reason why the DNS server outside the k8s cluster must be accesible
via the internet?

**Comment by kfox1111** [comment]
@johnbelamaric  yeah, you could have coredns register with etcd or something the membership and  do the same thing as above with s/k8s/etcd/. but in a k8s environment, it would be nicer to just use the inventory directly from k8s. I think its a single rest call to do to the query.

**Comment by kfox1111** [comment]
@miekg external to k8s != internet. :)

we currently have a primary that is maintained by cobbler. cobbler maintains a bind9 zone and we currently replicate it out to bind9 based slave vm's via axfer/ixfer. so pretty seamless. access is all over internal (to project, not k8s) networking.

I'm looking at how to pull most of the heavy lifting of dns queries into k8s in containers rather then in vm's.

Having slaves in k8s that point to a master that isn't coredns is a good use case in general I think though.

Perhaps there is another way to do this too... Option 2, You could have a single coredns server outside the regular k8s svc, on its own port. it would be an ixfer endpoint that the primary points to, and syncs data into etcd. then all the other slaves use etcd instead. This would require a separate tcp port externally available, but may be easier to implement?

It would be harder on a user though. would need a second deployment for the ixfer coredns and an instance (or more) of etcd for storage.

Maybe a third option would be a coredns ixfer server that would sync/upload a received zone to k8s as a configmap. Slaves could just share that out and k8s would ensure replication to all the coredns slaves.

I kind of like the scalability of the pure ixfer replication scheme listed in the original request though.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] k8s ixfer inv..." ]
>Having slaves in k8s that point to a master that isn't coredns is a good use case in general I think though.

Yep, it is.

But I don't see why you need this administration. The external DNS' IP address 
fixed. So you open up AXFR to all and let the CoreDNS secondaries just fetch 
from the external IP address. Still is all static and the config can be shared 
between all CoreDNS instances (i.e. some container).

Why wouldn't that work?

**Comment by johnbelamaric** [comment]
Notifies won't work, but otherwise this should be ok. How often is the polling, or is it TTL-based?

On Aug 2, 2017, at 6:14 AM, Miek Gieben <notifications@github.com<mailto:notifications@github.com>> wrote:

[ Quoting <notifications@github.com<mailto:notifications@github.com>> in "Re: [coredns/coredns] k8s ixfer inv..." ]
>Having slaves in k8s that point to a master that isn't coredns is a good use case in general I think though.

Yep, it is.

But I don't see why you need this administration. The external DNS' IP address
fixed. So you open up AXFR to all and let the CoreDNS secondaries just fetch
from the external IP address. Still is all static and the config can be shared
between all CoreDNS instances (i.e. some container).

Why wouldn't that work?

**Comment by kfox1111** [comment]
I dug through the code a bit. AXFR is done based on TTL info from the SOA. so it can be long out of date without IXFR support. There is no polling support currently. Though maybe not too hard to add.

**Comment by kfox1111** [comment]
I was also thinking about the initial request... If you use a k8s service to export it externally, there is no way to know the source ip, so the security of the IXFR is totally shot. So maybe not a good option after all.

So, what about running a slave on the external nodes, net=host. that allows the ip's to be registered directly with the primary. These would be treated more like reflectors. They would forward to the real secondaries.

I think this would just require two different settings.
1, a way for TransferTo to accept a k8s label selector for dynamic membership. (set on the reflectors)
2, a way for TransferFrom to accept a k8s label selector for dynamic membership. (set on the real secondaries)

What do you think?

**Comment by miekg** [comment]
The reason I'm pushing back a bit is this: I want to keep each middleware self-contained. Using k8s syntax and techniques in the *secondary* middleware, works, but makes *secondary* somewhat involved with the *kubernetes* middleware. This complicates the overall design of CoreDNS.

Coming back to the problem:
1. There isn't much harm in making SOA's refresh rate small, i.e. check every 30s? 3s?
2. If reliant on notifies, the problem is, they can't go anyway because you don't have the internal k8s IP addresses, only the VIP. 
   * Sending to the VIP means only 1 of the CoreDNSs gets the notify, not the others.
   * What you want is CoreDNS in cluster to notify all other instances that there is new data

The last bullet specifies a new middleware (I think) that:
* listens for notifies (or whatever)
* has a forward spec (query another DNS server, query k8s)
* forward what it has to all these instances

Does that capture your use case?

**Comment by kfox1111** [comment]
shrinking the SOA's affect caching times. That may invalidate downstream caches faster then needed, requiring more secondaries to handle the extra load, and adding more load to the primary.

Yeah, I think that bullet list captures a way to do what I need.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] k8s ixfer inv..." ]
>shrinking the SOA's affect caching times. That may invalidate downstream caches 
>faster then needed, requiring more secondaries to handle the extra load, and 
>adding more load to the primary.

No it does not, these are separate timers, not related to RR's TTLs

>Yeah, I think that bullet list captures a way to do what I need.

good :-)

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
I believe https://github.com/Creamfinance/coredns-dbcheck is more promising than adding secondary disk support

**Comment by kfox1111** [comment]
the idea behind secondary disk support is to persist local storage. This will scale quite well. Persisting it in a relationaldb may have performance issues, as well as much more overhead on the operator to setup/maintain/scale the relational db.

**Comment by miekg** [comment]
Yes, true. Also failure is more localized. I need to give this more thought.
