### ISSUE TITLE
mw/kubernetes: integration tests

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#982]
What is the difference between these two tests? They look identical, except the for the non-working endpoints that are configured? Why is this a full blown integration tests? Can we just test the endpoint traversel in a small unit test?
~~~
func TestKubernetesIntegration(t *testing.T) {

	removeUpstreamConfig, upstreamServer, udp := createUpstreamServer(t)
	defer upstreamServer.Stop()
	defer removeUpstreamConfig()

	corefile :=
		`.:0 {
    kubernetes cluster.local 0.0.10.in-addr.arpa {
                endpoint http://localhost:8080
		namespaces test-1
		pods disabled
		upstream ` + udp + `
    }
	erratic . {
		drop 0
	}
`
	doIntegrationTests(t, corefile, dnsTestCases)
}

func TestKubernetesIntegrationAPIProxy(t *testing.T) {

	removeUpstreamConfig, upstreamServer, udp := createUpstreamServer(t)
	defer upstreamServer.Stop()
	defer removeUpstreamConfig()

	corefile :=
		`.:0 {
    kubernetes cluster.local 0.0.10.in-addr.arpa {
        endpoint http://nonexistance:8080,http://invalidip:8080,http://localhost:8080
        namespaces test-1
        pods disabled
        upstream ` + udp + `
    }
    erratic . {
        drop 0
    }
`
	doIntegrationTests(t, corefile, dnsTestCases)
}
~~~

**Comment by chrisohaver** [comment]
I believe @yongtang added this test.

IMO, this warrants an integration test because it deals with the actual connection to the kubernetes API.  This would be hard to cover well in a unit test.

But, _all_ of the tests cases in `dnsTestCases` do not need to be executed.  Perhaps just one test case, that verifies the api connection is successful (e.g. one `A` query for `svc-1-a.test-1.svc.cluster.local.`). 

@yongtang, does that sound fair?

**Comment by miekg** [comment]
+1 to what @chrisohaver said
