### ISSUE TITLE
mw/hosts: inline /etc/hosts file?

### ISSUE THREAD

**Issue by yongtang** [coredns/coredns#999]
In our production we were trying to use `middleware/hosts` to add just a couple of entries from `/etc/hosts` file. At the moment a separate file has to be created even though we only need a couple of lines.

Since `/etc/hosts` file itself is line based and is rather straightforward, I think it makes sense to support the inline of `/etc/hosts` inside Corefile. That will be especially convenient when only one or two lines of `/etc/hosts` are used.

**Comment by miekg** [comment]
This makes a lot of sense. We also allow this for `etc/resolv.conf` entries essentially in the `upstream` syntax.
(/cc @pmoroney). Any ideas for syntax, following allow re-using current parser:
~~~
hosts {
    host 127.0.0.0 localhost [alias]
}
~~~
Should this add hosts are reset any know entries? Think addition makes most sense.

**Comment by yongtang** [comment]
Assigned it to me . Will work on it later.

**Comment by pmoroney** [comment]
Sorry I somehow missed this thread. This sounds like a great idea to me.
Currently Hostsfile.Parse() overwrites the current maps. This is so that if the hosts file is modified it will parse the new file and forget about the old entries.

I see three ways we can do this:

- Pull out the parsing logic in Parse() to a new function and have it just return the new maps, and use that 
new function in a Merge() function that gets called every time after we check the file for updates.
- Modify Hosts to have a slice of Hostfiles and check them in order.
- Restrict it so specifying both a file and inline entries is an invalid configuration

I think I prefer the slice of Hostfiles option myself.
As for the config we could just check to see if the first line is `fallthrough` and then just parse the rest as if it is a hosts file. I think we will want to display warnings for lines that don't have valid host entries.

(also it looks like I forgot to lock the mutex when overwriting the maps in Hostfile.Parse(), I'll have to fix that)
